create or replace TABLE PRE.PDIM_DOC_ORDENFABRICACION (
ORDENFABRICACION_ID	VARCHAR PRIMARY KEY,
MATERIAL_ID	VARCHAR,
SOCIEDAD_ID	VARCHAR,
CENTRO_ID	VARCHAR,
SECTOR_ID	VARCHAR,
CLASEORDFAB_ID	VARCHAR,
TIPOORDFAB_ID	NUMBER,
CLIENTE_ID	VARCHAR,
LOTE	VARCHAR,
ORDENFABRICACION_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

create or replace TABLE CON.DIM_DOC_ORDENFABRICACION (
ORDENFABRICACION_ID	VARCHAR PRIMARY KEY,
MATERIAL_ID	VARCHAR,
SOCIEDAD_ID	VARCHAR,
CENTRO_ID	VARCHAR,
SECTOR_ID	VARCHAR,
CLASEORDFAB_ID	VARCHAR,
TIPOORDFAB_ID	NUMBER,
CLIENTE_ID	VARCHAR,
LOTE	VARCHAR,
ORDENFABRICACION_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);