CREATE OR ALTER TABLE MIRRORING.DIM_FIN_CUENTA(
    CUENTA_ID VARCHAR(15),
    SOCIEDADCO_ID VARCHAR(4),
    CUENTA VARCHAR(10),
    CUENTA_TEXT VARCHAR(40),
    CUENTA_ID_TEXT VARCHAR(60),
    SUBDIVISION_ID VARCHAR(132),
    SUBDIVISION_TEXT VARCHAR(40),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_CUENTA
ON TABLE MIRRORING.DIM_FIN_CUENTA;