CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_EQUIPORESPCREDITO (
	EQUIPORESPCREDITO_ID VARCHAR(8),
	EQUIPORESPCREDITO VARCHAR(3),
	EQUIPORESPCREDITO_TEXT VARCHAR(30),
    EQUIPORESPCREDITO_ID_TEXT VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_EQUIPORESPCREDITO
ON TABLE MIRRORING.DIM_FIN_EQUIPORESPCREDITO;