CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_CENTROBENEFICIO(
	CENTROBENEFICIO_ID VARCHAR(15),
	SOCIEDADCO_ID VARCHAR(4),
	CENTROBENEFICIO VARCHAR(10),
	CENTROBENEFICIO_TEXT VARCHAR(40),
    CENTROBENEFICIO_ID_TEXT VARCHAR(60),
	SISORIGEN_ID VARCHAR(4),
	MANDANTE VARCHAR(4),
	FECHA_CARGA TIMESTAMP_TZ(9),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_CENTROBENEFICIO
ON TABLE MIRRORING.DIM_FIN_CENTROBENEFICIO;