CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_SOCIEDADCO(
SOCIEDADCO_ID VARCHAR(4),
SOCIEDADCO_TEXT VARCHAR(40),
SOCIEDADCO_ID_TEXT VARCHAR(50),
SISORIGEN_ID VARCHAR(4),
MANDANTE VARCHAR(4),
FECHA_CARGA TIMESTAMP_TZ,
ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_SOCIEDADCO
ON TABLE MIRRORING.DIM_FIN_SOCIEDADCO;