CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_POSICIONPRES (
	POSICIONPRES_ID VARCHAR(29),
	POSICIONPRES VARCHAR(24),
	POSICIONPRES_TEXT VARCHAR(60),
    POSICIONPRES_ID_TEXT VARCHAR(90),
	ENTIDADCP_ID VARCHAR(4),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_POSICIONPRES
ON TABLE MIRRORING.DIM_FIN_POSICIONPRES;