CREATE OR ALTER TABLE MIRRORING.DIM_FIN_GRUPOCUENTA(
CUENTA_GRUPO_ID	VARCHAR(30),
SUBCLASE_ID	VARCHAR(20),
CUENTA_INICIO VARCHAR(30),
CUENTA_FIN VARCHAR(30),
SISORIGEN_ID VARCHAR(4),
MANDANTE VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_GRUPOCUENTA
ON TABLE MIRRORING.DIM_FIN_GRUPOCUENTA;