CREATE OR ALTER TABLE MIRRORING.DIM_FIN_DETALLECOMPREAL (
	DETALLECOMPREAL_ID VARCHAR(3),
	DETALLECOMPREAL_TEXT VARCHAR(20),
    DETALLECOMPREAL_ID_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_DETALLECOMPREAL
ON TABLE MIRRORING.DIM_FIN_DETALLECOMPREAL;