CREATE OR ALTER TABLE MIRRORING.DIM_FIN_ACREEDOR(
    ACREEDOR_ID VARCHAR(10),
	ACREEDOR_TEXT VARCHAR(35),
    ACREEDOR_ID_TEXT VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(4),
	FECHA_CARGA TIMESTAMP_TZ(9),
	ZONA_HORARIA VARCHAR(12)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_ACREEDOR
ON TABLE MIRRORING.DIM_FIN_ACREEDOR;