CREATE OR REPLACE TABLE MIRRORING.FCT_FIN_CONTROLPRESUPUESTAL(
    ANIO VARCHAR(4),
	MES VARCHAR(2),
	ANIOMES VARCHAR(6),
	SOCIEDADCO_ID VARCHAR(4), --clave
	SOCIEDAD_ID VARCHAR(4),
	ENTIDADCP_ID VARCHAR(4), --clave
	CATEGORIAPRES_ID VARCHAR(1),
	TIPOVALOR_ID VARCHAR(2),
	FONDO_ID VARCHAR(10),
	CENTROGESTOR_ID VARCHAR(21),
	CENTROGESTOR VARCHAR(21),
	DETALLECOMPREAL_ID VARCHAR(3),
	INDICADOREST_ID VARCHAR(1),
	PROGRAMAPRES_ID VARCHAR(29),
	PROGRAMAPRES VARCHAR(29),
	POSICIONPRES_ID VARCHAR(29),
	POSICIONPRES VARCHAR(29),
	CENTROCOSTO_ID VARCHAR(21), --clave
	CENTROCOSTO VARCHAR(21),
	CUENTA_ID VARCHAR(29), --clave
	CUENTA VARCHAR(29),
	ACREEDOR_ID VARCHAR(10),
	DEUDOR_ID VARCHAR(10),
	GASTOER_ID VARCHAR(2),
	FECHA_CONTABILIZACION DATE, --clave
    TEXTO_TEXT VARCHAR(60),
	IND_PRESUPUESTO_ASIGNABLE NUMBER(23,2),
	IND_PRESUPUESTO_ASIGNADO NUMBER(23,2),
	IND_PRESUPUESTO_GASTOREAL NUMBER(23,2),
	IND_PRESUPUESTO_GASTOCOMP NUMBER(23,2),
	IND_PRESUPUESTO_DISPONIBLE NUMBER(27,2),
	IND_PRESUPUESTO_ACTUAL NUMBER(23,2),
	IND_PRESUPUESTO_COMPREAL NUMBER(23,2),
	IND_PRESUPUESTO_VALORREAL NUMBER(23,2),
	MON_ENTCP VARCHAR(5),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA TIMESTAMP_TZ,
	ZONA_HORARIA VARCHAR(10),
	PRIMARY KEY (SOCIEDADCO_ID,ENTIDADCP_ID,CENTROCOSTO_ID,CUENTA_ID,FECHA_CONTABILIZACION)
);


CREATE OR REPLACE STREAM MIRRORING.STREAM_FCT_FIN_CONTROLPRESUPUESTAL
ON TABLE MIRRORING.FCT_FIN_CONTROLPRESUPUESTAL;



SELECT * FROM MIRRORING.FCT_FIN_CONTROLPRESUPUESTAL