CREATE OR ALTER TABLE MIRRORING.DIM_FIN_GRUPOCREDCLIENTE(
	GRUPOCREDCLIENTE_ID VARCHAR(9),
	GRUPOCREDCLIENTE VARCHAR(4),
	GRUPOCREDCLIENTE_TEXT VARCHAR(30),
    GRUPOCREDCLIENTE_ID_TEXT VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_GRUPOCREDCLIENTE
ON TABLE MIRRORING.DIM_FIN_GRUPOCREDCLIENTE;