CREATE OR ALTER TABLE MIRRORING.DIM_FIN_CLASERIESGO(
	CLASERIESGO_ID VARCHAR(8),
	CLASERIESGO VARCHAR(3),
	CLASERIESGO_TEXT VARCHAR(30),
    CLASERIESGO_ID_TEXT VARCHAR(40),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_CLASERIESGO
ON TABLE MIRRORING.DIM_FIN_CLASERIESGO;