create or replace view CON.VW_DIM_TRA_TRANSPORTISTA (
    TRANSPORTISTA_ID,
    TRANSPORTISTA_TEXT,
/*    SE ELIMINAN POR SOLICITUD DE DANIEL GORDILLO 23/06/2025
    CLIENTE_ID,
    CLIENTE_TEXT,
    REGION_ID,
    REGION_TEXT,
    CENTRO_ID,
    CENTRO_TEXT,
*/
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) as
    SELECT
    t.TRANSPORTISTA_ID,
    t.TRANSPORTISTA_TEXT,
    /* 
    t.CLIENTE_ID,
    d1.CLIENTE_TEXT,
    t.REGION_ID,
    d2.REGION_TEXT,
    t.CENTRO_ID,
    d3.CENTRO_TEXT,
    */
    t.SISORIGEN_ID,
    t.MANDANTE,
    t.FECHA_CARGA,
    t.ZONA_HORARIA
    FROM CON.DIM_TRA_TRANSPORTISTA t
   /* LEFT JOIN DIM_CLI_CLIENTE d1 ON t.CLIENTE_ID = d1.CLIENTE_ID
    LEFT JOIN DIM_GEO_REGION d2 ON t.REGION_ID = d2.REGION_ID
    LEFT JOIN DIM_ORG_CENTRO d3 ON t.CENTRO_ID = d3.CENTRO_ID*/
    ;