CREATE OR REPLACE TASK MIRRORING.TASK_FCT_FIN_GASTOS
    warehouse=LAMOSALAKE_DEV_WH
	WHEN SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_FIN_GASTOS')
	AS BEGIN

    -- 1. TRUNCAR tabla temporal
    TRUNCATE TABLE MIRRORING.TR_FCT_FIN_GASTOS;

    -- 2. INSERTAR datos desde el stream a la temporal
    INSERT INTO MIRRORING.TR_FCT_FIN_GASTOS
    SELECT * FROM MIRRORING.STREAM_VW_FCT_FIN_GASTOS;

    -- 3. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_FIN_GASTOS AS FACTGASTOS
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_GASTOS
            WHERE METADATA$ACTION = 'DELETE'
    ) AS TR
    WHERE FACTGASTOS.SOCIEDAD_ID = TR.SOCIEDAD_ID
    AND FACTGASTOS.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTGASTOS.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTGASTOS.CUENTA_ID = TR.CUENTA_ID
    AND FACTGASTOS.ANIOMES = TR.ANIOMES;

    -- 4. INSERTAR o ACTUALIZAR registros nuevos o modificados
    MERGE INTO MIRRORING.FCT_FIN_GASTOS AS FACTGASTOS
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_GASTOS
            WHERE METADATA$ACTION = 'INSERT'
    ) AS TR
    
    ON FACTGASTOS.SOCIEDAD_ID = TR.SOCIEDAD_ID
    AND FACTGASTOS.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTGASTOS.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTGASTOS.CUENTA_ID = TR.CUENTA_ID
    AND FACTGASTOS.ANIOMES = TR.ANIOMES
    
    WHEN NOT MATCHED THEN INSERT (
        TIPO,
        ANIO,
        MES,
        ANIOMES,
        FECHA_CONTABILIZACION,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        CUENTAMAYOR_ID,
        GASTOER_ID,
        CENTRO_ID,
        ACREEDOR_ID,
        SOCIEDADGLASOC_ID,
        VERSION_ID,
        IND_GASTOPRESUPUESTO_MXN,
        IND_GASTOPRESUPUESTO_SOC,
        IND_GASTOPRESUPUESTO_USD,
        IND_GASTOPRESUPUESTO_V0_SOC,
        IND_GASTOPRESUPUESTO_V1_SOC,
        IND_GASTOPRESUPUESTO_V2_SOC,
        IND_GASTOPRESUPUESTO_V3_SOC,
        IND_GASTOPRESUPUESTO_V0_MXN,
        IND_GASTOPRESUPUESTO_V1_MXN,
        IND_GASTOPRESUPUESTO_V2_MXN,
        IND_GASTOPRESUPUESTO_V3_MXN,
        IND_GASTOPRESUPUESTO_V0_USD,
        IND_GASTOPRESUPUESTO_V1_USD,
        IND_GASTOPRESUPUESTO_V2_USD,
        IND_GASTOPRESUPUESTO_V3_USD,
        IND_GASTOREAL_MXN,
        MON_MXN,
        IND_GASTOREAL_USD,
        MON_USD,
        IND_GASTOREAL_SOC,
        MON_SOC,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    ) VALUES (
        TIPO,
        ANIO,
        MES,
        ANIOMES,
        FECHA_CONTABILIZACION,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        CUENTAMAYOR_ID,
        GASTOER_ID,
        CENTRO_ID,
        ACREEDOR_ID,
        SOCIEDADGLASOC_ID,
        VERSION_ID,
        IND_GASTOPRESUPUESTO_MXN,
        IND_GASTOPRESUPUESTO_SOC,
        IND_GASTOPRESUPUESTO_USD,
        IND_GASTOPRESUPUESTO_V0_SOC,
        IND_GASTOPRESUPUESTO_V1_SOC,
        IND_GASTOPRESUPUESTO_V2_SOC,
        IND_GASTOPRESUPUESTO_V3_SOC,
        IND_GASTOPRESUPUESTO_V0_MXN,
        IND_GASTOPRESUPUESTO_V1_MXN,
        IND_GASTOPRESUPUESTO_V2_MXN,
        IND_GASTOPRESUPUESTO_V3_MXN,
        IND_GASTOPRESUPUESTO_V0_USD,
        IND_GASTOPRESUPUESTO_V1_USD,
        IND_GASTOPRESUPUESTO_V2_USD,
        IND_GASTOPRESUPUESTO_V3_USD,
        IND_GASTOREAL_MXN,
        MON_MXN,
        IND_GASTOREAL_USD,
        MON_USD,
        IND_GASTOREAL_SOC,
        MON_SOC,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    );
END;