CREATE OR REPLACE TASK MIRRORING.TASK_FCT_FIN_ADH_VENTAS
	WAREHOUSE=LAMOSALAKE_DEV_WH
	WHEN SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_FIN_ADH_VENTAS_2')
	AS BEGIN

    -- RECREAR STREAM para eliminar basura
    -- create or replace stream MIRRORING.STREAM_FCT_FIN_ADH_CARTERA_2 on table MIRRORING.FCT_FIN_ADH_CARTERA_2;
    
    -- 1. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_FIN_ADH_CARTERA
    WHERE MODELO = 'VENTAS'
    AND SISORIGEN_ID <> 'BW4'; --Ventana de Tiempo
          

    -- 2. INSERTAR registros
    -- Insertar Todas la Ventas BW4
    INSERT INTO MIRRORING.FCT_FIN_ADH_CARTERA
    SELECT *
    FROM MIRRORING.VW_FCT_FIN_ADH_VENTAS_2 src
    WHERE src.MODELO = 'VENTAS'
    AND src.SISORIGEN_ID = 'BW4'
    AND NOT EXISTS (
            SELECT 1
            FROM MIRRORING.FCT_FIN_ADH_CARTERA tgt
            WHERE tgt.SISORIGEN_ID = src.SISORIGEN_ID
    );
    
    -- Insertar Todas la Ventas distintas BW4
    INSERT INTO MIRRORING.FCT_FIN_ADH_CARTERA
    SELECT *
    FROM MIRRORING.VW_FCT_FIN_ADH_VENTAS_2 src
    WHERE src.MODELO = 'VENTAS'
    AND src.SISORIGEN_ID <> 'BW4';   

END;

ALTER TASK MIRRORING.TASK_FCT_FIN_ADH_VENTAS RESUME;