CREATE OR ALTER TABLE CON.DIM_MAT_GRUPOMATERIALES5(		
GRUPOMATERIALES5_ID	VARCHAR(10)	PRIMARY KEY,
GRUPOMATERIALES5_TEXT	VARCHAR(70)	,
SISORIGEN_ID	VARCHAR(4)	,
MANDANTE	VARCHAR(4)	,
FECHA_CARGA	TIMESTAMP_TZ	,
ZONA_HORARIA	VARCHAR(4)	
)		
;