CREATE OR REPLACE ROW ACCESS POLICY SEGURIDAD.RAP_DIM_CENTROCOSTO_ID
AS (    DIRECCION_ID VARCHAR(2),
        SUCURSAL_ID VARCHAR(2),
        GERENCIA_ID VARCHAR(2),
        ENCARGADO_CC_ID VARCHAR(12),
        ENCARGADO_GERENCIA_ID VARCHAR(12),
        ENCARGADO_DIRECCION_ID VARCHAR(12),
        ENCARGADO_DIRECAREA_ID VARCHAR(12)
) RETURNS BOOLEAN ->

CASE    WHEN    (   (SELECT SEGURIDAD.FN_RAP_DIM(DIRECCION_ID,'DIRECCION_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(SUCURSAL_ID,'SUCURSAL_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(GERENCIA_ID,'GERENCIA_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(ENCARGADO_CC_ID,'ENCARGADO_CC_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(ENCARGADO_GERENCIA_ID,'ENCARGADO_GERENCIA_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(ENCARGADO_DIRECCION_ID,'ENCARGADO_DIRECCION_ID')) = TRUE
                    AND (SELECT SEGURIDAD.FN_RAP_DIM(ENCARGADO_DIRECAREA_ID,'ENCARGADO_DIRECAREA_ID')) = TRUE
                ) = TRUE

        THEN TRUE
        ELSE FALSE

END;