SELECT         CASE MONTH(FECHA_LOGISTICA)
            WHEN 1 THEN 'ENE'
            WHEN 2 THEN 'FEB'
            WHEN 3 THEN 'MAR'
            WHEN 4 THEN 'ABR'
            WHEN 5 THEN 'MAY'
            WHEN 6 THEN 'JUN'
            WHEN 7 THEN 'JUL'
            WHEN 8 THEN 'AGO'
            WHEN 9 THEN 'SEP'
            WHEN 10 THEN 'OCT'
            WHEN 11 THEN 'NOV'
            WHEN 12 THEN 'DIC'
        END AS MES_TEXTO
FROM 
MIRRORING.FCT_ADH_APIC
LIMIT 10;

SELECT monthname(fecha_logistica, 'NLS_DATE_LANGUAGE=SPANISH' ) mes
FROM 
MIRRORING.FCT_ADH_APIC
WHERE
MODELO= 'ABASTECIMIENTOS'
LIMIT 100;


SELECT TO_CHAR(CURRENT_DATE(), 'NLS_DATE_LANGUAGE=SPANISH') AS nombre_mes;


SELECT TRY_CAST('2023-09-23', VARCHAR(3) ) AS nombre_mes;



SELECT DISTINCT MODELO FROM MIRRORING.FCT_COM_ADH_COMERCIAL ;