USE DATABASE LAMOSALAKE_DEV;
USE SCHEMA RAW;
/* create or replace table RAW.PARAMETROS_EXTRACCION (
    ORDEN INTEGER,
    EXTRACTOR VARCHAR(60),
    NEGOCIO VARCHAR(100),
    PARAMETRO VARCHAR(100),
    R_INICIO VARCHAR(50) ,
    R_FIN VARCHAR(50) 
);*/


/*TRUNCATE TABLE LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION;*/

DELETE FROM  LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION WHERE EXTRACTOR = 'ZBWSD_CAPTURA_DIARIA' ;

 
INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'VKORG' PARAMETRO, 'R311' R_INICIO , 'R401' R_FIN	UNION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'FECHA_DOCUMENTO' PARAMETRO, '30' R_INICIO , NULL R_FIN	UNION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'MSEHI' PARAMETRO, 'M2' R_INICIO , NULL R_FIN	UNION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'SPART' PARAMETRO, '00' R_INICIO , '10' R_FIN	UNION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'VTWEG' PARAMETRO, 'EX' R_INICIO , 'VM' R_FIN	UNION
SELECT 1 ORDEN,  'ZBWSD_CAPTURA_DIARIA' EXTRACTOR, 'REVMEXICO' NEGOCIO,'PREFIJO' PARAMETRO, 'SQ1_' R_INICIO , NULL R_FIN	
;
