-- Este archivo pertenece a DIM_CLI_RAMO

CREATE OR REPLACE TABLE PRE.PDIM_CLI_RAMO (
    RAMO_ID VARCHAR(10),
    RAMO_TEXT VARCHAR(30),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

