CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_SOCIEDADGLASOC(
    SOCIEDADGLASOC_ID VARCHAR(4) NOT NULL,
    PAIS_ID VARCHAR(3) NOT NULL,
    NEGOCIOGRUPO_ID VARCHAR(4) NOT NULL,
    SOCIEDADGLASOC_TEXT VARCHAR(25) NOT NULL,
    SOCIEDADGLASOC_ID_TEXT VARCHAR(40) NOT NULL,    
    PAIS_TEXT VARCHAR(25) NOT NULL,
    NEGOCIOGRUPO_TEXT VARCHAR(25) NOT NULL,
    SISORIGEN_ID VARCHAR(4) NOT NULL,
	MANDANTE VARCHAR(4) NOT NULL,
	FECHA_CARGA TIMESTAMP_TZ(9) NOT NULL,
	ZONA_HORARIA VARCHAR(10) NOT NULL,
    PRIMARY KEY (SOCIEDADGLASOC_ID)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_SOCIEDADGLASOC ON TABLE MIRRORING.DIM_FIN_SOCIEDADGLASOC;