CREATE OR REPLACE TABLE MIRRORING.DIM_DOC_CLASEDOCFI(
	CLASEDOCFI_ID VARCHAR(2),
	CLASEDOCFI_TEXT VARCHAR(20),
    CLASEDOCFI_ID_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_DOC_CLASEDOCFI
ON TABLE MIRRORING.DIM_DOC_CLASEDOCFI;