CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_CATEGORIAPRES (
	CATEGORIAPRES_ID VARCHAR(60),
	CATEGORIAPRES_TEXT VARCHAR(60),
    CATEGORIAPRES_ID_TEXT VARCHAR(130),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_CATEGORIAPRES
ON TABLE MIRRORING.DIM_FIN_CATEGORIAPRES;