CREATE OR ALTER TABLE RAW.SQ1_EXT_0CMMT_ITEM_PU_ATTR (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	FIKRS VARCHAR(4),
	DATEFROM DATE,
	DATETO DATE,
	FIPEX VARCHAR(24),
	POTYP VARCHAR(1),
	STR_ID VARCHAR(10),
	CISUB1 VARCHAR(10),
	CISUB2 VARCHAR(10),
	CISUB3 VARCHAR(10),
	CISUB4 VARCHAR(10),
	CISUB5 VARCHAR(10),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);