CREATE OR ALTER TABLE RAW.SQ1_EXT_0PU_MEASURE_ATTR (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	FMAREA VARCHAR(4),
	MEASURE VARCHAR(24),
	VALID_FROM DATE,
	VALID_TO DATE,
	FP_CATEGORY VARCHAR(3),
	FP_TYPE VARCHAR(4),
	OBJKEY VARCHAR(70),
	OBJTYPE VARCHAR(10),
	LOGSYS VARCHAR(10),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);