CREATE OR ALTER TABLE RAW.SQ1_EXT_0FUNDS_CTR_ATTR (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	FIKRS VARCHAR(4),
	FICTR VARCHAR(16),
	DATETO DATE,
	DATEFROM DATE,
	BOSSID VARCHAR(12),
	BOSSNAME VARCHAR(20),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);