CREATE OR REPLACE TABLE RAW.SQ1_EXT_0COSTELMNT_TEXT(
        ANIO VARCHAR(4),
        MES VARCHAR(2),
        KOKRS VARCHAR(4),
        KSTAR VARCHAR(10),
        TXTSH VARCHAR(40),
        TEXTO VARCHAR(132),
        SISORIGEN_ID VARCHAR(4),
        MANDANTE VARCHAR(4),
        FECHA_CARGA TIMESTAMP_TZ,
        ZONA_HORARIA VARCHAR(10)
);

SELECT * FROM RAW.SQ1_EXT_0COSTELMNT_TEXT;