CREATE OR ALTER TABLE RAW.SQ1_EXT_0PU_MEASURE_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	LANGUAGE VARCHAR(1),
	FMAREA VARCHAR(4),
	MEASURE VARCHAR(24),
	SHORT_DESC VARCHAR(20),
	DESCRIPTION VARCHAR(50),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);