CREATE OR REPLACE TABLE RAW.SQ1_EXT_0CRED_GROUP_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	SPRAS VARCHAR(1),
	GRUPP VARCHAR(4),
	KKBER VARCHAR(4),
	GTEXT VARCHAR(30),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);