CREATE OR ALTER TABLE RAW.SQ1_EXT_0GL_ACCOUNT_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	LANGU VARCHAR(1),
	KTOPL VARCHAR(4),
	SAKNR VARCHAR(10),
	TXTSH VARCHAR(20),
	TXTLG VARCHAR(50),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);