CREATE OR REPLACE TABLE RAW.SQ1_EXT_0FM_ACTDETL_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	LANGU VARCHAR(1),
	ACTDETL VARCHAR(3),
	TXTSH VARCHAR(20),
	TXTMD VARCHAR(40),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);