CREATE OR REPLACE TABLE RAW.SQ1_EXT_0AC_DOC_TYP_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	SPRAS VARCHAR(1),
	BLART VARCHAR(2),
	LTEXT VARCHAR(20),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);