CREATE OR ALTER TABLE RAW.SQ1_EXT_0CMMT_ITEM_PU_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	LANGU VARCHAR(1),
	FIKRS VARCHAR(4),
	FIPEX VARCHAR(24),
	DATETO DATE,
	DATEFROM DATE,
	TXTSH VARCHAR(20),
	TXTMD VARCHAR(40),
	TXTLG VARCHAR(60),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);