CREATE OR ALTER TABLE RAW.SQ1_EXT_0FUNDS_CTR_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	DATEFROM DATE,
	DATETO DATE,
	FIKRS VARCHAR(4),
	FICTR VARCHAR(16),
	LANGU VARCHAR(1),
	TXTMD VARCHAR(40),
	TXTSH VARCHAR(20),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);