USE DATABASE LAMOSALAKE_DEV;
USE SCHEMA RAW;
create or replace table RAW.PARAMETROS_EXTRACCION (
    EXTRACTOR VARCHAR(60),
    NOMBRE_TABLA VARCHAR(100),
    PARAMETROS VARCHAR(100),
    VALOR_INFERIOR VARCHAR(50),
    VALOR_SUPERIOR VARCHAR(50)
);

INSERT INTO RAW.PARAMETROS_EXTRACCION
VALUES(
    'ZBWSD_CAPTURA_DIARIA',
    'SQ1_ZBWSD_CAPTURA_DIARIA',    
    'FECHA_DOCUMENTO',
    '20250201',
    '20250401'    
    );