CREATE OR ALTER TABLE RAW.PARAMETROS_EXTRACCION (
    ORDEN INTEGER,
    EXTRACTOR VARCHAR(60),
    NEGOCIO VARCHAR(100),
    PARAMETRO VARCHAR(100),
    R_INICIO VARCHAR(50) ,
    R_FIN VARCHAR(50) 
);
