create or replace TABLE CON.FCT_LOG_ADH_ABASTECIMIENTOS_PCP (
    ANIO VARCHAR(4),
    MES VARCHAR(2),
    ANIOMES VARCHAR(10),
    FECHA_ABASTECIMIENTOS_PCP DATE,
    SOCIEDAD_ID VARCHAR(4),
    CENTRO_ID VARCHAR(4),
    MATERIAL_ID VARCHAR(30),
    MATERIALCENTRO_ID VARCHAR(34),
    IND_PRECIOCOMPRA_PCP_LOC NUMBER(15,2),
    MON_LOC VARCHAR(4),
    SISORIGEN_ID VARCHAR(4) NOT NULL,
	MANDANTE VARCHAR(4) NOT NULL,
	FECHA_CARGA TIMESTAMP_TZ(9) NOT NULL,
	ZONA_HORARIA VARCHAR(10) NOT NULL
 
);