CREATE OR REPLACE TABLE CON.FCT_LOG_ADH_ABASTECIMIENTOS (
  CENTRO_ID VARCHAR(4),
  ALMACENCENTRO_ID VARCHAR(9),
  ORGCOMPRAS_ID VARCHAR(4),
  GRUPOCOMPRAS_ID VARCHAR(3),
  MATERIAL_ID VARCHAR(40),
  MATERIALCENTRO_ID VARCHAR(45),
  GRUPOARTICULOS_ID VARCHAR(9),
  PROVEEDOR_ID VARCHAR(10),

  DOCCOMPRAS_CLASE VARCHAR(4),
  DOCCOMPRAS_TIPO VARCHAR(1),
  DOCCOMPRAS VARCHAR(10),
  DOCCOMPRAS_POS VARCHAR(5),
  DOCCOMPRAS_REPARTO VARCHAR(4),
  FECHA_LIBERACION DATE,
  FECHA_DOCCOMPRAS DATE,
  FECHA_ENTREGAPLANIFICADA DATE,
  FECHA_ENTREGAOBJETIVO DATE,
  FECHA_CONTABILIZACION DATE,

  FECHA_ORDEN DATE,
  ANIOMES VARCHAR(7),

  CLAVEOPERACION VARCHAR(3),
  SOLPED VARCHAR(10),
  SOLPED_POS VARCHAR(5),

  IND_CANTIDAD_TOTAL NUMBER(20,3),
  UM_PEDIDO VARCHAR(3),

  IND_IMPTE_COMPRA_PED NUMBER(38,12),
  IND_IMPTE_FLETE_PED NUMBER(16,2),
  IND_IMPTE_COMPRA_SIN_FLETE_PED NUMBER(38,12),
  MON_PED VARCHAR(5),

  IND_IMPTE_COMPRA_LOC NUMBER(38,12),
  IND_IMPTE_FLETE_LOC NUMBER(16,2),
  IND_IMPTE_COMPRA_SIN_FLETE_LOC NUMBER(38,12),
  MON_LOC VARCHAR(5),

  IND_IMPTE_COMPRA_USD NUMBER(38,12),
  IND_IMPTE_FLETE_USD NUMBER(38,12),
  IND_IMPTE_COMPRA_SIN_FLETE_USD NUMBER(38,12),
  MON_USD VARCHAR(3),

  IND_IMPTE_COMPRA_EUR NUMBER(38,12),
  IND_IMPTE_FLETE_EUR NUMBER(38,12),
  IND_IMPTE_COMPRA_SIN_FLETE_EUR NUMBER(38,12),
  MON_EUR VARCHAR(3),

  TIPOCAMBIO_USD NUMBER(25,12),
  TIPOCAMBIO_EUR NUMBER(25,12),

  IND_CANT_DIAS_COLOCACION NUMBER(38,0),
  IND_CANT_POSICIONES_PEDIDO NUMBER(38,0),

  /*IND_CANT_EM_TOTAL_VENCIDAS NUMBER(31,3),
  IND_CANT_DIASPONDERADOS NUMBER(38,3),
  IND_CANT_DIASPODERADOS_ANT NUMBER(38,3),
  IND_CANT_POS_TOTAL NUMBER(18,0),
  IND_CANT_EM_PEDIDO_ENTIEMPO NUMBER(31,3),
  IND_CANT_EM_COMPLETAS_ENTIEMPO NUMBER(31,3),
  IND_CANT_POS_COMPLETAS_ENTIEMPO NUMBER(1,0),
  IND_CANT_POS_NOCOMPLETAS_ENTIEMPO NUMBER(1,0),*/

  CLAVEMP_LOC VARCHAR(18),
  CLAVEMP_USD VARCHAR(18),
  CLAVEMP_EUR VARCHAR(18),

  ESTADO VARCHAR(20),

  SISORIGEN_ID VARCHAR(3),
  MANDANTE VARCHAR(3),
  FECHA_CARGA DATE,
  ZONA_HORARIA VARCHAR(4)
);
