CREATE OR ALTER TABLE PRE.PDIM_FIN_DETALLECOMPREAL(
    DETALLECOMPREAL_ID VARCHAR(3),
	DETALLECOMPREAL_TEXT VARCHAR(20),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);