CREATE OR ALTER TABLE PRE.PDIM_FIN_CLASERIESGO(
    CLASERIESGO_ID VARCHAR(8),
	CLASERIESGO VARCHAR(3),
	CLASERIESGO_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);