/*INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(1,'ZBWPP_CALDISENO',	'GENERAL_MX',	'WERKS',	'R101',	'R120'),
(1,	'ZBWPP_CALDISENO',	'GENERAL_MX',	'BUDAT1',	'1', NULL),
(1,'ZBWPP_CALDISENO',	'GENERAL_MX',	'PREFIJO',	'SQ1_',	NULL),
(2,'ZBWPP_CALDISENO',	'GENERAL_MX',	'WERKS',	'R101',	'R120'),
(2,	'ZBWPP_CALDISENO',	'GENERAL_MX',	'BUDAT1',	'30', NULL)
(2,'ZBWPP_CALDISENO',	'GENERAL_MX',	'PREFIJO',	'SQ1_',	NULL)
*/

/* 
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(1,'ZBWPP_CALDISENO',	'REVMEXICO',	'WERKS',	'R101',	'R120'),
(1,	'ZBWPP_CALDISENO',	'REVMEXICO',	'BUDAT1',	'20250101', '20251231'),
(1,'ZBWPP_CALDISENO',	'REVMEXICO',	'CLASE_ORDEN',	'ZBWPP_CALDISENO_CLASEORD_MEX',	NULL),
(1,'ZBWPP_CALDISENO',	'REVMEXICO',	'MATNR',	'NULL,	NULL),
(1,'ZBWPP_CALDISENO',	'REVMEXICO',	'MTART',	'FERT',	NULL)
*/
/* 
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(99,'PRUEBA',	'GENERAL',	'PREFIJO',	'SQ1_',	'SQ1_'),
(99,'PRUEBA',	'GENERAL',	'MANDANTE',	'500',	'500'),
(99,'PRUEBA',	'GENERAL',	'SISTEMA_ORIGEN',	'SQ1',	'SQ1')
*/
/* 
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(99,'PRUEBA2',	'GENERAL',	'PREFIJO',	'SQ1_',	'SQ1_'),
(99,'PRUEBA2',	'GENERAL',	'MANDANTE',	'400',	'400'),
(99,'PRUEBA2',	'GENERAL',	'SISTEMA_ORIGEN',	'SQ1',	'SQ1')
*/
/* 
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(1,'ZBWPP_CALDISENO',	'REVMEXICO',	'MTART',	'FERT',	NULL)
*/
/* 
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(1,'2LIS_03_BF',	'ADHMEXICO',	'CLASEMOVIMIENTO1',	'261',	'262'),
(2,'2LIS_03_BF',	'ADHMEXICO',	'CLASEMOVIMIENTO2',	'131',	'132'),
(3,'2LIS_03_BF',	'ADHMEXICO',	'CLASEMOVIMIENTO3',	'311',	'312')
*/
INSERT INTO RAW.PARAMETROS_EXTRACCION 
VALUES
(99,'2LIS_03_BF', 'ADHMEXICO', 'BSTTYP',NULL,NULL),
(99,'2LIS_03_BF', 'ADHMEXICO', 'BUDAT',NULL,NULL),
(99,'2LIS_03_BF', 'ADHMEXICO', 'MATNR',NULL,NULL),
(99,'2LIS_03_BF', 'ADHMEXICO', 'MBLNR',NULL,NULL),
(99,'2LIS_03_BF', 'ADHMEXICO', 'WERKS',NULL,NULL)