INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION 
VALUES
(1,'ZBWPP_CALDISENO',	'GENERAL_MX',	'WERKS',	'R101',	'R120'),
(1,	'ZBWPP_CALDISENO',	'GENERAL_MX',	'BUDAT1',	'1', NULL),
(1,'ZBWPP_CALDISENO',	'GENERAL_MX',	'PREFIJO',	'SQ1_',	NULL),
(2,'ZBWPP_CALDISENO',	'GENERAL_MX',	'WERKS',	'R101',	'R120'),
(2,	'ZBWPP_CALDISENO',	'GENERAL_MX',	'BUDAT1',	'30', NULL)
(2,'ZBWPP_CALDISENO',	'GENERAL_MX',	'PREFIJO',	'SQ1_',	NULL)