--select * from RAW.SQ1_MOF_ZBWPP_CALDISENO
--select * from RAW.PARAMETROS_EXTRACCION

SELECT
        YEAR(E2LISBF.BUDAT) AS ANIO,
        MONTH(E2LISBF.BUDAT) AS MES,
        TO_CHAR(E2LISBF.BUDAT,'YYYYMM') AS ANIOMES, 
        E2LISBF.BUKRS AS SOCIEDAD_ID,
        E2LISBF.WERKS AS CENTRO_ID
FROM RAW.SQ1_EXT_2LIS_03_BF AS E2LISBF;

SELECT
    YEAR(TO_DATE(E2LISBF.BUDAT, 'YYYYMMDD')) AS ANIO,
    MONTH(TO_DATE(E2LISBF.BUDAT, 'YYYYMMDD')) AS MES,
    TO_CHAR(TO_DATE(E2LISBF.BUDAT, 'YYYYMMDD'), 'YYYYMM') AS ANIOMES, 
    E2LISBF.BUKRS AS SOCIEDAD_ID,
    E2LISBF.WERKS AS CENTRO_ID
FROM RAW.SQ1_EXT_2LIS_03_BF AS E2LISBF;
/* 
"CASE 
    WHEN 0STOR_LOC IN ('NC01', 'NC02', 'PA01') THEN
        CASE 
            WHEN 0DCINDIC = 'S' THEN 0ZPPPTUE * -1
            ELSE 0ZPPPTUE
        END
    ELSE
        CASE 
            WHEN 0DCINDIC = 'H' THEN 0ZPPPTUE * -1
            ELSE 0ZPPPTUE
        END
END AS 0ZPPPTUE"
--------------------------------------------------
"CASE 
    WHEN 0STOR_LOC IN ('NC01', 'NC02', 'PA01') AND 0DCINDIC = 'S' THEN 0QUANT_B* -1
    WHEN 0STOR_LOC NOT IN ('NC01', 'NC02', 'PA01') AND 0DCINDIC = 'H' THEN 0QUANT_B * -1
    ELSE 0QUANT_B
END AS 0QUANT_B"
*/
SELECT DISTINCT LGORT from RAW.SQ1_EXT_2LIS_03_BF;