CREATE OR REPLACE TABLE MIRRORING.FCT_ADH_APIC (
    APIC_ID                           VARCHAR,
    ANIO                              VARCHAR(4),
    MES                               NUMBER(6),
    ANIOMES                           VARCHAR(6),
    FECHA_LOGISTICA                   DATE,
    ALMACENCENTRO_ID                  VARCHAR(10),
    ALMACEN_ID                        VARCHAR(4),
    CENTRO_ID                         VARCHAR(4),
    SOCIEDAD_ID                       VARCHAR(4),
    GRUPOCOMPRAS_ID                   VARCHAR(3),
    ORGCOMPRAS_ID                     VARCHAR(4),
    PROVEEDOR_ID                      VARCHAR(10),
    MATERIALCENTRO_ID                 VARCHAR(40),
    MATERIAL_ID                       VARCHAR(18),
    CLASEMOVIMIENTO_ID                VARCHAR(3),
    CLAVEOPERACION                    VARCHAR(3),
    GRUPO_OPERACION                   VARCHAR(20),
    BOR_CLASEPEDIDO_ID                VARCHAR(4),
    VTA_CLASEFACTURA_ID               VARCHAR(4),
    VTA_TIPO_TRANSACCION              VARCHAR(30),
    BOR_IND_BO_TOTAL_TON              NUMBER(17,3),
    VTA_IND_VENTA_PCP_LOC             NUMBER,
    VTA_IND_VENTA_PCP_TON             NUMBER,
    VTA_IND_VENTA_REAL_LOC            NUMBER,
    VTA_IND_VENTA_REAL_TON            NUMBER,
    INV_IND_BLOQUEADO_TON             NUMBER(17,3),
    INV_IND_BLOQUEADO_UMB             NUMBER(17,3),
    INV_IND_CONTROL_CALIDAD_TON       NUMBER(17,3),
    INV_IND_CONTROL_CALIDAD_UMB       NUMBER(17,3),
    INV_IND_COSTO_INV_LOC             NUMBER(17,2),
    INV_IND_INVENTARIO_FISICO_TON     NUMBER(17,3),
    INV_IND_INVENTARIO_FISICO_UMB     NUMBER(17,3),
    INV_IND_LIBRE_UTILIZACION_TON     NUMBER(17,3),
    INV_IND_LIBRE_UTILIZACION_UMB     NUMBER(17,3),
    INV_IND_LIBRE_VENTA_TON           NUMBER(17,3),
    INV_IND_LIBRE_VENTA_UMB           NUMBER(17,3),
    INV_IND_STOCK_SEGURIDAD_TON       NUMBER(17,3),
    INV_IND_STOCK_SEGURIDAD_UMB       NUMBER(17,3),
    INV_IND_TRANSITO_TON              NUMBER(17,3),
    INV_IND_TRANSITO_UMB              NUMBER(17,3),
    ABS_IND_CANTIDAD_TOTAL            NUMBER(20,3),
    ABS_IND_CANT_DIAS_COLOCACION      NUMBER(38,0),
    ABS_IND_CANT_POSICIONES_PEDIDO    NUMBER(38,0),
    ABS_IND_IMPTE_COMPRA_LOC          NUMBER(38,12),
    ABS_IND_IMPTE_COMPRA_PED          NUMBER(38,12),
    ABS_IND_IMPTE_COMPRA_USD          NUMBER(38,12),
    ABS_IND_IMPTE_COMPRA_SIN_FLETE_LOC NUMBER(38,12),
    ABS_IND_IMPTE_COMPRA_SIN_FLETE_PED NUMBER(38,12),
    ABS_IND_IMPTE_COMPRA_SIN_FLETE_USD NUMBER(38,12),
    ABS_IND_IMPTE_FLETE_LOC           NUMBER(16,2),
    ABS_IND_IMPTE_FLETE_PED           NUMBER(16,2),
    ABS_IND_IMPTE_FLETE_USD           NUMBER(38,12),
    PRD_IND_IMPTE_ML                  NUMBER(17,3),
    PRD_IND_IMPTE_COMPRA_ML           NUMBER(17,3),
    PRD_IND_IMPTE_USD                 NUMBER(17,3),
    PRD_IND_IMPTE_COMPRA_USD          NUMBER(17,3),
    PRD_IND_CANTIDAD_UMB              NUMBER(17,3),
    PRD_IND_CANTIDAD_UME              NUMBER(17,3),
    MON_LOC                           VARCHAR(5),
    MON_PED                           VARCHAR(5),
    MON_USD                           VARCHAR(5),
    UNI_PED                           VARCHAR(3),
    UNI_EST                           VARCHAR,
    UNI_UMB                           VARCHAR,
    FECHA_CARGA                       TIMESTAMP_TZ,
    MANDANTE                          VARCHAR(4),
    MODELO                            VARCHAR,
    SISORIGEN_ID                      VARCHAR(4),
    ZONA_HORARIA                      VARCHAR
);


CREATE OR REPLACE STREAM MIRRORING.STREAM_FCT_ADH_APIC ON TABLE MIRRORING.FCT_ADH_APIC;


describe table MIRRORING.FCT_ADH_APIC;


select distinct modelo from MIRRORING.FCT_ADH_APIC;
