insert into SEGURIDAD.SEG_USUARIO_ROLE 
	(USER_NM,
	ROLE_NM)
	values
	('FERNANDO_CUELLAR','SAP_ROLE');

DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE 
	WHERE USER_NM = 'AGUSTIN_GUTIERREZ';
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE 
	WHERE USER_NM = 'FERNANDO_CUELLAR'
	AND ROLE_NM = 'SAP_ROLE';


select * from SEGURIDAD.SEG_USUARIO_ROLE 
WHERE USER_NM = 'FERNANDO_CUELLAR';

insert into seguridad.seg_role_dimension
(ROLE_NM , DIM , VALOR )
values
('ROLE_DESTINATARIO','ASESORDEST_ID','0001302294') --luis
-- ('ROLE_DESTINATARIO','COORDINADORDEST_ID','0001303565')
;
SELECT * FROM seguridad.seg_role_dimension; --ROLE_DESTINATARIO
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION 
	WHERE ROLE_NM = 'ROLE_DESTINATARIO';

select * from seguridad.seg_role_dimension
WHERE ROLE_NM = 'ROLE_DESTINATARIO';

DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION 
	WHERE ROLE_NM = 'ROLE_DESTINATARIO'
	AND DIM = 'COORDINADORDEST_ID'
	AND VALOR = '0001303565';

DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION 
	WHERE ROLE_NM = 'ROLE_DESTINATARIO'
	AND DIM = 'ASESORDEST_ID'
	AND VALOR = '0001302294';
insert into seguridad.seg_usuario_dimension
(USER_NM , DIM , VALOR )
values
('FERNANDO_CUELLAR','COORDINADORDEST_ID','123');

DELETE FROM SEGURIDAD.SEG_USUARIO_DIMENSION 
	WHERE USER_NM = 'FERNANDO_CUELLAR'
	AND DIM = 'COORDINADORDEST_ID'
	AND VALOR = '123';
select distinct(grupoclientes2_id) from con.vw_dim_cli_solicitante; --CHECAR EL EXTRACTO UN GRUPO VACIO

SELECT * from con.VW_DIM_CLI_DESTINATARIO;
SELECT * FROM SEGURIDAD.VW_CON_SEG_USUARIO_ROLE_DIMENSION;


SELECT * FROM CON.VW_DIM_CLI_DESTINATARIO
WHERE ASESORDEST_ID = '0001302294'
AND COORDINADORDEST_ID = '0001303565';




insert into seguridad.seg_role_dimension
(ROLE_NM , DIM , VALOR )
values
('BACKORDER_ROLE','ORGVENTAS_ID','ALL'),
('BACKORDER_ROLE','CANALDISTRIB_ID','ALL'),
('BACKORDER_ROLE','CENTRO_ID','ALL'),
('BACKORDER_ROLE','OFICINAVENTAS_ID','ALL'),
('BACKORDER_ROLE','GRUPOVENDEDORES_ID','ALL'),
('BACKORDER_ROLE','ASESORPEDIDO_ID','ALL'),
('BACKORDER_ROLE','SOLICITANTE_ID','ALL'),
('BACKORDER_ROLE','DESTINATARIO_ID','ALL'),
('BACKORDER_ROLE','UEN_ADHESIVOS_ID','ALL')
;

SELECT * 
FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = CURRENT_USER;

SELECT * 
FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM IN (
  SELECT ROLE_NM 
  FROM SEGURIDAD.SEG_USUARIO_ROLE 
  WHERE USER_NM = CURRENT_USER
)
AND DIM IN ('COORDINADORDEST_ID', 'ASESORDEST_ID');

SELECT RD.ROLE_NM, RD.DIM, RD.VALOR
FROM SEGURIDAD.SEG_ROLE_DIMENSION RD
JOIN SEGURIDAD.SEG_USUARIO_ROLE UR ON RD.ROLE_NM = UR.ROLE_NM
WHERE UR.USER_NM = CURRENT_USER
AND RD.DIM IN ('COORDINADORDEST_ID', 'ASESORDEST_ID');

DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION 
	WHERE ROLE_NM = 'ROLE_DESTINATARIO';


SELECT
  *,
  COORDINADORDEST_ID,
  ASESORDEST_ID,
  (
    SELECT COUNT(DISTINCT VALOR)
    FROM SEGURIDAD.SEG_ROLE_DIMENSION
    WHERE ROLE_NM IN (
        SELECT ROLE_NM 
        FROM SEGURIDAD.SEG_USUARIO_ROLE 
        WHERE USER_NM = CURRENT_USER
    )
    AND DIM IN ('COORDINADORDEST_ID', 'ASESORDEST_ID')
    AND VALOR IN (COORDINADORDEST_ID, ASESORDEST_ID)
  ) AS CONTADOR_ROL
FROM CON.VW_DIM_CLI_DESTINATARIO
WHERE CURRENT_USER = 'FERNANDO_CUELLAR';
