INSERT INTO "LAMOSALAKE_DEV"."RAW"."PARAMETROS_EXTRACCION" (EXTRACTOR, PARAMETRO, VALOR_INFERIOR, VALOR_SUPERIOR)
VALUES 
    ('ZBWSD_PEDIDOS_BACKORDER', 'PDTES', 'X', ''),
    ('ZBWSD_PEDIDOS_BACKORDER', 'CANAL DISTRIBUCION', 'EX', 'NA');


SELECT * FROM "LAMOSALAKE_DEV"."RAW"."PARAMETROS_EXTRACCION";

---------------------------- EN BASE A LA IMAGEN DE DAMIEL DE CADENA COMERCIAL

INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo 1: REV-MEXICO-R101
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'PDTES', 'X', NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'SPART', '00', '10'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VKORG', 'R101', 'R101'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VRKME', 'M2', NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VTWEG', 'EX', 'NA'),

    -- Grupo 2: REV-MEXICO-R311 -R401-EX
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-EX', 'PDTES', 'X', NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-EX', 'SPART', '00', '10'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-EX', 'VKORG', 'R311', 'R401'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-EX', 'VRKME', 'M2', NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-EX', 'VTWEG', 'EX', NULL),

    -- Grupo 3: REV-MEXICO-R311 -R401-NA
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-NA', 'PDTES', 'X', NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-NA', 'SPART', '00', '10'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-NA', 'VKORG', 'R311', 'R401'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-NA', 'VRKME', 'M2', NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311 -R401-NA', 'VTWEG', 'NA', NULL);

    INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo 1: REV-MEXICO-R101
    (99, 'ZBWMM_INVENTARIO', 'GENERAL', 'PREFIJO', 'SQ1_', NULL);   

-------------------------------------------------------------------------------------------------------------------------
--SCRIPT PARA CARGAR PARAMETROS A TODO REV, ADH Y JUNTOS
    INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo REVESTIMIENTOS TODOS
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV', 'PDTES', 'X', NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV', 'SPART', '00', '10'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV', 'VKORG', 'R101', 'R401'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV', 'VRKME', 'M2', NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV', 'VTWEG', 'EX', 'NA');

    INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo ADHESIVOS TODOS
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL ADH', 'PDTES', 'X', NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL ADH', 'SPART', '00', '10'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL ADH', 'VKORG', 'A101', 'A201'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL ADH', 'VRKME', 'ST', 'TON'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL ADH', 'VTWEG', 'EX', 'NA');

    INSERT INTO LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo GENERAL TODOS
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV/ADH', 'PDTES', 'X', NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV/ADH', 'SPART', '00', '10'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV/ADH', 'VKORG', 'A101', 'R401'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV/ADH', 'VRKME', 'M2', 'TON'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL REV/ADH', 'VTWEG', 'EX', 'NA');
