INSERT INTO "LAMOSALAKE_DEV"."RAW"."PARAMETROS_EXTRACCION" (EXTRACTOR, PARAMETRO, VALOR_INFERIOR, VALOR_SUPERIOR)
VALUES 
    ('ZBWSD_PEDIDOS_BACKORDER', 'PDTES', 'X', ''),
    ('ZBWSD_PEDIDOS_BACKORDER', 'CANAL DISTRIBUCION', 'EX', 'NA');


SELECT * FROM "LAMOSALAKE_DEV"."RAW"."PARAMETROS_EXTRACCION" WHERE EXTRACTOR = 'ZBWSD_PEDIDOS_BACKORDER';