-- PARAMETROS QUE SE VAN A USAR
-- PDTES         Check cantidad pendiente
-- SPART          Sector
-- VKORG       Organización de ventas
-- VRKME        Unidad de medida de venta
-- VTWEG       Canal de distribución

-- AUART         Clase de documento de ventas
-- ERDAT         Fecha de creación del registro
-- KUNNR       Solicitante
-- MATKL         Grupo de artículos
-- VBELN         Documento de ventas
-- VKBUR        Oficina de ventas

---------------------------- EN BASE A LA IMAGEN DE DAMIEL DE CADENA COMERCIAL

INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    -- Grupo 1: REV-MEXICO-R101
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'PDTES', 'X', NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'SPART', '00', '10'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VKORG', 'R101', 'R101'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VRKME', 'M2', NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VTWEG', 'EX', 'NA'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'AUART', NULL, NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'ERDAT', '20250101', '20250505'),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'KUNNR', NULL, NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'MATKL', NULL, NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VBELN', NULL, NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'VKBUR', NULL, NULL),
    (1, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R101', 'NEGOCIO', 'REV-MEXICO-R101', NULL),
    -- Grupo 2: REV-MEXICO-R311 -R401-EX
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'PDTES', 'X', NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'SPART', '00', '10'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'VKORG', 'R311', 'R401'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'VRKME', 'M2', NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'VTWEG', 'EX', 'IN'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'AUART', NULL, NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'ERDAT', '125', '1'),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'KUNNR', NULL, NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'MATKL', NULL, NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'VBELN', NULL, NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'VKBUR', NULL, NULL),
    (2, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-EX', 'NEGOCIO', 'REV-MEXICO-R311-R401-EX', NULL),
    -- Grupo 3: REV-MEXICO-R311 -R401-NA
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'PDTES', 'X', NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'SPART', '00', '10'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'VKORG', 'R311', 'R401'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'VRKME', 'M2', NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'VTWEG', 'NA', 'VM'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'AUART', NULL, NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'ERDAT', '125', '1'),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'KUNNR', NULL, NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'MATKL', NULL, NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'VBELN', NULL, NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'VKBUR', NULL, NULL),
    (3, 'ZBWSD_PEDIDOS_BACKORDER', 'REV-MEXICO-R311-R401-NA', 'NEGOCIO', 'REV-MEXICO-R311-R401-NA', NULL),
    -- Grupo 4: ADH TO
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'PDTES', 'X', NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'SPART', '00', '80'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'VKORG', 'A000', 'A201'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'VRKME', 'TO', NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'VTWEG', 'EX', 'NA'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'AUART', NULL, NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'ERDAT', '20250101', '20250630'),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'KUNNR', NULL, NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'MATKL', NULL, NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'VBELN', NULL, NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'VKBUR', NULL, NULL),
    (4, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-TO', 'NEGOCIO', 'ADH-TO', NULL),
    -- Grupo 5: ADH ST
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'PDTES', 'X', NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'SPART', '00', '10'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'VKORG', 'A000', 'A201'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'VRKME', 'ST', NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'VTWEG', 'EX', 'NA'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'AUART', NULL, NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'ERDAT', '20250101', '20250630'),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'KUNNR', NULL, NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'MATKL', NULL, NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'VBELN', NULL, NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'VKBUR', NULL, NULL),
    (5, 'ZBWSD_PEDIDOS_BACKORDER', 'ADH-A000-A201-ST', 'NEGOCIO', 'ADH-ST', NULL),
    ---
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'PDTES', 'X', NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'SPART', '00', '80'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'VKORG', 'A101', 'A104'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'VRKME', 'TO', NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'VTWEG', 'EX', 'NA'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'AUART', NULL, NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'ERDAT', '20250101', '20250721'),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'KUNNR', NULL, NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'MATKL', NULL, NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'VBELN', NULL, NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'VKBUR', NULL, NULL),
    (6, 'ZBWSD_PEDIDOS_BACKORDER', 'PRUEBAINTEGRAL', 'NEGOCIO', 'PRUEBA', NULL),
    -- Adicionales
    (99, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL', 'PREFIJO', 'SQ1_', NULL),
    (99, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL', 'MANDANTE', '500', NULL),
    (99, 'ZBWSD_PEDIDOS_BACKORDER', 'GENERAL', 'SISTEMA_ORIGEN', 'SQ1', NULL);

UPDATE raw.parametros_extraccion
SET R_FIN = R_INICIO
WHERE R_FIN IS NULL
  AND extractor = 'ZBWSD_PEDIDOS_BACKORDER';

DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWSD_PEDIDOS_BACKORDER';


-- select DISTINCT EXTRACTOR, negocio from raw.parametros_extraccion
-- where extractor = 'ZBWSD_PEDIDOS_BACKORDER';


-- select * from raw.sq1_mof_zbwsd_pedidos_backorder;
-- SELECT COUNT(*) FROM PRE.PFCT_COM_BACKORDER;


-- SELECT * FROM RAW.PARAMETROS_EXTRACCION
-- where extractor = 'EXTRACTOR_TX'
-- AND PARAMETRO = 'PREFIJO';


-- INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
-- VALUES
-- (99, 'EXTRACTOR_TX', 'GENERAL', 'PREFIJO', 'SQ1_', NULL),
--     (99, 'EXTRACTOR_TX', 'GENERAL', 'MANDANTE', '500', NULL),
--     (99, 'EXTRACTOR_TX', 'GENERAL', 'SISTEMA_ORIGEN', 'SQ1', NULL);


SELECT * FROM LOGS.HISTORIAL_EJECUCIONES
ORDER BY FECHA_HORA_INICIO DESC limit 200;


SELECT MAX(ANIOMES) FROM CON.FCT_COM_ADH_VENTAS_ACT
WHERE ANIO = '2025';

SELECT * FROM MIRRORING.FCT_COM_ADH_COMERCIAL
WHERE MODELO = 'VENTAS'
AND ANIO = '2025'
AND SISORIGEN_ID = 'SQ1'
;
select * from mirroring.TR_FCT_COM_ADH_VENTAS_ACT;
