INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES
    (1, 'ZBWFI_REP_ANTSALDET', 'REV_MEX', 'BUKRS', 'R101', NULL),
    (1, 'ZBWFI_REP_ANTSALDET', 'REV_MEX', 'BUDAT', 'FechaHoy', NULL),
    (1, 'ZBWFI_REP_ANTSALDET', 'REV_MEX', 'KURST', 'Z', NULL),
    (1, 'ZBWFI_REP_ANTSALDET', 'REV_MEX', 'WAERK', 'MXN', NULL),

    (2, 'ZBWFI_REP_ANTSALDET', 'REV_USA', 'BUKRS', 'R401', NULL),
    (2, 'ZBWFI_REP_ANTSALDET', 'REV_USA', 'BUDAT', 'FechaHoy', NULL),
    (2, 'ZBWFI_REP_ANTSALDET', 'REV_USA', 'KURST', 'Z', NULL),
    (2, 'ZBWFI_REP_ANTSALDET', 'REV_USA', 'WAERK', 'USD', NULL),

    (3, 'ZBWFI_REP_ANTSALDET', 'REV_ARGENTINA', 'BUKRS', 'R201', NULL),
    (3, 'ZBWFI_REP_ANTSALDET', 'REV_ARGENTINA', 'BUDAT', 'FechaHoy', NULL),
    (3, 'ZBWFI_REP_ANTSALDET', 'REV_ARGENTINA', 'KURST', 'Z', NULL),
    (3, 'ZBWFI_REP_ANTSALDET', 'REV_ARGENTINA', 'WAERK', 'ARS', NULL),

    (4, 'ZBWFI_REP_ANTSALDET', 'REV_PERU', 'BUKRS', 'R203', NULL),
    (4, 'ZBWFI_REP_ANTSALDET', 'REV_PERU', 'BUDAT', 'FechaHoy', NULL),
    (4, 'ZBWFI_REP_ANTSALDET', 'REV_PERU', 'KURST', 'Z', NULL),
    (4, 'ZBWFI_REP_ANTSALDET', 'REV_PERU', 'WAERK', 'PEN', NULL),

    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_202', 'BUKRS', 'R202', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_202', 'BUDAT', 'FechaHoy', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_202', 'KURST', 'Z', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_202', 'WAERK', 'COP', NULL),

    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_204', 'BUKRS', 'R204', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_204', 'BUDAT', 'FechaHoy', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_204', 'KURST', 'Z', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_204', 'WAERK', 'COP', NULL),

    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_404', 'BUKRS', 'R404', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_404', 'BUDAT', 'FechaHoy', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_404', 'KURST', 'Z', NULL),
    (5, 'ZBWFI_REP_ANTSALDET', 'REV_COLOMBIA_404', 'WAERK', 'COP', NULL),

    (6, 'ZBWFI_REP_ANTSALDET', 'REV_CHILE', 'BUKRS', 'R403', NULL),
    (6, 'ZBWFI_REP_ANTSALDET', 'REV_CHILE', 'BUDAT', 'FechaHoy', NULL),
    (6, 'ZBWFI_REP_ANTSALDET', 'REV_CHILE', 'KURST', 'Z', NULL),
    (6, 'ZBWFI_REP_ANTSALDET', 'REV_CHILE', 'WAERK', 'CLP', NULL),

    (7, 'ZBWFI_REP_ANTSALDET', 'ADH_MEX', 'BUKRS', 'A101', 'A103'),
    (7, 'ZBWFI_REP_ANTSALDET', 'ADH_MEX', 'BUDAT', 'FechaHoy', NULL),
    (7, 'ZBWFI_REP_ANTSALDET', 'ADH_MEX', 'KURST', 'Z', NULL),
    (7, 'ZBWFI_REP_ANTSALDET', 'ADH_MEX', 'WAERK', 'MXN', NULL),

    (8, 'ZBWFI_REP_ANTSALDET', 'ADH_GUATEMALA', 'BUKRS', 'A201', NULL),
    (8, 'ZBWFI_REP_ANTSALDET', 'ADH_GUATEMALA', 'BUDAT', 'FechaHoy', NULL),
    (8, 'ZBWFI_REP_ANTSALDET', 'ADH_GUATEMALA', 'KURST', 'Z', NULL),
    (8, 'ZBWFI_REP_ANTSALDET', 'ADH_GUATEMALA', 'WAERK', 'GTQ', NULL),

    (9, 'ZBWFI_REP_ANTSALDET', 'ADH_CHILE', 'BUKRS', 'A202', NULL),
    (9, 'ZBWFI_REP_ANTSALDET', 'ADH_CHILE', 'BUDAT', 'FechaHoy', NULL),
    (9, 'ZBWFI_REP_ANTSALDET', 'ADH_CHILE', 'KURST', 'Z', NULL),
    (9, 'ZBWFI_REP_ANTSALDET', 'ADH_CHILE', 'WAERK', 'CLP', NULL);

UPDATE raw.parametros_extraccion
SET R_FIN = R_INICIO
WHERE R_FIN IS NULL
  AND extractor = 'ZBWFI_REP_ANTSALDET';

  DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWFI_REP_ANTSALDET';