DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWSD_CUADERNO_FINANCIERO'
  AND NEGOCIO = 'ADH_MEXICO';

SELECT * FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWSD_CUADERNO_FINANCIERO'
AND NEGOCIO = 'ADH_MEXICO';

-- NO. DE CASO: 1
INSERT INTO RAW.PARAMETROS_EXTRACCION (
    ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN
)
VALUES
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'MSEHI', 'TO', NULL),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'SPART', '00', '80'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VKORG', 'A101', 'A104'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'WAERK', 'MXN', NULL),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'FKDAT', '20250101', '20250630'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VTWEG', 'EX', 'NA');

-- NO. DE CASO: 2
INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN) VALUES
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'FKDAT', '20250101', '20250731'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'MSEHI', 'TO', NULL),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'SPART', '00', '80'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VKORG', 'A101', 'A104'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VTWEG', 'EX', 'NA'),
(1, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'WAERK', 'MXN', NULL);

-- NO. DE CASO: 3
INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN) VALUES
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'FKDAT', '20250101', '20250531'),
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'MSEHI', 'TO', NULL),
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'SPART', '00', '80'),
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VKORG', 'A201', NULL),
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VTWEG', 'EX', 'NA'),
(2, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'WAERK', 'GTQ', NULL);

--NO. DE CASO: 4
INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN) VALUES
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'FKDAT', '20250101', '20250731'),
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'MSEHI', 'TO', NULL),
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'SPART', '00', '80'),
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VKORG', 'A201', NULL),
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'VTWEG', 'EX', 'NA'),
(3, 'ZBWSD_CUADERNO_FINANCIERO', 'ADH_MEXICO', 'WAERK', 'GTQ', NULL);

-------------------


--NO. DE CASO: 13 PEDIDOS
INSERT INTO RAW.PARAMETROS_EXTRACCION (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN) VALUES
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'VKORG', 'A101', 'A104'),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'SPART', '00', '80'),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'VTWEG', 'EX', 'NA'),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'FECHA_DOCUMENTO', '20250501', '20250731'),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'MSEHI', 'TO', 'TO'),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'KUNAG', NULL, NULL),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'TIPO_DOCUMENTO', NULL, NULL),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'VBELN', NULL, NULL),
(2, 'ZBWSD_CAPTURA_DIARIA', 'ADHMEXICO', 'VKBUR', NULL, NULL);


DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWSD_CAPTURA_DIARIA'
  AND NEGOCIO = 'ADHMEXICO';