-- SELECT 
--     'PRE' AS CAPA,
--     SUM(IND_BO_TOTAL_EST) AS IND_BO_TOTAL,
--     SUM(IND_BO_ENTREGA_EST) AS IND_BO_ENTREGA,
--     SUM(IND_BO_CONFIRMADO_EST) AS IND_BO_CONFIRMADO,
--     SUM(IND_BO_NO_CONFIRMADO_EST) AS IND_BO_NO_CONFIRMADO,
--     SUM(IND_BO_MONEDA_DOCUMENTO) AS IMPORTE_TOTAL
-- FROM PRE.PFCT_COM_BACKORDER;

-- SELECT 
--     'CON REVS' AS CAPA,
--     SUM(IND_BO_TOTAL_M2) AS IND_BO_TOTAL,
--     SUM(IND_BO_ENTREGA_M2) AS IND_BO_ENTREGA,
--     SUM(IND_BO_CONFIRMADO_M2) AS IND_BO_CONFIRMADO,
--     SUM(IND_BO_NO_CONFIRMADO_M2) AS IND_BO_NO_CONFIRMADO,
--     SUM(IND_BO_IMPORTE_DOC) AS IMPORTE_TOTAL
-- FROM CON.FCT_COM_REV_BACKORDER_ACT;

-- SELECT 
--     'CON_ADHS' AS MODELO,
--     SUM(IND_BO_TOTAL_TON) AS IND_BO_TOTAL,
--     SUM(IND_BO_ENTREGA_TON) AS IND_BO_ENTREGA,
--     SUM(IND_BO_CONFIRMADO_TON) AS IND_BO_CONFIRMADO,
--     SUM(IND_BO_NO_CONFIRMADO_TON) AS IND_BO_NO_CONFIRMADO,
--     SUM(IND_BO_IMPORTE_DOC) AS IMPORTE_TOTAL
-- FROM CON.FCT_COM_ADH_BACKORDER_ACT;

SELECT 
    'PRE' AS MODELO,
    ORGVENTAS_ID,
    SUM(IND_BO_TOTAL_EST) AS IND_BO_TOTAL,
    SUM(IND_BO_ENTREGA_EST) AS IND_BO_ENTREGA,
    SUM(IND_BO_CONFIRMADO_EST) AS IND_BO_CONFIRMADO,
    SUM(IND_BO_NO_CONFIRMADO_EST) AS IND_BO_NO_CONFIRMADO,
    SUM(IND_BO_MONEDA_DOCUMENTO) AS IMPORTE_TOTAL
FROM PRE.PFCT_COM_BACKORDER
GROUP BY ORGVENTAS_ID

UNION ALL

SELECT 
    'CON_REVS' AS MODELO,
    ORGVENTAS_ID,
    SUM(IND_BO_TOTAL_M2),
    SUM(IND_BO_ENTREGA_M2),
    SUM(IND_BO_CONFIRMADO_M2),
    SUM(IND_BO_NO_CONFIRMADO_M2),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_REV_BACKORDER_ACT
GROUP BY ORGVENTAS_ID

UNION ALL

SELECT 
    'CON_ADHS' AS MODELO,
    ORGVENTAS_ID,
    SUM(IND_BO_TOTAL_TON),
    SUM(IND_BO_ENTREGA_TON),
    SUM(IND_BO_CONFIRMADO_TON),
    SUM(IND_BO_NO_CONFIRMADO_TON),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_ADH_BACKORDER_ACT
GROUP BY ORGVENTAS_ID;


select * from con.fct_com_rev_backorder_act;
select * from raw.sq1_mof_zbwsd_pedidos_backorder;

TRUNCATE TABLE RAW.SQ1_MOF_ZBWSD_PEDIDOS_BACKORDER;
TRUNCATE TABLE PRE.PFCT_COM_BACKORDER;
TRUNCATE TABLE CON.FCT_COM_REV_BACKORDER_ACT;
TRUNCATE TABLE CON.FCT_COM_ADH_BACKORDER_ACT;

SELECT * FROM LOGS.HISTORIAL_EJECUCIONES
ORDER BY FECHA_HORA_INICIO DESC;


SELECT 
    'CON_REVS' AS MODELO,
    ORGVENTAS_ID,
    CANALDISTRIB_ID,
    MON_DOC,
    SUM(IND_BO_TOTAL_M2),
    SUM(IND_BO_ENTREGA_M2),
    SUM(IND_BO_CONFIRMADO_M2),
    SUM(IND_BO_NO_CONFIRMADO_M2),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_REV_BACKORDER_ACT
GROUP BY ORGVENTAS_ID, CANALDISTRIB_ID, mon_doc;

SELECT 
    'CON_REVS' AS MODELO,
    ORGVENTAS_ID AS "Organización ventas",
    CANALDISTRIB_ID AS "Canal distribución",
    MON_DOC AS "Moneda",
    SUM(IND_BO_IMPORTE_DOC) AS "Importe total",
FROM CON.FCT_COM_REV_BACKORDER_ACT
GROUP BY ORGVENTAS_ID, CANALDISTRIB_ID, mon_doc
ORDER BY ORGVENTAS_ID, CANALDISTRIB_ID, mon_doc;


SELECT 
    'CON_ADHS' AS MODELO,
    ORGVENTAS_ID,
    SUM(IND_BO_TOTAL_TON),
    SUM(IND_BO_ENTREGA_TON),
    SUM(IND_BO_CONFIRMADO_TON),
    SUM(IND_BO_NO_CONFIRMADO_TON),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_ADH_BACKORDER_ACT
GROUP BY ORGVENTAS_ID;

SELECT 
    'CON_ADHS' AS MODELO,
    ORGVENTAS_ID,
    mon_doc,
    SUM(IND_BO_TOTAL_TON),
    SUM(IND_BO_ENTREGA_TON),
    SUM(IND_BO_CONFIRMADO_TON),
    SUM(IND_BO_NO_CONFIRMADO_TON),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_ADH_BACKORDER_ACT
WHERE UNI_EST = 'TO'
GROUP BY ORGVENTAS_ID,mon_doc
ORDER BY ORGVENTAS_ID, mon_doc;


SELECT 
    'CON_ADHS' AS MODELO,
    ORGVENTAS_ID,
    mon_doc,
    FECHA_BACKORDER,
    SUM(IND_BO_TOTAL_TON),
    SUM(IND_BO_ENTREGA_TON),
    SUM(IND_BO_CONFIRMADO_TON),
    SUM(IND_BO_NO_CONFIRMADO_TON),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.VW_FCT_COM_ADH_BACKORDER
WHERE UNI_EST = 'TO'
GROUP BY ORGVENTAS_ID,mon_doc, FECHA_BACKORDER
ORDER BY ORGVENTAS_ID, mon_doc, FECHA_BACKORDER;

--------------------------------

SELECT 
    'CON_ADHS' AS MODELO,
    ORGVENTAS_ID,
    mon_doc,
    FECHA_BACKORDER,
    SUM(IND_BO_TOTAL_TON),
    SUM(IND_BO_ENTREGA_TON),
    SUM(IND_BO_CONFIRMADO_TON),
    SUM(IND_BO_NO_CONFIRMADO_TON),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_ADH_BACKORDER_FOTO
WHERE UNI_EST = 'TO'
GROUP BY ORGVENTAS_ID,mon_doc, FECHA_BACKORDER
ORDER BY ORGVENTAS_ID, mon_doc, FECHA_BACKORDER;

SELECT DISTINCT(FECHA_BACKORDER) FROM CON.VW_FCT_COM_REV_BACKORDER;
SELECT * FROM CON.VW_FCT_COM_REV_BACKORDER;

SELECT 
    'CON_REVS' AS MODELO,
    ORGVENTAS_ID,
    CANALDISTRIB_ID,
    MON_DOC,
    FECHA_BACKORDER,
    SUM(IND_BO_TOTAL_M2),
    SUM(IND_BO_ENTREGA_M2),
    SUM(IND_BO_CONFIRMADO_M2),
    SUM(IND_BO_NO_CONFIRMADO_M2),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.VW_FCT_COM_REV_BACKORDER
GROUP BY ORGVENTAS_ID, CANALDISTRIB_ID, mon_doc,FECHA_BACKORDER;

SELECT 
    'CON_REVS' AS MODELO,
    ORGVENTAS_ID,
    CANALDISTRIB_ID,
    MON_DOC,
    FECHA_BACKORDER,
    SUM(IND_BO_TOTAL_M2),
    SUM(IND_BO_ENTREGA_M2),
    SUM(IND_BO_CONFIRMADO_M2),
    SUM(IND_BO_NO_CONFIRMADO_M2),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.FCT_COM_REV_BACKORDER_FOTO
GROUP BY ORGVENTAS_ID, CANALDISTRIB_ID, mon_doc,FECHA_BACKORDER;

SELECT 
    'CON_REVS' AS MODELO,
    SUM(IND_BO_TOTAL_M2),
    SUM(IND_BO_ENTREGA_M2),
    SUM(IND_BO_CONFIRMADO_M2),
    SUM(IND_BO_NO_CONFIRMADO_M2),
    SUM(IND_BO_IMPORTE_DOC)
FROM CON.VW_FCT_COM_REV_BACKORDER;

SELECT DISTINCT(ORGVENTAS_ID) FROM CON.VW_FCT_COM_REV_BACKORDER;


