SELECT * FROM RAW.SQ1_EXT_0CUSTOMER_ATTR LIMIT 10; --check
SELECT * FROM RAW.SQ1_EXT_0CUSTOMER_TEXT LIMIT 10; --check
SELECT * FROM RAW.SQ1_EXT_ZSD_GPO_CTES_TEXT LIMIT 10; --check
SELECT * FROM RAW.SQ1_EXT_0CUST_CLASS_TEXT LIMIT 10; --check
SELECT * FROM RAW.SQ1_EXT_0ACCNT_ASGN_TEXT LIMIT 10; --CHECK
SELECT * FROM RAW.SQ1_EXT_0CUST_GROUP_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0CUST_GRP1_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0CUST_GRP2_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0CUST_GRP3_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0CUST_GRP4_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0CUST_GRP5_TEXT LIMIT 10;
SELECT * FROM RAW.SQ1_EXT_0INDUSTRY_TEXT LIMIT 10;
