CURRENT_TIMESTAMP() AS FECHA_CARGA,
TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA

;

CALL PRE.SP_PRE_PDIM_CLI_GRUPOCLIENTES1();
CALL CON.SP_CON_DIM_CLI_GRUPOCLIENTES1();
SELECT * FROM CON.DIM_CLI_GRUPOCLIENTES1;
---
CALL PRE.SP_PRE_PDIM_CLI_GRUPOCLIENTES2();
CALL CON.SP_CON_DIM_CLI_GRUPOCLIENTES2();
SELECT * FROM CON.DIM_CLI_GRUPOCLIENTES2;

CALL PRE.SP_PRE_PDIM_CLI_GRUPOCLIENTES3();
CALL CON.SP_CON_DIM_CLI_GRUPOCLIENTES3();
SELECT * FROM CON.DIM_CLI_GRUPOCLIENTES3;

CALL PRE.SP_PRE_PDIM_CLI_GRUPOCLIENTES4();
CALL CON.SP_CON_DIM_CLI_GRUPOCLIENTES4();
SELECT * FROM CON.DIM_CLI_GRUPOCLIENTES4;

CALL PRE.SP_PRE_PDIM_CLI_GRUPOCLIENTES5();
CALL CON.SP_CON_DIM_CLI_GRUPOCLIENTES5();
SELECT * FROM CON.DIM_CLI_GRUPOCLIENTES5;

CALL PRE.SP_PRE_PDIM_CLI_RAMO();
CALL CON.SP_CON_DIM_CLI_RAMO();
SELECT * FROM CON.DIM_CLI_RAMO;

CALL PRE.SP_PRE_PDIM_CLI_CLIENTE();
CALL CON.SP_CON_DIM_CLI_CLIENTE();
SELECT * FROM CON.DIM_CLI_CLIENTE;

        SELECT
            K.LIFNR,
            K.PARVW,
            T.TXTLG AS TXTLG,
            K.SISORIGEN_ID,
            K.MANDANTE,
            CURRENT_TIMESTAMP() AS FECHA_CARGA,
            TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA
        FROM RAW.SQ1_TBL_KNVP K
        LEFT JOIN RAW.SQ1_EXT_0BPARTNER_TEXT T
            ON K.LIFNR = T.PARTNER
        WHERE K.PARVW = 'ZC';


call pre.SP_PRE_PDIM_CLI_COORDINADORCOMERCIAL();
call con.SP_CON_DIM_CLI_COORDINADORCOMERCIAL();
select * from con.DIM_CLI_COORDINADORCOMERCIAL;

CALL PRE.SP_PRE_PDIM_CLI_ASESORCOMERCIAL();
CALL CON.SP_CON_DIM_CLI_ASESORCOMERCIAL();  
SELECT * FROM CON.DIM_CLI_ASESORCOMERCIAL;

CALL PRE.SP_PRE_PDIM_CLI_EJECUTIVOCIS();
CALL CON.SP_CON_DIM_CLI_EJECUTIVOCIS();
SELECT * FROM CON.DIM_CLI_EJECUTIVOCIS;

CALL PRE.SP_PRE_PDIM_CLI_TIENDARECIBO();
CALL CON.SP_CON_DIM_CLI_TIENDARECIBO();
SELECT * FROM CON.DIM_CLI_TIENDARECIBO;

SELECT
            A.VKORG || '_' || A.VTWEG || '_' || A.SPART || '_' || A.KUNNR AS DESTINATARIO_ID,
            A.KUNNR AS DESTINATARIO,
            A.VKORG AS ORGVENTAS_ID,
            A.VTWEG AS CANALDISTRIB_ID,
            A.SPART AS SECTOR_ID,
            C.LIFNR AS COORDINADORDEST_ID,
            V.LIFNR AS ASESORDEST_ID,
            T.TXTMD AS DESTINATARIO_TEXT,
            A.SISORIGEN_ID,
            A.MANDANTE,
            CURRENT_TIMESTAMP() AS FECHA_CARGA,
            TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA
        FROM RAW.SQ1_EXT_0CUST_SALES_ATTR A
        LEFT JOIN RAW.SQ1_TBL_KNVP C
            ON C.VKORG = A.VKORG
        AND C.VTWEG = A.VTWEG
        AND C.SPART = A.SPART
        AND C.KUNNR = A.KUNNR
        AND C.PARVW = 'ZJ' -- Coordinador
        LEFT JOIN RAW.SQ1_TBL_KNVP V
            ON V.VKORG = A.VKORG
        AND V.VTWEG = A.VTWEG
        AND V.SPART = A.SPART
        AND V.KUNNR = A.KUNNR
        AND V.PARVW = 'ZV' -- Asesor
        LEFT JOIN RAW.SQ1_EXT_0CUST_SALES_TEXT T
            ON T.VKORG = A.VKORG
        AND T.VTWEG = A.VTWEG
        AND T.SPART = A.SPART
        AND T.KUNNR = A.KUNNR;

CALL PRE.SP_PRE_PDIM_CLI_DESTINATARIO();
CALL CON.SP_CON_DIM_CLI_DESTINATARIO();
SELECT * FROM CON.DIM_CLI_DESTINATARIO
WHERE COORDINADORDEST_ID IS NOT NULL;

SELECT
            A.VKORG || '_' || A.VTWEG || '_' || A.SPART || '_' || A.KUNNR AS SOLICITANTE_ID,
            A.KUNNR AS SOLICITANTE,
            A.VKORG AS ORGVENTAS_ID,
            A.VTWEG AS CANALDISTRIB_ID,
            A.SPART AS SECTOR_ID,
            A.KDGRP AS GRUPOCLIENTES_ID,
            A.BZIRK AS ZONAVENTAS_ID,
            A.VKGRP AS GRUPOVENDEDORES_ID,
            A.VKBUR AS OFICINAVENTAS_ID,
            A.KVGR1 AS GRUPOCLIENTES1_ID,
            A.KVGR2 AS GRUPOCLIENTES2_ID,
            A.KVGR3 AS GRUPOCLIENTES3_ID,
            A.KVGR4 AS GRUPOCLIENTES4_ID,
            A.KVGR5 AS GRUPOCLIENTES5_ID,
            A.KTGRD AS GRUPOIMPUTCLIENTE_ID,
            A.KLABC AS INDICADOR_ABC_ID,
            T.TXTMD AS SOLICITANTE_TEXT,
            A.SISORIGEN_ID,
            A.MANDANTE,
            CURRENT_TIMESTAMP() AS FECHA_CARGA,
            TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA
        FROM RAW.SQ1_EXT_0CUST_SALES_ATTR A
        LEFT JOIN RAW.SQ1_EXT_0CUST_SALES_TEXT T
            ON T.VKORG = A.VKORG
        AND T.VTWEG = A.VTWEG
        AND T.SPART = A.SPART
        AND T.KUNNR = A.KUNNR;

call PRE.SP_PRE_PDIM_CLI_SOLICITANTE();
call CON.SP_CON_DIM_CLI_SOLICITANTE();
select * from CON.DIM_CLI_SOLICITANTE;

select * from logs.historial_ejecuciones
order by historial_ejecuciones.fecha_hora_inicio desc;

SELECT COUNT(*) FROM CON.DIM_CLI_SOLICITANTE;
SELECT COUNT(*) FROM CON.VW_DIM_CLI_DESTINATARIO;

CALL PRE.SP_PRE_PDIM_CLI_ASESORCOMERCIAL();
CALL CON.SP_CON_DIM_CLI_ASESORCOMERCIAL();

CALL PRE.SP_PRE_PDIM_CLI_COORDINADORCOMERCIAL();
CALL CON.SP_CON_DIM_CLI_COORDINADORCOMERCIAL();

CALL PRE.SP_PRE_PDIM_CLI_EJECUTIVOCIS();
CALL CON.SP_CON_DIM_CLI_EJECUTIVOCIS();

CALL PRE.SP_PRE_PDIM_CLI_TIENDARECIBO();
CALL CON.SP_CON_DIM_CLI_TIENDARECIBO();

SELECT * FROM CON.DIM_CLI_EJECUTIVOCIS;

        SELECT
            K.LIFNR,
            K.PARVW,
            T.TXTLG,
            K.SISORIGEN_ID,
            K.MANDANTE,
            CURRENT_TIMESTAMP() AS FECHA_CARGA,
            TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA
        FROM RAW.SQ1_TBL_KNVP K
        LEFT JOIN (
            SELECT *
            FROM (
                SELECT *,
                    ROW_NUMBER() OVER (PARTITION BY PARTNER ORDER BY TXTLG) AS rn
                FROM RAW.SQ1_EXT_0BPARTNER_TEXT
            )
            WHERE rn = 1
        ) T ON K.LIFNR = T.PARTNER
        WHERE K.PARVW = 'ZC';

SELECT LIFNR, COUNT(*) AS total
FROM RAW.SQ1_TBL_KNVP
WHERE PARVW = 'ZC'
GROUP BY LIFNR
HAVING COUNT(*) > 1
ORDER BY total DESC;
CALL PRE.SP_PRE_PDIM_CLI_TIENDARECIBO();

SELECT COORDINADORCOMERCIAL_ID, COUNT(*) AS num_registros FROM PRE.PDIM_CLI_COORDINADORCOMERCIAL GROUP BY COORDINADORCOMERCIAL_ID HAVING COUNT(*) > 1;
SELECT *  FROM PRE.PDIM_CLI_COORDINADORCOMERCIAl;
SELECT ASESORCOMERCIAL_ID, COUNT(*) AS num_registros FROM CON.DIM_CLI_ASESORCOMERCIAL GROUP BY ASESORCOMERCIAL_ID HAVING COUNT(*) > 1;
SELECT DESTINATARIO_ID, COUNT(*) AS num_registros FROM CON.DIM_CLI_DESTINATARIO GROUP BY DESTINATARIO_ID HAVING COUNT(*) > 1;

SELECT SOLICITANTE_ID, COUNT(*) AS num_registros FROM CON.DIM_CLI_SOLICITANTE GROUP BY SOLICITANTE_ID HAVING COUNT(*) > 1;

SELECT COUNT(*) FROM CON.DIM_CLI_SOLICITANTE;

truncate table raw.SQ1_TBL_KNVP;
truncate table raw.SQ1_EXT_0BPARTNER_TEXT;

select * from raw.SQ1_EXT_0BPARTNER_TEXT;


-- Verificar duplicados de LIFNR contra PARTNER
SELECT
    K.LIFNR,
    COUNT(T.PARTNER) AS cantidad_registros_en_text
FROM RAW.SQ1_TBL_KNVP K
LEFT JOIN RAW.SQ1_EXT_0BPARTNER_TEXT T
    ON K.LIFNR = T.PARTNER
WHERE K.PARVW = 'ZJ'  -- Solo el rol de Coordinador Comercial
GROUP BY K.LIFNR
HAVING COUNT(T.PARTNER) > 1
ORDER BY cantidad_registros_en_text DESC;

SELECT 
    K.LIFNR,
    T.PARTNER,
    T.TXTLG
FROM RAW.SQ1_TBL_KNVP K
LEFT JOIN RAW.SQ1_EXT_0BPARTNER_TEXT T
    ON K.LIFNR = T.PARTNER
WHERE K.PARVW = 'ZJ'
AND K.LIFNR IN ( -- Aquí metes los LIFNR que detectaste con más de un registro
    SELECT K2.LIFNR
    FROM RAW.SQ1_TBL_KNVP K2
    LEFT JOIN RAW.SQ1_EXT_0BPARTNER_TEXT T2
        ON K2.LIFNR = T2.PARTNER
    WHERE K2.PARVW = 'ZJ'
    GROUP BY K2.LIFNR
    HAVING COUNT(T2.PARTNER) > 1
)
ORDER BY K.LIFNR;

SELECT
    LIFNR,
    PARVW,
    TXTLG,
    SISORIGEN_ID,
    MANDANTE,
    CURRENT_TIMESTAMP() AS FECHA_CARGA,
    TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA
FROM (
    SELECT
        K.LIFNR,
        K.PARVW,
        T.TXTLG,
        K.SISORIGEN_ID,
        K.MANDANTE,
        ROW_NUMBER() OVER (
            PARTITION BY K.LIFNR
            ORDER BY T.TXTLG, K.MANDANTE
        ) AS rn
    FROM RAW.SQ1_TBL_KNVP K
    LEFT JOIN RAW.SQ1_EXT_0BPARTNER_TEXT T
        ON K.LIFNR = T.PARTNER
    WHERE K.PARVW = 'ZC'
)
QUALIFY rn = 1;


SELECT LIFNR, COUNT(*) AS total
FROM RAW.SQ1_TBL_KNVP
WHERE PARVW = 'ZJ'  -- Solo si filtras por tipo de interlocutor (coordinador)
GROUP BY LIFNR
HAVING COUNT(*) > 1
ORDER BY total DESC;

SELECT PARTNER, COUNT(*) AS total
FROM RAW.SQ1_EXT_0BPARTNER_TEXT
GROUP BY PARTNER
HAVING COUNT(*) > 1
ORDER BY total DESC;


SELECT *
FROM RAW.SQ1_TBL_KNVP
where lifnr = '0001300218';


select * from CON.VW_FCT_COM_ADH_BACKORDER;

select * from raw.sq1_ext_z_tcurr;

SELECT
    PARVW,
    COUNT(DISTINCT LIFNR) AS total_unicos
FROM RAW.SQ1_TBL_KNVP
WHERE PARVW IN ('ZV', 'ZC', 'ZS', 'ZJ')
GROUP BY PARVW
ORDER BY PARVW;

SELECT 'DIM_CLI_EJECUTIVOCIS' AS tabla, COUNT(*) AS total FROM CON.DIM_CLI_EJECUTIVOCIS
UNION ALL
SELECT 'DIM_CLI_TIENDARECIBO', COUNT(*) FROM CON.DIM_CLI_TIENDARECIBO
UNION ALL
SELECT 'DIM_CLI_COORDINADORCOMERCIAL', COUNT(*) FROM CON.DIM_CLI_COORDINADORCOMERCIAL
UNION ALL
SELECT 'DIM_CLI_ASESORCOMERCIAL', COUNT(*) FROM CON.DIM_CLI_ASESORCOMERCIAL;



SELECT VKORG, VTWEG, SPART, KUNNR, COUNT(*) AS total
FROM RAW.SQ1_TBL_KNVP
WHERE PARVW = 'ZV'
GROUP BY VKORG, VTWEG, SPART, KUNNR
HAVING COUNT(*) > 1
ORDER BY total DESC;

SELECT VKORG, VTWEG, SPART, KUNNR, COUNT(*) AS total
FROM RAW.SQ1_EXT_0CUST_SALES_TEXT
GROUP BY VKORG, VTWEG, SPART, KUNNR
HAVING COUNT(*) > 1;

