insert into SEGURIDAD.SEG_USUARIO_ROLE 
	(USER_NM,
	ROLE_NM)
	values
	('FERNANDO_CUELLAR','SAP_ROLE');

DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE 
	WHERE USER_NM = 'FERNANDO_CUELLAR';
SELECT * FROM SEGURIDAD.SEG_USUARIO_ROLE 
    WHERE USER_NM = 'FERNANDO_CUELLAR';
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE 
	WHERE USER_NM = 'FERNANDO_CUELLAR'
	AND ROLE_NM = 'SAP_ROLE';

DELETE FROM seguridad.seg_role_dimension 
    WHERE ROLE_NM = 'BACKORDER_REV_ROLE';

DELETE FROM seguridad.seg_role_dimension 
    WHERE ROLE_NM = 'BACKORDER_REV_ROLE'
    AND DIM = 'ORGVENTAS_ID'
    AND VALOR = 'ALL';

SELECT * FROM seguridad.seg_role_dimension 
    WHERE ROLE_NM = 'BACKORDER_REV_ROLE';

SELECT * FROM seguridad.SEG_USUARIO_DIMENSION 
    WHERE USER_NM = 'FERNANDO_CUELLAR';

--ORGVENTAS_ID
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ORGVENTAS_ID', 'R101');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ORGVENTAS_ID', 'ALL');

-- --CANALDISTRIB_ID
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CANALDISTRIB_ID', 'NA');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CANALDISTRIB_ID', 'ALL');

-- -- --INNER JOIN CON LA DIMENSION
INSERT INTO seguridad.SEG_USUARIO_DIMENSION (USER_NM, DIM, VALOR) VALUES ('FERNANDO_CUELLAR', 'CENTRO_ID', 'R101');
-- INSERT INTO seguridad.SEG_USUARIO_DIMENSION (USER_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CENTRO_ID', 'R107');


delete from seguridad.SEG_USUARIO_DIMENSION 
    WHERE USER_NM = 'FERNANDO_CUELLAR'
    AND DIM = 'CENTRO_ID';

-- select * from seguridad.SEG_USUARIO_DIMENSION 
--     where USER_NM = 'FERNANDO_CUELLAR';

--CENTRO
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CENTRO_ID', 'R101');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CENTRO_ID', 'R120');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CENTRO_ID', 'R107');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'CENTRO_ID', 'ALL');

--OFICINAVENTAS_ID
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'OFICINAVENTAS_ID', 'RMN1');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'OFICINAVENTAS_ID', 'RMN2');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'OFICINAVENTAS_ID', 'RGD1');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'OFICINAVENTAS_ID', 'ALL');

-- --GRUPOVENDEDORES_ID
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'GRUPOVENDEDORES_ID', '001');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'GRUPOVENDEDORES_ID', 'ALL');

-- --SOLICITANTE_ID*****
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'GRUPOCLIENTES2_ID', 'ZPO');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'GRUPOCLIENTES2_ID', 'ZFI');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'GRUPOCLIENTES2_ID', 'ALL');

delete from seguridad.seg_role_dimension 
    where ROLE_NM = 'BACKORDER_REV_ROLE'
    and DIM = 'GRUPOCLIENTES2_ID';

--DESTINATARIO_ID
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ASESORDEST_ID', '0001302294');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'COORDINADORDEST_ID', '0001303565');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'DESTINATARIO_ID', 'ALL');

INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'UENADHESIVOS_ID', 'AMR1');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'UENADHESIVOS_ID', 'ALL');

INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ASESORCOMERCIAL_ID', 'ALL');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ASESORCOMERCIAL_ID', '0001300563');
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('BACKORDER_REV_ROLE', 'ASESORCOMERCIAL_ID', '0001303252');


select * from con.vw_fct_com_adh_ventas;

select aniomes, sum(vta_ind_venta_real_impuesto_loc) as total_impuesto, sum(vta_ind_venta_real_fletes_loc) as total_fletes, sum(vta_ind_venta_real_fletes_impuestos_loc) as total_fletes_impuestos from mirroring.fct_com_adh_comercial
where vta_ind_venta_real_impuesto_loc != 0
group by aniomes
order by aniomes;

select * --sum(VENTA_REAL_IVA_ML) 
from PRE.PFCT_COM_ADH_VENTAS_HIST
where ORGANIZACION_VENTAS_CLAVE = 'A101';

SELECT SUM(IND_VENTA_REAL_IMPUESTO_LOC) AS TOTAL_VENTA_REAL_IVA_ML
FROM CON.FCT_COM_ADH_VENTAS_HIST
WHERE ORGVENTAS_ID = 'A101'
AND ANIO BETWEEN 2023 AND 2024;


SELECT "[CDZB3U1AVKXXZ5S7J08L3IO7G].[CDZB3U1AVKXXZ5S7J08L3EMTO] Venta Real IVA $ML"
FROM RAW.BW4_VENTAS_HIST_NEW V
WHERE "[0COMP_CODE].[20COMP_CODE] Clave" = 'A101'
AND "[0CALMONTH].[20CALMONTH] Clave" = '202401';

SELECT SUM("[CDZB3U1AVKXXZ5S7J08L3IO7G].[CDZB3U1AVKXXZ5S7J08L3EMTO] Venta Real IVA $ML") AS TOTAL_VENTA_REAL_IVA_ML
FROM RAW.BW4_VENTAS_HIST_NEW V
WHERE RIGHT("[0CALMONTH].[20CALMONTH] Clave", 4) BETWEEN '2023' AND '2024'
AND "[0COMP_CODE].[20COMP_CODE] Clave" = 'A101';

TOTAL_VENTA_REAL_IVA_ML
5,832,307,217.38;


SELECT *
FROM RAW.BW4_VENTAS_HIST_NEW V
LIMIT 10;