INSERT INTO PRE.PFCT_COM_ADH_VENTAS_PCP_HIST
        (
            ANIO	,
            MES	,
            ANIOMES	,
            SOCIEDAD_ID	,
            ORGVENTAS_ID	,
            CANALDISTRIB_ID	,
            SECTOR_ID	,
            CENTRO_ID	,
	        OFICINAVENTAS_ID,            
            UENADHESIVOS_ID	,
            PAIS_ID	,
            REGION_ID	,
            ASESORFACTURA_ID	,
            CLIENTE_ID	,
            SOLICITANTE_ID	,
            DESTINATARIO_ID	,
            MATERIAL_ID	,
            MATERIALVENTAS_ID	,
            MATERIALCENTRO_ID	,
            IND_VENTA_PCP_TON	,
            UNI_EST	,
            IND_VENTA_PCP_LOC	,
            MON_LOC	,
            IND_VENTA_PCP_USD	,
            MON_USD	,
            SISORIGEN_ID	,
            MANDANTE	,
            FECHA_CARGA	,
            ZONA_HORARIA
        )
SELECT 
    NULLIF(RIGHT(ANIOMES_NATURAL_CLAVE, 4), '#') AS ANIO,
    NULLIF(LEFT(ANIOMES_NATURAL_CLAVE, 2), '#') AS MES,
    NULLIF(RIGHT(ANIOMES_NATURAL_CLAVE, 4) || LEFT(ANIOMES_NATURAL_CLAVE, 2), '#') AS ANIOMES,

    NULLIF(ORGANIZACION_VENTAS_CLAVE, '#') AS SOCIEDAD_ID,
    NULLIF(ORGANIZACION_VENTAS_CLAVE, '#') AS ORGVENTAS_ID,
    NULLIF(CANAL_DISTRIBUCION_CLAVE, '#') AS CANALDISTRIB_ID,
    '00' AS SECTOR_ID,

    NULLIF(CENTRO_CLAVE, '#') AS CENTRO_ID,
    NULLIF(OFICINA_VENTAS_CLAVE, '#') AS OFICINAVENTAS_ID,
    NULLIF(UEN_CLAVE, '#') AS UENADHESIVOS_ID,

    NULLIF(PAIS_CLAVE, '#') AS PAIS_ID,
    REPLACE(NULLIF(REGION_CLAVE, '#'), '/', '_') AS REGION_ID,

    NULLIF(ASESOR_COMERCIAL_FACTURA_CLAVE, '#') AS ASESORFACTURA_ID,

    NULLIF(SOLICITANTE_CLAVE_NO_RELACIONADA, '#') AS CLIENTE_ID,

    CONCAT(
        NULLIF(ORGANIZACION_VENTAS_CLAVE, '#'), '_',
        NULLIF(CANAL_DISTRIBUCION_CLAVE, '#'), '_',
        '00', '_',
        NULLIF(SOLICITANTE_CLAVE_NO_RELACIONADA, '#')
    ) AS SOLICITANTE_ID,

    CONCAT(
        NULLIF(ORGANIZACION_VENTAS_CLAVE, '#'), '_',
        NULLIF(CANAL_DISTRIBUCION_CLAVE, '#'), '_',
        '00', '_',
        NULLIF(DESTINATARIO_MERCANCIA_CLAVE_NO_RELACIONADA, '#')
    ) AS DESTINATARIO_ID,

    LTRIM(NULLIF(MATERIAL_CLAVE, '#'), '0') AS MATERIAL_ID,
    CONCAT(
        NULLIF(ORGANIZACION_VENTAS_CLAVE, '#'), '_',
        NULLIF(CANAL_DISTRIBUCION_CLAVE, '#'), '_',
        LTRIM(NULLIF(MATERIAL_CLAVE, '#'), '0')
    ) AS MATERIALVENTAS_ID,
    CONCAT(
        NULLIF(CENTRO_CLAVE, '#'), '_',
        LTRIM(NULLIF(MATERIAL_CLAVE, '#'), '0')
    ) AS MATERIALCENTRO_ID,

    COALESCE(SUM(PCP_VENTA_TON), 0) AS IND_VENTA_PCP_TON,
    COALESCE(U.VALOR_ESTANDARD, UNIDAD_ESTADISTICA_CLAVE) AS UNI_EST,
    COALESCE(SUM(PCP_VENTA_ML), 0) AS IND_VENTA_PCP_LOC,
    'MXN' AS MON_LOC,
    COALESCE(SUM(PCP_VENTA_USD), 0) AS IND_VENTA_PCP_USD,
    'USD' AS MON_USD,

    'BW4' AS SISORIGEN_ID,
    '' AS MANDANTE,
    CURRENT_TIMESTAMP() AS FECHA_CARGA,
    TO_CHAR(CURRENT_TIMESTAMP(), 'TZH:TZM') AS ZONA_HORARIA

FROM PRE.PFCT_COM_ADH_VENTAS_HIST H
LEFT JOIN RAW.CAT_UNIDAD_ESTADISTICA U
    ON U.VALOR_ORIGINAL = H.UNIDAD_ESTADISTICA_CLAVE

GROUP BY 
    LEFT(ANIOMES_NATURAL_CLAVE, 4),
    RIGHT(ANIOMES_NATURAL_CLAVE, 2),
    ANIOMES_NATURAL_CLAVE,
    ORGANIZACION_VENTAS_CLAVE,
    CANAL_DISTRIBUCION_CLAVE,
    CENTRO_CLAVE,
    OFICINA_VENTAS_CLAVE,
    UEN_CLAVE,
    PAIS_CLAVE,
    REGION_CLAVE,
    ASESOR_COMERCIAL_FACTURA_CLAVE,
    SOLICITANTE_CLAVE_NO_RELACIONADA,
    DESTINATARIO_MERCANCIA_CLAVE_NO_RELACIONADA,
    MATERIAL_CLAVE,
    UNIDAD_ESTADISTICA_CLAVE,
    U.VALOR_ESTANDARD;

//este es el query para insertar en la tabla de ventas PCP lo historico

