REEMBOLSO_FLETES_ML,
VENTA_PRECIO_CONSTRUCTORA_MXN,
VENTA_PRECIO_CONSTRUCTORA_ML,
VENTA_PRECIO_CONSTRUCTORA_USD,
VENTA_REAL_C_FLETES_ML,
VENTA_REAL_C_FLETES_USD,
VENTA_REAL_C_FLETES_IVA_ML,
VENTA_REAL_C_FLETES_IVA_USD,
DESCUENTOS_ML,
PROMOCIONES_ML,
REBATES_ML,
CORRECTIVAS_ML,
VENTA_PRECIO_LISTA_USD,
VENTA_PRECIO_TEÓRICO_USD,
VENTA_PRECIO_NETO_USD,
DESCUENTOS_USD,
PROMOCIONES_USD,
REBATES_USD,
CORRECTIVAS_USD,
IMPORTE_IVA_MXN,
IMPORTE_IVA_ML,
IMPORTE_IVA_USD,


;

SELECT 
SUM(IND_VENTA_REAL_TON),
SUM(IND_VENTA_PRECIOLISTA_LOC),
SUM(IND_VENTA_PRECIOFACTURA_LOC),
SUM(IND_VENTA_PRECIONETO_LOC),
SUM(IND_VENTA_REAL_LOC),
SUM(IND_VENTA_REAL_IMPUESTO_LOC)
 FROM CON.FCT_COM_ADH_VENTAS_HIST
WHERE ORGVENTAS_ID = 'A101';