CREATE OR REPLACE VIEW CON.VW_DIM_CLI_COORDINADORCOMERCIAL AS
SELECT
    C.COORDINADORCOMERCIAL_ID,
    C.FUNCION_INTERLOCUTOR,
    C.COORDINADORCOMERCIAL_TEXT,
    C.SISORIGEN_ID,
    C.MANDANTE,
    C.FECHA_CARGA,
    C.ZONA_HORARIA
FROM CON.DIM_CLI_COORDINADORCOMERCIAL C;

SELECT * FROM CON.VW_DIM_CLI_COORDINADORCOMERCIAL;
