CREATE OR REPLACE VIEW CON.VW_DIM_CLI_CLIENTE AS
SELECT
    C.CLIENTE_ID,
    C.CLIENTE_TEXT,
    C.RAMO_ID,
    R.RAMO_TEXT,
    C.PAIS_ID,
    P.PAIS_TEXT,
    C.REGION_ID,
    G.REGION_TEXT,
    C.LOCALIDAD,
    C.CALLE,
    C.CODIGOPOSTAL,
    C.CLASIFICACIONCLIENTE_ID,
    CL.CLASIFICACIONCLIENTE_TEXT,
    C.GRUPOSOLICITANTE_ID,
    GR.GRUPOSOLICITANTE_TEXT,
    C.RFC_ID,
    C.SISORIGEN_ID,
    C.MANDANTE,
    C.FECHA_CARGA,
    C.ZONA_HORARIA
FROM DIM_CLI_CLIENTE C
LEFT JOIN DIM_CLI_RAMO R
    ON C.RAMO_ID = R.RAMO_ID
LEFT JOIN DIM_GEO_PAIS P
    ON C.PAIS_ID = P.PAIS_ID
LEFT JOIN DIM_GEO_REGION G
    ON C.REGION_ID = G.REGION_ID
LEFT JOIN DIM_CLI_CLASIFICACIONCLIENTE CL
    ON C.CLASIFICACIONCLIENTE_ID = CL.CLASIFICACIONCLIENTE_ID
LEFT JOIN DIM_CLI_GRUPOSOLICITANTE GR
    ON C.GRUPOSOLICITANTE_ID = GR.GRUPOSOLICITANTE_ID;

-- SELECT COUNT(*) FROM CON.VW_DIM_CLI_CLIENTE;
-- --6468

-- --213
-- SELECT 
--     CLIENTE_ID,
--     RAMO_ID,
--     COUNT(*) AS TOTAL
-- FROM CON.DIM_CLI_CLIENTE
-- GROUP BY CLIENTE_ID, RAMO_ID
-- HAVING COUNT(*) > 1;

-- SELECT 
--     C.CLIENTE_ID,
--     C.RAMO_ID,
--     R.RAMO_TEXT,
--     COUNT(*) AS TOTAL_COMBINACIONES
-- FROM CON.DIM_CLI_CLIENTE C
-- LEFT JOIN CON.DIM_CLI_RAMO R
--     ON C.RAMO_ID = R.RAMO_ID
-- GROUP BY C.CLIENTE_ID, C.RAMO_ID, R.RAMO_TEXT
-- HAVING COUNT(*) > 1;



-- SELECT GRUPOSOLICITANTE_ID, COUNT(*) 
-- FROM CON.DIM_CLI_GRUPOSOLICITANTE
-- GROUP BY GRUPOSOLICITANTE_ID
-- HAVING COUNT(*) > 1;

-- SELECT * FROM CON.DIM_CLI_GRUPOSOLICITANTE WHERE GRUPOSOLICITANTE_ID = 'Z_DIVERSOS';
-- SELECT COUNT(*) FROM CON.DIM_CLI_CLIENTE WHERE GRUPOSOLICITANTE_ID = 'Z_DIVERSOS';
-- SELECT * FROM CON.DIM_CLI_RAMO WHERE RAMO_ID = '0001';

-- SELECT 
--     C.CLIENTE_ID,
--     C.GRUPOSOLICITANTE_ID,
--     COUNT(*) AS TOTAL_COMBINACIONES
-- FROM CON.DIM_CLI_CLIENTE C
-- LEFT JOIN CON.DIM_CLI_GRUPOSOLICITANTE GR
--     ON C.GRUPOSOLICITANTE_ID = GR.GRUPOSOLICITANTE_ID
-- GROUP BY C.CLIENTE_ID, C.GRUPOSOLICITANTE_ID
-- HAVING COUNT(*) > 1;

-- SELECT * FROM CON.DIM_CLI_CLIENTE WHERE CLIENTE_ID = '0010108903';

-- SELECT 
--     GRUPOSOLICITANTE_ID,
--     COUNT(*) AS TOTAL
-- FROM CON.DIM_CLI_GRUPOSOLICITANTE
-- GROUP BY GRUPOSOLICITANTE_ID
-- HAVING COUNT(*) > 1;