CREATE OR REPLACE VIEW CON.VW_DIM_CLI_TIENDARECIBO AS
SELECT
    T.TIENDARECIBO_ID,
    T.FUNCION_INTERLOCUTOR,
    T.TIENDARECIBO_TEXT,
    T.SISORIGEN_ID,
    T.MANDANTE,
    T.FECHA_CARGA,
    T.ZONA_HORARIA
FROM CON.DIM_CLI_TIENDARECIBO T;

SELECT * FROM CON.VW_DIM_CLI_TIENDARECIBO
WHERE TIENDARECIBO_TEXT IS NOT NULL;

SELECT * FROM CON.DIM_CLI_TIENDARECIBO;