CREATE OR REPLACE VIEW CON.VW_DIM_CLI_EJECUTIVOCIS AS
SELECT
    E.EJECUTIVOCIS_ID,
    E.FUNCION_INTERLOCUTOR,
    E.EJECUTIVOCIS_TEXT,
    E.SISORIGEN_ID,
    E.MANDANTE,
    E.FECHA_CARGA,
    E.ZONA_HORARIA
FROM CON.DIM_CLI_EJECUTIVOCIS E;

SELECT * FROM CON.VW_DIM_CLI_EJECUTIVOCIS;