create or replace task MIRRORING.TASK_FCT_LOG_ADH_INVENTARIO
	warehouse=LAMOSALAKE_DEV_WH
	when SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_LOG_ADH_INVENTARIO')
	as begin

    TRUNCATE TABLE TR_FCT_LOG_ADH_INVENTARIO;

    INSERT INTO TR_FCT_LOG_ADH_INVENTARIO
    SELECT * FROM STREAM_VW_FCT_LOG_ADH_INVENTARIO;
    

    -- 1. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_LOG_ADH_INVENTARIO d
    USING (
      SELECT * FROM TR_FCT_LOG_ADH_INVENTARIO
      WHERE METADATA$ACTION = 'DELETE'
    ) s
    WHERE d.ANIOMES = s.ANIOMES
     AND  d.CENTRO_ID = s.CENTRO_ID
     AND s.ALMACEN_ID = d.ALMACEN_ID
     AND s.MATERIAL_ID = d.MATERIAL_ID
     AND s.STOCKESPECIAL = d.STOCKESPECIAL
     AND s.NUMSTOCKESPECIAL = d.NUMSTOCKESPECIAL
     AND s.MODELO = d.MODELO
    
    ;

    -- 2. INSERTAR o ACTUALIZAR registros nuevos o modificados
    MERGE INTO MIRRORING.FCT_LOG_ADH_INVENTARIO d
    USING (
      SELECT * FROM TR_FCT_LOG_ADH_INVENTARIO
      WHERE METADATA$ACTION = 'INSERT'
    ) s
    ON d.ANIOMES = s.ANIOMES
     AND d.CENTRO_ID = s.CENTRO_ID
     AND s.ALMACEN_ID = d.ALMACEN_ID
     AND s.MATERIAL_ID = d.MATERIAL_ID
     AND s.STOCKESPECIAL = d.STOCKESPECIAL
     AND s.NUMSTOCKESPECIAL = d.NUMSTOCKESPECIAL
     AND s.MODELO = d.MODELO
    WHEN NOT MATCHED THEN INSERT (
      ANIO,
      MES,
      ANIOMES,
      FECHA_FOTO_INVENTARIO,
      CENTRO_ID,
      ALMACEN_ID,
      ALMACENCENTRO_ID,
      MATERIAL_ID,
      MATERIALCENTRO_ID,
      TIPOMATERIAL_ID,
      CONTROL_PRECIOS,
      STOCKESPECIAL,
      NUMSTOCKESPECIAL,
      IND_LIBRE_UTILIZACION_UMB,
      IND_BLOQUEADO_UMB,
      IND_CONTROL_CALIDAD_UMB,
      IND_TRANSITO_UMB,
      IND_INVENTARIO_FISICO_UMB,
      IND_LIBRE_VENTA_UMB,
      IND_STOCK_SEGURIDAD_UMB,
      UNI_UMB,
      IND_LIBRE_UTILIZACION_TON,
      IND_BLOQUEADO_TON,
      IND_CONTROL_CALIDAD_TON,
      IND_TRANSITO_TON,
      IND_INVENTARIO_FISICO_TON,
      IND_LIBRE_VENTA_TON,
      IND_STOCK_SEGURIDAD_TON,
      UNI_EST,
      IND_COSTO_INV_MXN,
      MON_MXN,
      IND_COSTO_INV_LOC,
      MON_LOC,
      IND_COSTO_INV_USD,
      MON_USD,
      MODELO,
      SISORIGEN_ID,
      MANDANTE,
      FECHA_CARGA,
      ZONA_HORARIA
    ) VALUES (
S.ANIO,
      MES,
      ANIOMES,
      FECHA_FOTO_INVENTARIO,
      CENTRO_ID,
      ALMACEN_ID,
      ALMACENCENTRO_ID,
      MATERIAL_ID,
      MATERIALCENTRO_ID,
      TIPOMATERIAL_ID,
      CONTROL_PRECIOS,
      STOCKESPECIAL,
      NUMSTOCKESPECIAL,
      IND_LIBRE_UTILIZACION_UMB,
      IND_BLOQUEADO_UMB,
      IND_CONTROL_CALIDAD_UMB,
      IND_TRANSITO_UMB,
      IND_INVENTARIO_FISICO_UMB,
      IND_LIBRE_VENTA_UMB,
      IND_STOCK_SEGURIDAD_UMB,
      UNI_UMB,
      IND_LIBRE_UTILIZACION_TON,
      IND_BLOQUEADO_TON,
      IND_CONTROL_CALIDAD_TON,
      IND_TRANSITO_TON,
      IND_INVENTARIO_FISICO_TON,
      IND_LIBRE_VENTA_TON,
      IND_STOCK_SEGURIDAD_TON,
      UNI_EST,
      IND_COSTO_INV_MXN,
      MON_MXN,
      IND_COSTO_INV_LOC,
      MON_LOC,
      IND_COSTO_INV_USD,
      MON_USD,
      MODELO,
      SISORIGEN_ID,
      MANDANTE,
      FECHA_CARGA,
      ZONA_HORARIA
);

end;