CREATE OR ALTER TABLE RAW.SQ1_EXT_0C_CTR_AREA_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	SPRAS VARCHAR(1),
	KKBER VARCHAR(4),
	KKBTX VARCHAR(35),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);