CREATE OR ALTER TABLE RAW.SQ1_EXT_0REPR_GROUP_TEXT (
	TS_SEQUENCE_NUMBER NUMBER(20,0),
	SBGRP VARCHAR(3),
	KKBER VARCHAR(4),
	TXTMD VARCHAR(30),
	MANDANTE VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10),
	TIPO VARCHAR(10)
);