CREATE OR REPLACE VIEW CON.VW_FCT_COM_ADH_BACKORDER AS
SELECT *
FROM CON.FCT_COM_ADH_BACKORDER_ACT
  WHERE 1=1
  AND ORGVENTAS_ID IN (SELECT ORGVENTAS_ID FROM CON.VW_DIM_ORG_ORGANIZACIONVENTAS)
  AND CANALDISTRIB_ID IN (SELECT CANALDISTRIB_ID FROM CON.VW_DIM_ORG_CANALDISTRIBUCION)
  AND CENTRO_ID IN (SELECT CENTRO_ID FROM CON.VW_DIM_ORG_CENTRO)
  AND OFICINAVENTAS_ID IN (SELECT OFICINAVENTAS_ID FROM CON.VW_DIM_ORG_OFICINAVENTAS)
  AND GRUPOVENDEDORES_ID IN (SELECT GRUPOVENDEDORES_ID FROM CON.VW_DIM_ORG_GRUPOVENDEDORES)
  AND SOLICITANTE_ID IN (SELECT SOLICITANTE_ID FROM CON.VW_DIM_CLI_SOLICITANTE)
  AND DESTINATARIO_ID IN (SELECT DESTINATARIO_ID FROM CON.VW_DIM_CLI_DESTINATARIO)
  AND ASESORPEDIDO_ID IN (SELECT ASESORCOMERCIAL_ID FROM CON.VW_DIM_CLI_ASESORCOMERCIAL)
  AND UENADHESIVOS_ID IN (SELECT UENADHESIVOS_ID FROM CON.VW_DIM_ORG_UENADHESIVOS)

UNION ALL

SELECT *
FROM CON.FCT_COM_ADH_BACKORDER_FOTO
  WHERE 1=1
  AND ORGVENTAS_ID IN (SELECT ORGVENTAS_ID FROM CON.VW_DIM_ORG_ORGANIZACIONVENTAS)
  AND CANALDISTRIB_ID IN (SELECT CANALDISTRIB_ID FROM CON.VW_DIM_ORG_CANALDISTRIBUCION)
  AND CENTRO_ID IN (SELECT CENTRO_ID FROM CON.VW_DIM_ORG_CENTRO)
  AND OFICINAVENTAS_ID IN (SELECT OFICINAVENTAS_ID FROM CON.VW_DIM_ORG_OFICINAVENTAS)
  AND GRUPOVENDEDORES_ID IN (SELECT GRUPOVENDEDORES_ID FROM CON.VW_DIM_ORG_GRUPOVENDEDORES)
  AND SOLICITANTE_ID IN (SELECT SOLICITANTE_ID FROM CON.VW_DIM_CLI_SOLICITANTE)
  AND DESTINATARIO_ID IN (SELECT DESTINATARIO_ID FROM CON.VW_DIM_CLI_DESTINATARIO)
  AND ASESORPEDIDO_ID IN (SELECT ASESORCOMERCIAL_ID FROM CON.VW_DIM_CLI_ASESORCOMERCIAL)
  AND UENADHESIVOS_ID IN (SELECT UENADHESIVOS_ID FROM CON.VW_DIM_ORG_UENADHESIVOS);
;

