CREATE OR REPLACE VIEW CON.VW_DIM_FIN_CENTROGESTOR(
    CENTROGESTOR_ID,
    ENTIDADCP_ID,
    CENTROGESTOR,
    CENTROGESTOR_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CENTROGESTOR_ID,
        ENTIDADCP_ID,
        CENTROGESTOR,
        CENTROGESTOR_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_FIN_CENTROGESTOR;