CREATE OR REPLACE VIEW CON.VW_DIM_FIN_CUENTA(
    CUENTA_ID,
    SOCIEDADCO_ID,
    CUENTA,
    CUENTA_TEXT,
    SUBDIVISION_ID,
    SUBDIVISION_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CUENTA_ID,
        SOCIEDADCO_ID,
        CUENTA,
        CUENTA_TEXT,
        SUBDIVISION_ID,
        SUBDIVISION_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_FIN_CUENTA;