CREATE OR REPLACE VIEW CON.VW_DIM_FIN_ACREEDOR(
    ACREEDOR_ID,
    ACREEDOR_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  ACREEDOR_ID,
        ACREEDOR_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_FIN_ACREEDOR;