CREATE OR REPLACE VIEW CON.VW_DIM_FIN_DETALLECOMPREAL(
    DETALLECOMPREAL_ID,
    DETALLECOMPREAL_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  DETALLECOMPREAL_ID,
        DETALLECOMPREAL_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_FIN_DETALLECOMPREAL;