CREATE OR REPLACE VIEW CON.VW_DIM_DOC_CLASEDOCFI(
    CLASEDOCFI_ID,
    CLASEDOCFI_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CLASEDOCFI_ID,
        CLASEDOCFI_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_DOC_CLASEDOCFI;