CREATE OR REPLACE VIEW CON.VW_DIM_FIN_CENTROCOSTO(
    CENTROCOSTO_ID,
	CENTROCOSTO,
	CENTROCOSTO_TEXT,
	SOCIEDADCO_ID,
    SOCIEDADCO_TEXT,
	SOCIEDAD_ID,
    SOCIEDAD_TEXT,
	CENTROBENEF_ID,
    CENTROBENEFICIO_TEXT,
	DIRECCION_ID,
	DIRECCION_TEXT,
	GERENCIA_ID,
	GERENCIA_TEXT,
	SUCURSAL_ID,
	SUCURSAL_TEXT,
	CCAGRUPADOR_ID,
	CCAGRUPADOR_TEXT,
	TIPOGASTO_ID,
	TIPOGASTO_TEXT,
	ENCARGADO_CC_ID,
	ENCARGADO_CC_TEXT,
	ENCARGADO_GERENCIA_ID,
	ENCARGADO_GERENCIA_TEXT,
	ENCARGADO_DIRECCION_ID,
	ENCARGADO_DIRECCION_TEXT,
	SOCIEDADCECOASOC_ID,
	CENTROCOSASOC_ID,
	CENTROCOSASOC_TEXT,
	ENCARGADO_DIRECAREA_ID,
	ENCARGADO_DIRECAREA_TEXT,
	ZTPGTOBPC,
	FECHA_DESDE,
	FECHA_HASTA,
	SISORIGEN_ID,
	MANDANTE,
	FECHA_CARGA,
	ZONA_HORARIA,
	TIPO
) 
WITH ROW ACCESS POLICY SEGURIDAD.RAP_DIM_CENTROCOSTO_ID
    ON (DIRECCION_ID,
        SUCURSAL_ID,
        GERENCIA_ID,
        ENCARGADO_CC_ID,
        ENCARGADO_GERENCIA_ID,
        ENCARGADO_DIRECCION_ID,
        ENCARGADO_DIRECAREA_ID
        )
AS

SELECT  CENTROCOSTO.CENTROCOSTO_ID,
        CENTROCOSTO.CENTROCOSTO,
        CENTROCOSTO.CENTROCOSTO_TEXT,
        CENTROCOSTO.SOCIEDADCO_ID,
        SOCIEDADCO.SOCIEDADCO_TEXT,
        CENTROCOSTO.SOCIEDAD_ID,
        SOCIEDAD.SOCIEDAD_TEXT,
        CENTROCOSTO.CENTROBENEF_ID,
        CENTROBENF.CENTROBENEFICIO_TEXT,
        CENTROCOSTO.DIRECCION_ID,
        CENTROCOSTO.DIRECCION_TEXT,
        CENTROCOSTO.GERENCIA_ID,
        CENTROCOSTO.GERENCIA_TEXT,
        CENTROCOSTO.SUCURSAL_ID,
        CENTROCOSTO.SUCURSAL_TEXT,
        CENTROCOSTO.CCAGRUPADOR_ID,
        CENTROCOSTO.CCAGRUPADOR_TEXT,
        CENTROCOSTO.TIPOGASTO_ID,
        CENTROCOSTO.TIPOGASTO_TEXT,
        CENTROCOSTO.ENCARGADO_CC_ID,
        CENTROCOSTO.ENCARGADO_CC_TEXT,
        CENTROCOSTO.ENCARGADO_GERENCIA_ID,
        CENTROCOSTO.ENCARGADO_GERENCIA_TEXT,
        CENTROCOSTO.ENCARGADO_DIRECCION_ID,
        CENTROCOSTO.ENCARGADO_DIRECCION_TEXT,
        CENTROCOSTO.SOCIEDADCECOASOC_ID,
        CENTROCOSTO.CENTROCOSASOC_ID,
        CENTROCOSTO.CENTROCOSASOC_TEXT,
        CENTROCOSTO.ENCARGADO_DIRECAREA_ID,
        CENTROCOSTO.ENCARGADO_DIRECAREA_TEXT,
        CENTROCOSTO.ZTPGTOBPC,
        CENTROCOSTO.FECHA_DESDE,
        CENTROCOSTO.FECHA_HASTA,
        CENTROCOSTO.SISORIGEN_ID,
        CENTROCOSTO.MANDANTE,
        CENTROCOSTO.FECHA_CARGA,
        CENTROCOSTO.ZONA_HORARIA,
        CENTROCOSTO.TIPO
FROM CON.DIM_FIN_CENTROCOSTO AS CENTROCOSTO

LEFT JOIN CON.DIM_ORG_SOCIEDAD AS SOCIEDAD
ON CENTROCOSTO.SOCIEDAD_ID = SOCIEDAD.SOCIEDAD_ID

LEFT JOIN CON.VW_DIM_FIN_SOCIEDADCO AS SOCIEDADCO
ON CENTROCOSTO.SOCIEDADCO_ID = CENTROCOSTO.SOCIEDADCO_ID

LEFT JOIN CON.DIM_FIN_CENTROBENEFICIO AS CENTROBENF
ON CENTROCOSTO.CENTROBENEF_ID = CENTROBENF.CENTROBENEFICIO_ID;