CREATE OR REPLACE VIEW select * from CON.VW_DIM_FIN_SOCIEDADGLASOC(
    SOCIEDADGLASOC_ID,
    SOCIEDADGLASOC_TEXT,
    PAIS_ID,
    PAIS_TEXT
) AS

SELECT  SOCIEDAD.SOCIEDAD_ID AS SOCIEDADGLASOC_ID,
        SOCIEDAD.SOCIEDAD_TEXT AS SOCIEDADGLASOC_TEXT,
        SOCIEDAD.PAIS_ID AS PAIS_ID,
        PAISTEXT.TXTSH AS PAIS_TEXT
FROM CON.DIM_ORG_SOCIEDAD AS SOCIEDAD

LEFT JOIN RAW.SQ1_EXT_0COUNTRY_TEXT AS PAISTEXT

ON SOCIEDAD.PAIS_ID = PAISTEXT.LAND1;