CREATE OR ALTER TABLE CON.DIM_FIN_VERSION(
    VERSION_ID,
    VERSION_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  VERSION_ID,
        VERSION_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_VERSION;