CREATE OR REPLACE TABLE CON.DIM_FIN_ACREEDOR(
    ACREEDOR_ID VARCHAR(10),
	ACREEDOR_TEXT VARCHAR(35),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(4),
	FECHA_CARGA TIMESTAMP_TZ(9),
	ZONA_HORARIA VARCHAR(12),
	primary key (ACREEDOR_ID)
)