CREATE OR REPLACE TABLE CON.DIM_FIN_GRUPOCREDCLIENTE(
    GRUPOCREDCLIENTE_ID,
    GRUPOCREDCLIENTE,
    GRUPOCREDCLIENTE_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  GRUPOCREDCLIENTE_ID,
        GRUPOCREDCLIENTE,
        GRUPOCREDCLIENTE_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_GRUPOCREDCLIENTE;