CREATE OR ALTER TABLE CON.DIM_FIN_EQUIPORESPCREDITO(
    EQUIPORESPCREDITO_ID,
    EQUIPORESPCREDITO,
    EQUIPORESPCREDITO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  EQUIPORESPCREDITO_ID,
        EQUIPORESPCREDITO,
        EQUIPORESPCREDITO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_EQUIPORESPCREDITO;