CREATE OR REPLACE TABLE CON.DIM_FIN_AREACTRLCDTO(
    AREACTRLCDTO_ID,
    AREACTRLCDTO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  AREACTRLCDTO_ID,
        AREACTRLCDTO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_AREACTRLCDTO;