CREATE OR ALTER TABLE CON.DIM_FIN_EQUIPORESPCREDITO(
    EQUIPORESPCREDITO_ID VARCHAR(8),
	EQUIPORESPCREDITO VARCHAR(3),
	EQUIPORESPCREDITO_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);