CREATE OR ALTER TABLE CON.DIM_FIN_ENTIDADCP(
    ENTIDADCP_ID VARCHAR(4),
	ENTIDADCP_TEXT VARCHAR(40),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);