CREATE OR ALTER TABLE CON.DIM_FIN_CATEGORIAPRES(
    CATEGORIAPRES_ID,
    CATEGORIAPRES_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CATEGORIAPRES_ID,
        CATEGORIAPRES_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_CATEGORIAPRES;