CREATE OR ALTER TABLE CON.DIM_FIN_ENTIDADCP(
    ENTIDADCP_ID,
    ENTIDADCP_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  ENTIDADCP_ID,
        ENTIDADCP_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_ENTIDADCP;