CREATE OR ALTER TABLE CON.DIM_FIN_CLASERIESGO(
    CLASERIESGO_ID,
    CLASERIESGO,
    CLASERIESGO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CLASERIESGO_ID,
        CLASERIESGO,
        CLASERIESGO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_CLASERIESGO;