CREATE OR REPLACE TABLE CON.DIM_FIN_PROGRAMAPRES(
    PROGRAMAPRES_ID,
    PROGRAMAPRES,
    PROGRAMAPRES_TEXT,
    ENTIDADCP_ID,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  PROGRAMAPRES_ID,
        PROGRAMAPRES,
        PROGRAMAPRES_TEXT,
        ENTIDADCP_ID,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_PROGRAMAPRES;