CREATE OR REPLACE TABLE CON.DIM_FIN_CUENTAMAYOR(
    CUENTAMAYOR_ID,
    CUENTAMAYOR,
    CUENTAMAYOR_TEXT,
    PLANCUENTAS_ID,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CUENTAMAYOR_ID,
        CUENTAMAYOR,
        CUENTAMAYOR_TEXT,
        PLANCUENTAS_ID,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM PRE.PDIM_FIN_CUENTAMAYOR