CREATE OR ALTER TABLE CON.DIM_DOC_CLASEDOCFI(
    CLASEDOCFI_ID VARCHAR(2),
	CLASEDOCFI_TEXT VARCHAR(20),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);