CREATE OR ALTER TABLE PRE.PDIM_MAT_GRUPOMATERIALES3(		
GRUPOMATERIALES3_ID	VARCHAR(10)	PRIMARY KEY,
GRUPOMATERIALES3_TEXT	VARCHAR(70)	,
SISORIGEN_ID	VARCHAR(4)	,
MANDANTE	VARCHAR(4)	,
FECHA_CARGA	TIMESTAMP_TZ	,
ZONA_HORARIA	VARCHAR(4)	
)		
;