insert into SEGURIDAD.SEG_USUARIO_ROLE 
	(USER_NM,
	ROLE_NM)
	values
	('FIDEL_RAMIREZ','REV_MEX_COMERCIAL_ROLE'),
	('FIDEL_RAMIREZ','ADH_MEX_COMERCIAL_ROLE');


select * from SEGURIDAD.SEG_USUARIO_ROLE ;

insert into seguridad.seg_role_dimension
(ROLE_NM , DIM , VALOR )
values
('REV_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','R101'),
('REV_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','R311'),
('REV_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','R312'),
('REV_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','R313'),
('REV_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','R401'),
('ADH_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','A101'),
('ADH_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','A102'),
('ADH_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','A103'),
('ADH_MEX_COMERCIAL_ROLE','ORGVENTAS_ID','A201'),
('REV_MEX_COMERCIAL_ROLE','CENTRO_ID','R105'),
('REV_MEX_COMERCIAL_ROLE','CENTRO_ID','R107'),
('REV_MEX_COMERCIAL_ROLE','CENTRO_ID','R109'),
('ADH_MEX_COMERCIAL_ROLE','CENTRO_ID','A111'),
('ADH_MEX_COMERCIAL_ROLE','CENTRO_ID','A121'),
('ADH_MEX_COMERCIAL_ROLE','CENTRO_ID','A131'),
('REV_MEX_COMERCIAL_ROLE','CANALDISTRIB_ID','ALL'),
('ADH_MEX_COMERCIAL_ROLE','CANALDISTRIB_ID','ALL')
;

select * from seguridad.seg_role_dimension;

insert into seguridad.seg_usuario_dimension
(USER_NM , DIM , VALOR )
values
('FIDEL_RAMIREZ','ORGVENTAS_ID','R311'),
('FIDEL_RAMIREZ','ORGVENTAS_ID','R312'),
('FIDEL_RAMIREZ','ORGVENTAS_ID','R313'),
('FIDEL_RAMIREZ','CENTRO_ID','R105'),
('FIDEL_RAMIREZ','CENTRO_ID','R109');



SELECT * FROM SEGURIDAD.VW_CON_SEG_USUARIO_ROLE_DIMENSION;