CREATE OR REPLACE VIEW CON.VW_FCT_FIN_REV_CARTERA (
	ANIO,
    MES,
    ANIO_MES,
    SOCIEDAD_ID,
    ORGVENTAS_ID,
    CANALDISTRIB_ID,
    SECTOR_ID,
    OFICINAVENTAS_ID,
    DEUDOR_ID,
    PAIS_ID,
    SOLICITANTE,
    SOLICITANTE_ID,
    DESTINATARIO,
    DESTINATARIO_ID,
    CLASEDOCFI_ID,
    DOCUMENTOFI,
    CENTROBENEFICIO_ID,
    CUENTALIBROMAYOR_ID,
    DOCREFERENCIA,
    FACTURA,
    CLASEFACTURA_ID,
    ASESORFACTURA_ID,
    ASESORFACTURA_NAME,
    AREACTRLCDTO_ID,
    CLASERIESGO_ID,
    EQUIPORESPCREDITO_ID,
    EQUIPORESPCREDITO_NAME,
    GRUPOCREDCLIENTE_ID,
    GRUPCREDCLIENTE_NAME,
    FECHACONTAB,
    FECHAVENCIMIENTO,
    FECHACLAVE,
    IND_IMP_CARTERA_TOTAL_MDOC,
    IND_IMP_VENCIDO_030_MDOC,
    IND_IMP_VENCIDO_3160_MDOC,
    IND_IMP_VENCIDO_6190_MDOC,
    IND_IMP_VENCIDO_MAYOR90_MDOC,
    IND_IMP_VENCIDO_TOTAL_MDOC,
    IND_IMP_PORVENCER_030_MDOC,
    IND_IMP_PORVENCER_3160_MDOC,
    IND_IMP_PORVENCER_6190_MDOC,
    IND_IMP_PORVENCER_MAYOR90_MDOC,
    IND_IMP_PORVENCER_TOTAL_MDOC,
    IND_IMP_COBRANZA_MDOC,
    IND_IMP_FACTURAS_MDOC,
    MON_DOC,
    IND_IMP_CARTERA_TOTAL_MSOC,
    IND_IMP_VENCIDO_030_MSOC,
    IND_IMP_VENCIDO_3160_MSOC,
    IND_IMP_VENCIDO_6190_MSOC,
    IND_IMP_VENCIDO_MAYOR90_MSOC,
    IND_IMP_VENCIDO_TOTAL_MSOC,
    IND_IMP_PORVENCER_030_MSOC,
    IND_IMP_PORVENCER_3160_MSOC,
    IND_IMP_PORVENCER_6190_MSOC,
    IND_IMP_PORVENCER_MAYOR90_MSOC,
    IND_IMP_PORVENCER_TOTAL_MSOC,
    IND_IMP_COBRANZA_MSOC,
    IND_IMP_FACTURAS_MSOC,
    MON_SOC,
    IND_IMP_CARTERA_TOTAL_MUSD,
    IND_IMP_VENCIDO_030_MUSD,
    IND_IMP_VENCIDO_3160_MUSD,
    IND_IMP_VENCIDO_6190_MUSD,
    IND_IMP_VENCIDO_MAYOR90_MUSD,
    IND_IMP_VENCIDO_TOTAL_MUSD,
    IND_IMP_PORVENCER_030_MUSD,
    IND_IMP_PORVENCER_3160_MUSD,
    IND_IMP_PORVENCER_6190_MUSD,
    IND_IMP_PORVENCER_MAYOR90_MUSD,
    IND_IMP_PORVENCER_TOTAL_MUSD,
    IND_IMP_COBRANZA_MUSD,
    IND_IMP_FACTURAS_MUSD,
    MON_USD,
    TIPO
) AS 

SELECT *
FROM CON.FCT_FIN_CARTERAACT
WHERE 1=1
    AND SOCIEDAD_ID LIKE 'R%'
    AND CANALDISTRIB_ID IN (SELECT CANALDISTRIB_ID FROM CON.VW_DIM_ORG_CANALDISTRIBUCION)
    AND DESTINATARIO_ID IN (SELECT DESTINATARIO_ID FROM CON.VW_DIM_CLI_DESTINATARIO)
    AND ORGVENTAS_ID IN (SELECT ORGVENTAS_ID FROM CON.VW_DIM_ORG_ORGANIZACIONVENTAS)
    AND SOCIEDAD_ID IN (SELECT SOCIEDAD_ID FROM CON.VW_DIM_ORG_SOCIEDAD)
    AND SOLICITANTE_ID IN (SELECT SOLICITANTE_ID FROM CON.VW_DIM_CLI_SOLICITANTE)

UNION ALL

SELECT *
FROM CON.FCT_FIN_CARTERAHIST
WHERE 1=1
    AND SOCIEDAD_ID LIKE 'R%'
    AND CANALDISTRIB_ID IN (SELECT CANALDISTRIB_ID FROM CON.VW_DIM_ORG_CANALDISTRIBUCION)
    AND DESTINATARIO_ID IN (SELECT DESTINATARIO_ID FROM CON.VW_DIM_CLI_DESTINATARIO)
    AND ORGVENTAS_ID IN (SELECT ORGVENTAS_ID FROM CON.VW_DIM_ORG_ORGANIZACIONVENTAS)
    AND SOCIEDAD_ID IN (SELECT SOCIEDAD_ID FROM CON.VW_DIM_ORG_SOCIEDAD)
    AND SOLICITANTE_ID IN (SELECT SOLICITANTE_ID FROM CON.VW_DIM_CLI_SOLICITANTE)
;
