CREATE OR REPLACE VIEW LAMOSALAKE_DEV.CON.VW_FCT_COM_REV_BACKORDER AS
SELECT *
FROM LAMOSALAKE_DEV.CON.FCT_COM_REV_BACKORDER_ACT

UNION ALL

SELECT *
FROM LAMOSALAKE_DEV.CON.FCT_COM_REV_BACKORDER_FOTO;
