CREATE OR REPLACE VIEW CON.VW_DIM_CLI_SOLICITANTE 
WITH ROW ACCESS POLICY SEGURIDAD.RAP_SAP_DIM_SOLICITANTE_ID ON (GRUPOCLIENTES2_ID) AS

WITH PASO1 AS (
    SELECT
        S.SOLICITANTE_ID,
        S.ORGVENTAS_ID,
        O.ORGVENTAS_TEXT,
        S.CANALDISTRIB_ID,
        C.CANALDISTRIB_TEXT,
        S.SECTOR_ID,
        SE.SECTOR_TEXT,
        S.SOLICITANTE,
        S.SOLICITANTE_TEXT,
        S.GRUPOCLIENTES_ID,
        G.GRUPOCLIENTES_TEXT,
        S.GRUPOCLIENTES1_ID,
        G1.GRUPOCLIENTES1_TEXT, 
        S.GRUPOCLIENTES2_ID,
        G2.GRUPOCLIENTES2_TEXT,
        S.SISORIGEN_ID,
        S.MANDANTE,
        S.FECHA_CARGA,
        S.ZONA_HORARIA
    FROM CON.DIM_CLI_SOLICITANTE S
    LEFT JOIN CON.DIM_ORG_ORGANIZACIONVENTAS O
        ON S.ORGVENTAS_ID = O.ORGVENTAS_ID
    LEFT JOIN CON.DIM_ORG_CANALDISTRIBUCION C
        ON S.CANALDISTRIB_ID = C.CANALDISTRIB_ID
    LEFT JOIN CON.DIM_ORG_SECTOR SE
        ON S.SECTOR_ID = SE.SECTOR_ID
    LEFT JOIN CON.DIM_CLI_GRUPOCLIENTES G
        ON S.GRUPOCLIENTES_ID = G.GRUPOCLIENTES_ID
    LEFT JOIN CON.DIM_CLI_GRUPOCLIENTES1 G1
        ON S.GRUPOCLIENTES1_ID = G1.GRUPOCLIENTES1_ID
    LEFT JOIN CON.DIM_CLI_GRUPOCLIENTES2 G2
        ON S.GRUPOCLIENTES2_ID = G2.GRUPOCLIENTES2_ID


), PASO2 AS (
    SELECT
        NULL	SOLICITANTE_ID,
        '--'	ORGVENTAS_ID,
        '--'	ORGVENTAS_TEXT,
        '--'	CANALDISTRIB_ID,
        '--'	CANALDISTRIB_TEXT,
        '--'	SECTOR_ID,
        '--'	SECTOR_TEXT,
        '--'	SOLICITANTE,
        '--'	SOLICITANTE_TEXT,
        '--'	GRUPOCLIENTES_ID,
        '--'	GRUPOCLIENTES_TEXT,
        '--'	GRUPOCLIENTES1_ID,
        '--'	GRUPOCLIENTES1_TEXT, 
        '--'	GRUPOCLIENTES2_ID,
        '--'	GRUPOCLIENTES2_TEXT,
        '--'	SISORIGEN_ID,
        '--'	MANDANTE,
        CURRENT_TIMESTAMP()  FECHA_CARGA,
        '--'	ZONA_HORARIA


), PASO3 AS (
    SELECT
        ''	    SOLICITANTE_ID,
        '--'	ORGVENTAS_ID,
        '--'	ORGVENTAS_TEXT,
        '--'	CANALDISTRIB_ID,
        '--'	CANALDISTRIB_TEXT,
        '--'	SECTOR_ID,
        '--'	SECTOR_TEXT,
        '--'	SOLICITANTE,
        '--'	SOLICITANTE_TEXT,
        '--'	GRUPOCLIENTES_ID,
        '--'	GRUPOCLIENTES_TEXT,
        '--'	GRUPOCLIENTES1_ID,
        '--'	GRUPOCLIENTES1_TEXT, 
        '--'	GRUPOCLIENTES2_ID,
        '--'	GRUPOCLIENTES2_TEXT,
        '--'	SISORIGEN_ID,
        '--'	MANDANTE,
        CURRENT_TIMESTAMP()  FECHA_CARGA,
        '--'	ZONA_HORARIA


), FINAL AS (
    SELECT * FROM PASO1
    UNION ALL
    SELECT * FROM PASO2
    UNION ALL
    SELECT * FROM PASO3

)

SELECT DISTINCT * FROM FINAL