CREATE OR REPLACE VIEW CON.VW_DIM_CLI_ASESORFACTURA(
    ASESORFACTURA_ID,
    ASESORFACTURA_TEXT,
    FUNCION_INTERLOCUTOR,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  ASESORCOMERCIAL_ID AS ASESORFACTURA_ID,
        ASESORCOMERCIAL_TEXT AS ASESORFACTURA_TEXT,
        FUNCION_INTERLOCUTOR,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM CON.DIM_CLI_ASESORCOMERCIAL;