CREATE OR REPLACE VIEW CON.VW_DIM_CLI_ASESORCOMERCIAL 
WITH ROW ACCESS POLICY SEGURIDAD.RAP_SAP_DIM_ASESORCOMERCIAL_ID ON (ASESORCOMERCIAL_ID)
AS
SELECT
    A.ASESORCOMERCIAL_ID,
    A.FUNCION_INTERLOCUTOR,
    A.ASESORCOMERCIAL_TEXT,
    A.SISORIGEN_ID,
    A.MANDANTE,
    A.FECHA_CARGA,
    A.ZONA_HORARIA
FROM CON.DIM_CLI_ASESORCOMERCIAL A;

