CREATE OR REPLACE VIEW CON.VW_DIM_CLI_DESTINATARIO 
WITH ROW ACCESS POLICY SEGURIDAD.RAP_SAP_DIM_DESTINATARIO_ID ON (COORDINADORDEST_ID, ASESORDEST_ID)
AS
WITH PASO1 AS (
    SELECT
        D.DESTINATARIO_ID,
        D.ORGVENTAS_ID,
        O.ORGVENTAS_TEXT,
        D.CANALDISTRIB_ID,
        C.CANALDISTRIB_TEXT,
        D.SECTOR_ID,
        S.SECTOR_TEXT,
        D.DESTINATARIO,
        D.DESTINATARIO_TEXT,
        D.COORDINADORDEST_ID,
        CD.COORDINADORCOMERCIAL_TEXT,
        D.ASESORDEST_ID,
        A.ASESORCOMERCIAL_TEXT,
        D.SISORIGEN_ID,
        D.MANDANTE,
        D.FECHA_CARGA,
        D.ZONA_HORARIA
    FROM CON.DIM_CLI_DESTINATARIO D
    LEFT JOIN CON.DIM_ORG_ORGANIZACIONVENTAS O --VERIFICAR SI ES QUE YA ESTA HECHA
        ON D.ORGVENTAS_ID = O.ORGVENTAS_ID
    LEFT JOIN CON.DIM_ORG_CANALDISTRIBUCION C
        ON D.CANALDISTRIB_ID = C.CANALDISTRIB_ID
    LEFT JOIN CON.DIM_ORG_SECTOR S
        ON D.SECTOR_ID = S.SECTOR_ID
    LEFT JOIN CON.DIM_CLI_COORDINADORCOMERCIAL CD
        ON D.COORDINADORDEST_ID = CD.COORDINADORCOMERCIAL_ID
    LEFT JOIN CON.DIM_CLI_ASESORCOMERCIAL A
        ON D.ASESORDEST_ID = A.ASESORCOMERCIAL_ID

), PASO2 AS (
   SELECT
        NULL DESTINATARIO_ID,
        '--' ORGVENTAS_ID,
        '--' ORGVENTAS_TEXT,
        '--' CANALDISTRIB_ID,
        '--' CANALDISTRIB_TEXT,
        '--' SECTOR_ID,
        '--' SECTOR_TEXT,
        '--' DESTINATARIO,
        '--' DESTINATARIO_TEXT,
        '--' COORDINADORDEST_ID,
        '--' COORDINADORCOMERCIAL_TEXT,
        '--' ASESORDEST_ID,
        '--' ASESORCOMERCIAL_TEXT,
        '--' SISORIGEN_ID,
        '--' MANDANTE,
        CURRENT_TIMESTAMP() FECHA_CARGA,
        '--' ZONA_HORARIA

), PASO3 AS (
   SELECT
        '' DESTINATARIO_ID,
        '--' ORGVENTAS_ID,
        '--' ORGVENTAS_TEXT,
        '--' CANALDISTRIB_ID,
        '--' CANALDISTRIB_TEXT,
        '--' SECTOR_ID,
        '--' SECTOR_TEXT,
        '--' DESTINATARIO,
        '--' DESTINATARIO_TEXT,
        '--' COORDINADORDEST_ID,
        '--' COORDINADORCOMERCIAL_TEXT,
        '--' ASESORDEST_ID,
        '--' ASESORCOMERCIAL_TEXT,
        '--' SISORIGEN_ID,
        '--' MANDANTE,
        CURRENT_TIMESTAMP() FECHA_CARGA,
        '--' ZONA_HORARIA

), FINAL AS (
    SELECT * FROM PASO1
    UNION ALL
    SELECT * FROM PASO2
    UNION ALL
    SELECT * FROM PASO3
)

SELECT * FROM FINAL