create or replace view CON.VW_DIM_DOC_ORDENFABRICACION (
    ORDENFABRICACION_ID,
    ORDENFABRICACION_TEXT,
    MATERIAL_ID,
    MATERIAL_TEXT,
    SOCIEDAD_ID,
    SOCIEDAD_TEXT,
    CENTRO_ID,
    CENTRO_TEXT,
    SECTOR_ID,
    SECTOR_TEXT,
    CLASEORDFAB_ID,
    CLASEORDFAB_TEXT,
    TIPOORDFAB_ID,
    CLIENTE_ID,
    CLIENTE_TEXT,
    LOTE,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) as
SELECT 
    t.ORDENFABRICACION_ID,
    t.ORDENFABRICACION_TEXT,
    t.MATERIAL_ID,
    d1.MATERIAL_TEXT,
    t.SOCIEDAD_ID,
    d2.SOCIEDAD_TEXT,
    t.CENTRO_ID,
    d3.CENTRO_TEXT,
    t.SECTOR_ID,
    d4.SECTOR_TEXT,
    t.CLASEORDFAB_ID,
    d5.CLASEORDFAB_TEXT,
    t.TIPOORDFAB_ID,
    t.CLIENTE_ID,
    d6.CLIENTE_TEXT,
    t.LOTE,
    t.SISORIGEN_ID,
    t.MANDANTE,
    t.FECHA_CARGA,
    t.ZONA_HORARIA
FROM CON.DIM_DOC_ORDENFABRICACION t 
LEFT JOIN DIM_MAT_MATERIAL d1 ON t.MATERIAL_ID = d1.MATERIAL_ID
LEFT JOIN DIM_ORG_SOCIEDAD d2 ON t.SOCIEDAD_ID = d2.SOCIEDAD_ID
LEFT JOIN DIM_ORG_CENTRO d3 ON t.CENTRO_ID = d3.CENTRO_ID
LEFT JOIN DIM_ORG_SECTOR d4 ON t.SECTOR_ID = d4.SECTOR_ID
LEFT JOIN DIM_DOC_CLASEORDFAB d5 ON t.CLASEORDFAB_ID = d5.CLASEORDFAB_ID
LEFT JOIN DIM_CLI_CLIENTE d6 ON t.CLIENTE_ID = d6.CLIENTE_ID
;

SELECT * FROM CON.VW_DIM_DOC_ORDENFABRICACION;