CREATE OR ALTER TABLE PRE.PDIM_MAT_GRUPOMATERIALES2(		
GRUPOMATERIALES2_ID	VARCHAR(10)	PRIMARY KEY,
GRUPOMATERIALES2_TEXT	VARCHAR(70)	,
SISORIGEN_ID	VARCHAR(4)	,
MANDANTE	VARCHAR(4)	,
FECHA_CARGA	TIMESTAMP_TZ	,
ZONA_HORARIA	VARCHAR(4)	
)		
;