SELECT * FROM SEGURIDAD.SEG_USUARIO_ROLE
ORDER BY USER_NM DESC
;

SELECT * FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE'
ORDER BY ROLE_NM ASC
;
SELECT * FROM SEGURIDAD.SEG_USUARIO_DIMENSION;

SELECT * FROM CON.VW_DIM_ORG_SOCIEDAD;

-- ROLES DEFAULT
INSERT INTO SEGURIDAD.SEG_USUARIO_ROLE
VALUES
-- ('AGUSTIN_GUTIERREZ', 'REV_PEDIDOS_ROLE')
--('AGUSTIN_GUTIERREZ', 'ADH_PEDIDOS_ROLE')
-- ('AGUSTIN_GUTIERREZ', 'ALL_PEDIDOS_ROLE'),
-- ('AGUSTIN_GUTIERREZ', 'SAP_ROLE')
;



-- DELETE ROLES

DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = 'AGUSTIN_GUTIERREZ'
;

INSERT INTO SEGURIDAD.SEG_USUARIO_DIMENSION
VALUES 
('AGUSTIN_GUTIERREZ', 'CENTRO_ID', 'A112');


------------------ DOCU ------------
-- Quitar Permisos (Todo)
DELETE FROM seguridad.seg_role_dimension
WHERE ROLE_NM = 'PEDIDOS_REV_TEST_ROLE' 
AND DIM IN ('CANALDISTRIB_ID', 'CENTRO_ID','OFICINAVENTAS_ID','GRUPOVENDEDORES_ID','UENADHESIVOS_ID')
;

-- Quitar Permisos (MOD)
DELETE FROM seguridad.seg_role_dimension
WHERE ROLE_NM = 'PEDIDOS_REV_TEST_ROLE' 
AND DIM = 'CANALDISTRIB_ID'
;

SELECT CANALDISTRIB_ID, CENTRO_ID, ORGVENTAS_ID, OFICINAVENTAS_ID, GRUPOVENDEDORES_ID, UENADHESIVOS_ID, count(*) as c  FROM CON.FCT_COM_REV_PEDIDOS_ACT
GROUP BY 1,2,3,4,5,6
ORDER BY c desc; 

-- Agregar Permisos
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION
VALUES
-- ('PEDIDOS_REV_TEST_ROLE', 'CANALDISTRIB_ID', ''),
-- ('PEDIDOS_REV_TEST_ROLE', 'CENTRO_ID', 'A126'),
-- ('PEDIDOS_REV_TEST_ROLE', 'ORGVENTAS_ID', 'A112'),
-- ('PEDIDOS_REV_TEST_ROLE', 'OFICINAVENTAS_ID', 'AMX1'),
-- ('PEDIDOS_REV_TEST_ROLE', 'GRUPOVENDEDORES_ID', '001'),
-- ('PEDIDOS_REV_TEST_ROLE', 'UENADHESIVOS_ID', 'AMX2'),
-- ('PEDIDOS_REV_TEST_ROLE', 'CANALDISTRIB_ID', 'ALL'),
-- ('PEDIDOS_REV_TEST_ROLE', 'CENTRO_ID', 'ALL'),
-- ('PEDIDOS_REV_TEST_ROLE', 'ORGVENTAS_ID', 'ALL'),
-- ('PEDIDOS_REV_TEST_ROLE', 'OFICINAVENTAS_ID', 'ALL'),
-- ('PEDIDOS_REV_TEST_ROLE', 'GRUPOVENDEDORES_ID', 'ALL')
('PEDIDOS_REV_TEST_ROLE', 'SOCIEDAD_ID', 'ALL')
;

-- Verificación de rol para el uso de las pruebas
insert into SEGURIDAD.SEG_USUARIO_ROLE 
    (USER_NM,
    ROLE_NM)
    values
    ('AGUSTIN_GUTIERREZ','PEDIDOS_REV_TEST_ROLE');


-- Prueba con una organización

INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'ORGVENTAS_ID', 'R311');
SELECT DISTINCT ORGVENTAS_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con todas las organizaciones
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'ORGVENTAS_ID', 'ALL');
SELECT DISTINCT ORGVENTAS_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con un centro
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'CENTRO_ID', 'R107');
SELECT DISTINCT CENTRO_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con todos los centros
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'CENTRO_ID', 'ALL');
SELECT DISTINCT CENTRO_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con una oficina de ventas
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'OFICINAVENTAS_ID', 'RME2');
SELECT DISTINCT OFICINAVENTAS_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con todas las oficinas
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'OFICINAVENTAS_ID', 'ALL');
SELECT DISTINCT OFICINAVENTAS_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'GRUPOVENDEDORES_ID', '001');

-- Prueba con un grupo de vendedores
SELECT DISTINCT GRUPOVENDEDORES_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con todos los grupos
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'GRUPOVENDEDORES_ID', 'ALL');
SELECT DISTINCT GRUPOVENDEDORES_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con un canal de distrubución
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'CANALDISTRIB_ID', 'NA');
SELECT DISTINCT CANALDISTRIB_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;

-- Prueba con todos los canales
INSERT INTO seguridad.seg_role_dimension (ROLE_NM, DIM, VALOR) VALUES ('PEDIDOS_REV_TEST_ROLE', 'CANALDISTRIB_ID', 'ALL');
SELECT DISTINCT CANALDISTRIB_ID FROM CON.VW_FCT_COM_REV_PEDIDOS;
