SELECT * FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'ZBWFI_REP_ANTSALDET'
AND NEGOCIO = 'ADH_GUATEMALA' AND PARAMETRO = 'BUDAT';

UPDATE RAW.PARAMETROS_EXTRACCION
SET R_FIN = '20250812'
WHERE EXTRACTOR = 'ZBWFI_REP_ANTSALDET'
AND PARAMETRO = 'BUDAT';

SELECT SOCIEDAD_ID, MON_DOC, SUM(IND_IMP_COBRANZA_MDOC), SUM(IND_IMP_FACTURAS_MDOC)
FROM CON.VW_FCT_FIN_ADH_CARTERA
WHERE FECHACLAVE = '2025-07-31'
group by SOCIEDAD_ID, MON_DOC
order by 1,2
;

SELECT SOCIEDAD_ID, MON_DOC, SUM(IND_IMP_COBRANZA_MDOC), SUM (IND_IMP_FACTURAS_MDOC)
FROM MIRRORING.VW_FCT_FIN_ADH_CARTERA
where FECHACLAVE = '2025-07-31'
group by SOCIEDAD_ID, MON_DOC
order by 1,2
;

SELECT DISTINCT FECHACLAVE FROM CON.FCT_FIN_CARTERAACT;

DELETE FROM CON.FCT_FIN_CARTERAACT;

SELECT * FROM LOGS.HISTORIAL_EJECUCIONES
ORDER BY FECHA_HORA_INICIO DESC;

SELECT FECHACLAVE, count(*) FROM CON.FCT_FIN_CARTERAACT
GROUP BY 1;

SELECT
    MON_DOC AS MONEDA,
    SUM(IND_IMP_CARTERA_TOTAL_MDOC) AS CARTERA_TOTAL
FROM
    CON.FCT_FIN_CARTERAACT
WHERE FECHACLAVE = '2025-08-11'
GROUP BY 1; //MXN	392362107.34 - USD	3407142.4

SELECT
    MON_DOC AS MONEDA,
    SUM(IND_IMP_CARTERA_TOTAL_MDOC) AS CARTERA_TOTAL
FROM
    CON.VW_FCT_FIN_ADH_CARTERA
WHERE FECHACLAVE = '2025-08-11'
GROUP BY 1; //MXN	392362107.34 - USD	3407142.4

SELECT
    MON_DOC AS MONEDA,
    SUM(IND_IMP_CARTERA_TOTAL_MDOC) AS CARTERA_TOTAL
FROM
    MIRRORING.FCT_FIN_ADH_CARTERA
WHERE FECHACLAVE = '2025-08-11'
GROUP BY 1; 

SELECT 'M' as MODELO, FECHACLAVE, SOCIEDAD_ID, count(*) FROM MIRRORING.FCT_FIN_ADH_CARTERA
WHERE FECHACLAVE = '2025-08-12'
GROUP BY 1, 2, 3
UNION ALL
SELECT 'C' AS MODELO, FECHACLAVE, SOCIEDAD_ID, count(*) FROM CON.FCT_FIN_CARTERAACT
GROUP BY 1, 2, 3 ; // 40295 ADH MEX
SELECT 'C' AS MODELO, FECHACLAVE, count(*) FROM CON.FCT_FIN_CARTERAACT
WHERE SOCIEDAD_ID IN ('A101', 'A102', 'A103')
GROUP BY 1, 2 ;

SELECT FECHA_CLAVE, count(*) FROM PRE.PFCT_FIN_CARTERAACT
GROUP BY 1;


SELECT DISTINCT FECHACLAVE, SOCIEDAD_ID, METADATA$ACTION, count(*) FROM MIRRORING.TR_FCT_FIN_ADH_CARTERA
GROUP BY 1,2,3;

DELETE FROM CON.FCT_FIN_CARTERAACT
WHERE FECHACLAVE = '2025-08-12';

DELETE FROM MIRRORING.FCT_FIN_ADH_CARTERA
WHERE FECHACLAVE = '2025-08-11';

CALL CON.SP_CON_FACT_CARTERAACT('202508');

CALL MIRRORING.SP_ACTUALIZAR_CALENDARIO('FCT_FIN_ADH_CARTERA', 'DIM_CAL_ADH_CARTERA', 'FECHACLAVE');

SELECT * FROM MIRRORING.DIM_CAL_ADH_CARTERA;

DELETE FROM MIRRORING.DIM_CAL_ADH_CARTERA;

SELECT * FROM MIRRORING.STREAM_DIM_CAL_ADH_CARTERA;