UPDATE CON.FCT_LOG_ADH_INVENTARIO_ACT
SET CENTRO_ID = 'R999' WHERE CENTRO_ID = 'R100';

SELECT * FROM MIRRORING.STREAM_VW_FCT_LOG_ADH_INVENTARIO;
SELECT * FROM MIRRORING.TR_FCT_LOG_ADH_INVENTARIO;

SELECT count(*) FROM MIRRORING.DIM_MAT_MATERIAL_ADH;

SELECT
    SUM(IND_)
FROM CON.FCT_LOG_ADH_INVENTARIO_FOTO
WHERE FECHA_FOTO_INVENTARIO = '20250430';
SELECT DISTINCT FECHA_FOTO_INVENTARIO FROM CON.FCT_LOG_ADH_INVENTARIO_ACT;

SELECT
    FECHA_FOTO_INVENTARIO,
    UNI_EST,
    IND_INVENTARIO_FISICO_EST,
    UNI_UMB,
    IND_INVENTARIO_FISICO_UMB
FROM PRE.PFCT_LOG_INVENTARIO
WHERE MATERIAL_ID = '3020-13GR-SA10';

SELECT
    FECHA_FOTO_INVENTARIO,
    UNI_EST,
    IND_INVENTARIO_FISICO_TON,
    UNI_UMB,
    IND_INVENTARIO_FISICO_UMB
FROM CON.FCT_LOG_ADH_INVENTARIO_ACT
WHERE MATERIAL_ID = '3020-13GR-SA10';

SELECT DISTINCT MEINH FROM RAW.SQ1_EXT_0MAT_UNIT_ATTR LIMIT 10;
DELETE FROM CON.FCT_LOG_ADH_INVENTARIO_ACT;
SELECT DISTINCT FECHA FROM RAW.SQ1_MOF_ZMM_INVENTARIO;

CALL CON.SP_CON_FCT_LOG_ADH_INVENTARIO_ACT();

CALL PRE.SP_PRE_PFCT_LOG_INVENTARIO();

SELECT count(*) FROM RAW.SQ1_MOF_ZMM_INVENTARIO;// 167

SELECT count(*) FROM PRE.PFCT_LOG_INVENTARIO; //135
SELECT * FROM CON.FCT_LOG_ADH_INVENTARIO_ACT
WHERE MATERIAL_ID IS NULL; // 135
SELECT count(*) FROM CON.FCT_LOG_ADH_INVENTARIO_ACT
BEFORE (STATEMENT => '01bdc693-030e-1c98-0003-72e304f97076')
-- GROUP BY TIPOMATERIAL_ID
; // completo 2152



SELECT
    DISTINCT MATERIAL
FROM RAW.SQ1_MOF_ZMM_INVENTARIO Z
        LEFT JOIN (SELECT *
                    from
                    (SELECT MEINH,MATNR,UMREZ,UMREN,
                    CASE    WHEN MEINH='TO' THEN 1
                            WHEN MEINH='M2' THEN 2
                            WHEN MEINH='KG' THEN 3
                            ELSE 9 END AS JERARQUIA,
                    ROW_NUMBER () OVER (PARTITION BY MATNR  ORDER BY JERARQUIA ASC) AS ROW_NUMBER
                    FROM RAW.SQ1_EXT_0MAT_UNIT_ATTR
                    ORDER BY JERARQUIA)
                    WHERE ROW_NUMBER =1) MAT
WHERE MAT.MATNR = ''
    ;
SELECT * FROM MIRRORING.DIM_MAT_MATERIALVENTAS;


---------------------------------
