CREATE OR ALTER TABLE CON.DIM_FIN_CUENTAMAYOR(
    CUENTAMAYOR_ID VARCHAR(15),
	CUENTAMAYOR VARCHAR(10),
	CUENTAMAYOR_TEXT VARCHAR(50),
	PLANCUENTAS_ID VARCHAR(4),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);