create or replace TABLE PRE.PDIM_ABA_GRUPOCOMPRAS (
	GRUPOCOMPRAS_ID VARCHAR(3),
	GRUPOCOMPRAS_TEXT VARCHAR(18),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);