create or replace TABLE PRE.PDIM_ABA_ORGCOMPRAS (
	ORGCOMPRAS_ID VARCHAR(4),
	ORGCOMPRAS_TEXT VARCHAR(20),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);