create or replace TABLE PRE.PDIM_ABA_TASACAMBIO (
	KURST VARCHAR(4),
	FCURR VARCHAR(5),
	TCURR VARCHAR(5),
	GDATU DATE,
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	ZONA_HORARIA VARCHAR(10),
	FECHA_CARGA VARCHAR(20),
	RATE NUMBER(25,12),
	FFACT NUMBER(10,0),
	TFACT NUMBER(10,0)
);