-- Este archivo pertenece a DIM_CLI_COORDINADORCOMERCIAL



CREATE OR REPLACE TABLE CON.DIM_CLI_COORDINADORCOMERCIAL (
    COORDINADORCOMERCIAL_ID VARCHAR,
    FUNCION_INTERLOCUTOR VARCHAR,
    COORDINADORCOMERCIAL_TEXT VARCHAR,
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

