-- Este archivo pertenece a DIM_CLI_GRUPOSOLICITANTE



CREATE OR REPLACE TABLE CON.DIM_CLI_GRUPOSOLICITANTE (
    GRUPOCUENTAS_ID VARCHAR(4),
    GRUPOSOLICITANTE_ID VARCHAR(10),
    GRUPOSOLICITANTE_TEXT VARCHAR(50),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);


