-- Este archivo pertenece a DIM_CLI_GRUPOCLIENTES4


CREATE OR REPLACE TABLE CON.DIM_CLI_GRUPOCLIENTES4 (
    GRUPOCLIENTES4_ID VARCHAR(3),
    GRUPOCLIENTES4_TEXT VARCHAR(20),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

