create or replace TABLE CON.DIM_ABA_GRUPOPROVEEDOR (
	GRUPOPROVEEDOR_ID VARCHAR(10),
	GRUPOPROVEEDOR_TEXT VARCHAR(50),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);