create or replace TABLE CON.DIM_ABA_PROVEEDOR (
	PROVEEDOR_ID VARCHAR(10),
	PROVEEDOR_TEXT VARCHAR(35),
	GRUPOCUENTASPROV_ID VARCHAR(4),
	GRUPOPROVEEDOR_ID VARCHAR(10),
	PAIS_ID VARCHAR(3),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(4),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(12)
);