CREATE OR ALTER TABLE PRE.PDIM_FIN_VERSION(
    VERSION_ID VARCHAR(3),
	VERSION_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);