CREATE OR ALTER TABLE PRE.PDIM_FIN_POSICIONPRES(
    POSICIONPRES_ID VARCHAR(29),
	POSICIONPRES VARCHAR(24),
	POSICIONPRES_TEXT VARCHAR(60),
	ENTIDADCP_ID VARCHAR(4),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);

