-- Este archivo pertenece a DIM_CLI_GRUPOCLIENTES



CREATE OR REPLACE TABLE CON.DIM_CLI_GRUPOCLIENTES (
    GRUPOCLIENTES_ID VARCHAR(2),
    GRUPOCLIENTES_TEXT VARCHAR(20),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);
