-- Este archivo pertenece a DIM_CLI_SOLICITANTE



CREATE OR REPLACE TABLE CON.DIM_CLI_SOLICITANTE (
    SOLICITANTE_ID VARCHAR(50),
    SOLICITANTE VARCHAR(10),
    ORGVENTAS_ID VARCHAR(4),
    CANALDISTRIB_ID VARCHAR(2),
    SECTOR_ID VARCHAR(2),
    GRUPOCLIENTES_ID VARCHAR(2),
    ZONAVENTAS_ID VARCHAR(6),
    GRUPOVENDEDORES_ID VARCHAR(3),
    OFICINAVENTAS_ID VARCHAR(4),
    GRUPOCLIENTES1_ID VARCHAR(3),
    GRUPOCLIENTES2_ID VARCHAR(3),
    GRUPOCLIENTES3_ID VARCHAR(3),
    GRUPOCLIENTES4_ID VARCHAR(3),
    GRUPOCLIENTES5_ID VARCHAR(3),
    GRUPOIMPUTCLIENTE_ID VARCHAR(2),
    INDICADOR_ABC_ID VARCHAR(2),
    SOLICITANTE_TEXT VARCHAR(35),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

