-- Este archivo pertenece a DIM_CLI_GRUPOCLIENTES1



CREATE OR REPLACE TABLE CON.DIM_CLI_GRUPOCLIENTES1 (
    GRUPOCLIENTES1_ID VARCHAR(3),
    GRUPOCLIENTES1_TEXT VARCHAR(20),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

