-- Este archivo pertenece a DIM_CLI_GRUPOCLIENTES3



CREATE OR ALTER TABLE CON.DIM_CLI_GRUPOCLIENTES3 (
    GRUPOCLIENTES3_ID VARCHAR(3),
    GRUPOCLIENTES3_TEXT VARCHAR(20),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

