CREATE OR ALTER TABLE CON.DIM_FIN_CATEGORIAPRES(
    CATEGORIAPRES_ID VARCHAR(60),
	CATEGORIAPRES_TEXT VARCHAR(60),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);