CREATE OR ALTER TABLE CON.DIM_FIN_GRUPOCREDCLIENTE(
    GRUPOCREDCLIENTE_ID VARCHAR(9),
	GRUPOCREDCLIENTE VARCHAR(4),
	GRUPOCREDCLIENTE_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);