create or replace TABLE PRE.PDIM_DOC_CLASEORDFAB (
CLASEORDFAB_ID	VARCHAR PRIMARY KEY,
CLASEORDFAB_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

create or replace TABLE CON.DIM_DOC_CLASEORDFAB (
CLASEORDFAB_ID	VARCHAR PRIMARY KEY,
CLASEORDFAB_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);