SELECT DISTINCT ENCARGADO_CC_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO;

SELECT  ZZENC_CC AS "ENCARGADO_CC_ID",
        ZZENC_CC_DES AS "ENCARGADO_CC_TEXT",
        ZZENC_GC AS "ENCARGADO_GERENCIA_ID",
        ZZENC_GC_DES AS "ENCARGADO_GERENCIA_TEXT",
        ZZENC_DC AS "ENCARGADO_DIRECCION_ID",
        ZZENC_DC_DES AS "ENCARGADO_DIRECCION_TEXT"
FROM RAW.SQ1_EXT_ZCSKS;


SELECT *
FROM RAW.SQ1_EXT_ZSTXH
WHERE TDID LIKE 'Z%'
AND TRY_TO_NUMBER(TEXTO) IS NOT NULL;

SELECT *
FROM RAW.SQ1_EXT_ZSTXH
WHERE TDNAME = 'ZSUB';

--GASTOER, SOCIEDADGLASOC, CUENTA (Filtro para la Subdivision)



SELECT *
FROM RAW.SQ1_EXT_0RISK_CATEG_TEXT
WHERE SPRAS = 'S';



SELECT * FROM MIRRORING.TR_FCT_FIN_ADH_CARTERA;