SELECT DISTINCT ENCARGADO_CC_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO;

SELECT  ZZENC_CC AS "ENCARGADO_CC_ID",
        ZZENC_CC_DES AS "ENCARGADO_CC_TEXT",
        ZZENC_GC AS "ENCARGADO_GERENCIA_ID",
        ZZENC_GC_DES AS "ENCARGADO_GERENCIA_TEXT",
        ZZENC_DC AS "ENCARGADO_DIRECCION_ID",
        ZZENC_DC_DES AS "ENCARGADO_DIRECCION_TEXT"
FROM RAW.SQ1_EXT_ZCSKS;


SELECT *
FROM RAW.SQ1_EXT_ZSTXH
WHERE TDID LIKE 'Z%'
AND TRY_TO_NUMBER(TEXTO) IS NOT NULL;

SELECT *
FROM RAW.SQ1_EXT_ZSTXH
WHERE TDNAME = 'ZSUB';

--GASTOER, SOCIEDADGLASOC, CUENTA (Filtro para la Subdivision)



SELECT *
FROM RAW.SQ1_EXT_0RISK_CATEG_TEXT
WHERE SPRAS = 'S';



SELECT * FROM MIRRORING.TR_FCT_FIN_ADH_CARTERA;



DROP TABLE RAW.SQ1_EXT_0C_CTR_AREA_TEXT;
DROP TABLE RAW.SQ1_EXT_0FM_BUCAT_TEXT;
DROP TABLE RAW.SQ1_EXT_0COSTCENTER_ATTR;
DROP TABLE RAW.SQ1_EXT_0COSTCENTER_TEXT;
DROP TABLE RAW.SQ1_EXT_ZCSKS;
DROP TABLE RAW.SQ1_EXT_0FUNDS_CTR_ATTR;
DROP TABLE RAW.SQ1_EXT_0FUNDS_CTR_TEXT;
DROP TABLE RAW.SQ1_EXT_0AC_DOC_TYP_TEXT;
DROP TABLE RAW.SQ1_EXT_0RISK_CATEG_TEXT;
DROP TABLE RAW.SQ1_EXT_0COSTELMNT_TEXT;
DROP TABLE RAW.SQ1_EXT_ZSTXH;
DROP TABLE RAW.SQ1_EXT_0GL_ACCOUNT_ATTR;
DROP TABLE RAW.SQ1_EXT_0GL_ACCOUNT_TEXT;
DROP TABLE RAW.SQ1_EXT_0FM_ACTDETL_TEXT;
DROP TABLE RAW.SQ1_EXT_0FM_AREA_ATTR;
DROP TABLE RAW.SQ1_EXT_0FM_AREA_TEXT;
DROP TABLE RAW.SQ1_EXT_0REPR_GROUP_TEXT;
DROP TABLE RAW.SQ1_EXT_0CRED_GROUP_TEXT;
DROP TABLE RAW.SQ1_EXT_0CMMT_ITEM_PU_ATTR;
DROP TABLE RAW.SQ1_EXT_0CMMT_ITEM_PU_TEXT;
DROP TABLE RAW.SQ1_EXT_0PU_MEASURE_ATTR;
DROP TABLE RAW.SQ1_EXT_0PU_MEASURE_TEXT;
DROP TABLE RAW.SQ1_EXT_0VERSION_TEXT;
DROP TABLE RAW.SQ1_EXT_0CO_AREA_ATTR;
DROP TABLE RAW.SQ1_EXT_0CO_AREA_TEXT;