SELECT * FROM MIRRORING.DIM_FIN_ENTIDADCP;
SELECT * FROM MIRRORING.DIM_FIN_SOCIEDADCO;
SELECT * FROM MIRRORING.DIM_FIN_CENTROCOSTO;
SELECT * FROM MIRRORING.DIM_FIN_CENTROGESTOR;
SELECT * FROM MIRRORING.DIM_FIN_CUENTA;
SELECT * FROM MIRRORING.DIM_FIN_SOCIEDADGLASOC;
SELECT * FROM MIRRORING.DIM_FIN_VERSION;
SELECT * FROM MIRRORING.DIM_FIN_GASTOER;
SELECT * FROM MIRRORING.DIM_FIN_ACREEDOR;
SELECT * FROM MIRRORING.DIM_FIN_PROGRAMAPRES;
SELECT * FROM MIRRORING.DIM_FIN_DETALLECOMPREAL;
SELECT * FROM MIRRORING.DIM_FIN_POSICIONPRES;
SELECT * FROM MIRRORING.DIM_FIN_CATEGORIAPRES;
SELECT * FROM MIRRORING.DIM_CAL_GASTOSCONTROLPRES;


SELECT * FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES;
SELECT * FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
DESC TABLE MIRRORING.FCT_FIN_GASTOSCONTROLPRES;


SELECT COUNT(*) FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;



SELECT R_INICIO, R_FIN
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0PU_IS_PS_31-43'
AND NEGOCIO = 'CONTROL_PRESUPUESTAL';

SELECT R_INICIO, R_FIN
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';