
--------- CARTERA REAL RAW

SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025002';
SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER BETWEEN '2025001' AND '2025004';
SELECT *
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER BETWEEN '2025001' AND '2025004'
--AND KSTAR BETWEEN '5100000000' AND '6199999999'
GROUP BY ALL;
SELECT WAERS, SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025004'
GROUP BY WAERS;

SELECT  "MON_SOC",
        SUM("IND_IMPORTE_GTOREAL_SOC"),
        SUM("IND_IMPORTE_GTOREAL_MXN"),
        SUM("IND_IMPORTE_GTOREAL_USD")
FROM CON.FCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
GROUP BY "MON_SOC";




SELECT  'RAW' AS "CAPA",
        CURTYPE,
        WAERS,
        SUM(IFF(CURTYPE = '10', SWG, 0)) AS "IND_IMPORTE_GTOREAL_SOC",
        SUM(IFF(CURTYPE = '20', SWG, 0)) AS "IND_IMPORTE_GTOREAL_MXN",
        SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE CURTYPE != '00'
AND "FISCPER" BETWEEN '2025001' AND '2025004'
-- CUENTA 5220110001
GROUP BY ALL

UNION ALL

SELECT  'PRE' AS "CAPA",
        "TIPO_MONEDA",
        MON_MXN,
        SUM("IND_IMPORTE_GTOREAL_SOC") AS "IND_IMPORTE_GTOREAL_SOC",
        SUM("IND_IMPORTE_GTOREAL_MXN") AS "IND_IMPORTE_GTOREAL_MXN",
        SUM("IND_IMPORTE_GTOREAL_USD") AS "IND_IMPORTE_GTOREAL_USD"
FROM PRE.PFCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL

UNION ALL

SELECT  'CON' AS "CAPA",
        "TIPO_MONEDA",
        MON_MXN,
        SUM("IND_IMPORTE_GTOREAL_SOC") AS "IND_IMPORTE_GTOREAL_SOC",
        SUM("IND_IMPORTE_GTOREAL_MXN") AS "IND_IMPORTE_GTOREAL_MXN",
        SUM("IND_IMPORTE_GTOREAL_USD") AS "IND_IMPORTE_GTOREAL_USD"
FROM CON.FCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL
;


SELECT COUNT(*)
FROM (SELECT
            'Real' AS "TIPO",
            BUKRS AS "SOCIEDAD_ID",
            WERKS AS "CENTRO_ID",
            KOKRS AS "SOCIEDADCO_ID",
            KTOPL AS "PLANCUENTAS_ID",
            CCA_9.KOSTL AS "CENTROCOSTO_ID",
            KSTAR AS "CUENTA_ID",
            SAKNR AS "CUENTAMAYOR_ID",
            SUBSTR(FISCPER, 0, 4) AS "ANIO",
            SUBSTR(FISCPER, 6, 2) AS "MES",
            CONCAT(SUBSTR(FISCPER, 0, 4), SUBSTR(FISCPER, 6, 2)) AS "ANIOMES",
            BUDAT AS "FECHA_FECHA",
            '' AS "VERSION_ID",
            ZZVBUND AS "SOCIEDADGLASOC_ID",
            LIFNR AS "ACREEDOR_ID",
            'ZTPOGASTO' AS "TIPOGASTO_ID",
            "CURTYPE" AS "TIPO_MONEDA",

            --IFF(LTRIM(COSTE.SUBDIVISION_ID,'0') = '8', '08', IFF(LTRIM(COSTE.SUBDIVISION_ID,'0') = '25', '09', TIPOGASTO_ID)) AS "GASTOER_ID",
            '' AS "GASTOER_ID",
            
            0 AS "IND_IMPORTE_GTOPRESUP_SOC",
            SUM(IFF(CURTYPE = '10', SWG, 0)) AS "IND_IMPORTE_GTOREAL_SOC",
            WAERS AS "MON_SOC",

            0 AS "IND_IMPORTE_GTOPRESUP_MXN",
            SUM(IFF(CURTYPE = '20', SWG, 0)) AS "IND_IMPORTE_GTOREAL_MXN",
            WAERS AS "MON_MXN",

            0 AS "IND_IMPORTE_GTOPRESUP_USD",
            SUM(IFNULL(IFF(CURTYPE = '20', SWG * TCUR.RATE, 0), 0))  AS "IND_IMPORTE_GTOREAL_USD",
            'USD' AS "MON_USD",

            CURRENT_TIMESTAMP AS "FECHA_ACTUALIZACION",
            0 AS "IND_IMPORTE_GTOPRESUPV0_SOC",
            0 AS "IND_IMPORTE_GTOPRESUPV1_SOC",
            0 AS "IND_IMPORTE_GTOPRESUPV2_SOC",
            0 AS "IND_IMPORTE_GTOPRESUPV3_SOC",
            0 AS "IND_IMPORTE_GTOPRESUPV0_MXN",
            0 AS "IND_IMPORTE_GTOPRESUPV1_MXN",
            0 AS "IND_IMPORTE_GTOPRESUPV2_MXN",
            0 AS "IND_IMPORTE_GTOPRESUPV3_MXN",
            0 AS "IND_IMPORTE_GTOPRESUPV0_USD",
            0 AS "IND_IMPORTE_GTOPRESUPV1_USD",
            0 AS "IND_IMPORTE_GTOPRESUPV2_USD",
            0 AS "IND_IMPORTE_GTOPRESUPV3_USD",
            CCA_9.MANDANTE AS "MANDANTE",
            CCA_9.SISORIGEN_ID AS "SISORIGEN_ID",
            CCA_9.FECHA_CARGA AS "FECHA_CARGA",
            CCA_9.ZONA_HORARIA "ZONA_HORARIA"
        FROM RAW.SQ1_EXT_0CO_OM_CCA_9 AS CCA_9
        
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
        ON CECO.CENTROCOSTO_ID = CCA_9.KOSTL

        LEFT JOIN PRE.PDIM_FIN_CUENTA AS CUENTA
		ON LTRIM(CCA_9.KSTAR,'0') = LTRIM(CUENTA.CUENTA_ID,'0')

        LEFT JOIN PRE.PDIM_ABA_TASACAMBIO AS TCUR
        ON KURST = 'M' AND FCURR = WAERS AND TCURR = 'USD' AND GDATU = BLDAT
        
        WHERE BUKRS BETWEEN 'A000' AND 'R999'
        AND CURTYPE IN ('10', '20')
        --AND KSTAR BETWEEN '5100000000' AND '6199999999'
        AND FISCPER BETWEEN '2025001' AND '2025004'

        GROUP BY ALL
);

SELECT  'RAW' AS "CAPA",
        COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE "FISCPER" BETWEEN '2025001' AND '2025004'
-- CUENTA 5220110001
GROUP BY ALL

UNION ALL

SELECT  'PRE' AS "CAPA",
        COUNT(*)
FROM PRE.PFCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL

UNION ALL

SELECT  'CON' AS "CAPA",
        COUNT(*)
FROM CON.FCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL
;








SELECT  'RAW' AS "CAPA",
        CURTYPE,
        WAERS,
        SUM(IFF(CURTYPE = '10', SWG, 0)) AS "IND_IMPORTE_GTOREAL_SOC",
        SUM(IFF(CURTYPE = '20', SWG, 0)) AS "IND_IMPORTE_GTOREAL_MXN",
        SUM(SWG) AS "IND_IMPORTE_GTOREAL_USD"
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE CURTYPE != '00'
AND "FISCPER" BETWEEN '2025001' AND '2025004'
GROUP BY ALL

UNION ALL

SELECT  'PRE' AS "CAPA",
        TIPO_MONEDA,
        MON_MXN,
        SUM("IND_IMPORTE_GTOREAL_SOC") AS "IND_IMPORTE_GTOREAL_SOC",
        SUM("IND_IMPORTE_GTOREAL_MXN") AS "IND_IMPORTE_GTOREAL_MXN",
        SUM("IND_IMPORTE_GTOREAL_USD") AS "IND_IMPORTE_GTOREAL_USD"
FROM PRE.PFCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
GROUP BY ALL

UNION ALL

SELECT  'CON' AS "CAPA",
        TIPO_MONEDA,
        MON_MXN,
        SUM("IND_IMPORTE_GTOREAL_SOC") AS "IND_IMPORTE_GTOREAL_SOC",
        SUM("IND_IMPORTE_GTOREAL_MXN") AS "IND_IMPORTE_GTOREAL_MXN",
        SUM("IND_IMPORTE_GTOREAL_USD") AS "IND_IMPORTE_GTOREAL_USD"
FROM CON.FCT_FIN_GASTOSREAL
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
GROUP BY ALL;


SELECT  'PRE',
        TIPO_MONEDA,
        SUM("IND_IMPORTE_GTOREAL_SOC") AS "IND_IMPORTE_GTOREAL_SOC",
        SUM("IND_IMPORTE_GTOREAL_MXN") AS "IND_IMPORTE_GTOREAL_MXN",
        SUM("IND_IMPORTE_GTOREAL_USD") AS "IND_IMPORTE_GTOREAL_USD"
FROM PRE.PFCT_FIN_GASTOSPRESUPUESTO
WHERE "ANIOMES" = '202501'
AND "CENTROCOSTO_ID" = 'A002030052'
GROUP BY ALL;



SELECT  'RAW',
        CURTYPE,
        SUM(IFF(CURTYPE = '10', SWG, 0)) AS "IND_IMPORTE_GTOREAL_SOC",
        SUM(IFF(CURTYPE = '20', SWG, 0)) AS "IND_IMPORTE_GTOREAL_MXN",
        SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE "FISCPER" = '2025004'
GROUP BY ALL;



SELECT  *
FROM PRE.PFCT_FIN_GASTOSREAL;









--------- CARTERA PRESUPUESTO RAW


SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER BETWEEN '2025001' AND '2025004';
SELECT COUNT(*)
FROM RAW.PRUEBA_GASTOS_PRES
WHERE FISCPER BETWEEN '2025001' AND '2025004';
SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER = '2025002';
SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER = '2025003';
SELECT *, COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER = '2025002'
AND VTYPE = '040'
AND WAERS = 'MXN'
GROUP BY ALL;
SELECT DISTINCT KSTAR, COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER = '2025002'
AND VTYPE = '040'
AND WAERS = 'MXN'
GROUP BY ALL;


DELETE FROM RAW.SQ1_EXT_0CO_OM_CCA_1;
SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1;
SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER BETWEEN '2025001' AND '2025003';


--395.263
--395.370

--35.854
--35.911


--35.914

DROP TABLE RAW.PRUEBA_GASTOS_PRES;
SELECT COUNT(*)
FROM RAW.PRUEBA_GASTOS_PRES;
SELECT SUM(SWG)
FROM RAW.PRUEBA_GASTOS_PRES;

SELECT *
FROM "RAW"."PARAMETROS_EXTRACCION";

WHERE EXTRACTOR = 'ZBWFI_REP_ANTSALDET'
AND NEGOCIO = 'REV_MEX';




SELECT  'RAW' AS "CAPA",
        CURTYPE,
        WAERS,
        SUM(IFF(CURTYPE = '10', SWG, 0)) AS "IND_IMPORTE_GTOPRESUP_SOC",
        SUM(IFF(CURTYPE = '20', SWG, 0)) AS "IND_IMPORTE_GTOPRESUP_MXN",
        SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE CURTYPE != '00'
AND VERSN = '000'
AND "FISCPER" BETWEEN '2025001' AND '2025004'
--AND SEKNZ = 'S'
-- CUENTA 5220110001
GROUP BY ALL

UNION ALL

SELECT  'PRE' AS "CAPA",
        "TIPO_MONEDA",
        MON_MXN,
        SUM("IND_IMPORTE_GTOPRESUP_SOC") AS "IND_IMPORTE_GTOPRESUP_SOC",
        SUM("IND_IMPORTE_GTOPRESUP_MXN") AS "IND_IMPORTE_GTOPRESUP_MXN",
        SUM("IND_IMPORTE_GTOPRESUP_USD") AS "IND_IMPORTE_GTOPRESUP_USD"
FROM PRE.PFCT_FIN_GASTOSPRESUPUESTO
WHERE VERSION_ID = '000'
AND "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL

UNION ALL

SELECT  'CON' AS "CAPA",
        "TIPO_MONEDA",
        MON_MXN,
        SUM("IND_IMPORTE_GTOPRESUP_SOC") AS "IND_IMPORTE_GTOPRESUP_SOC",
        SUM("IND_IMPORTE_GTOPRESUP_MXN") AS "IND_IMPORTE_GTOPRESUP_MXN",
        SUM("IND_IMPORTE_GTOPRESUP_USD") AS "IND_IMPORTE_GTOPRESUP_USD"
FROM CON.FCT_FIN_GASTOSPRESUPUESTO
WHERE VERSION_ID = '000'
AND "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL
;





SELECT  'RAW' AS "CAPA",
        COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE "FISCPER" BETWEEN '2025001' AND '2025004'
-- CUENTA 5220110001
GROUP BY ALL

UNION ALL

SELECT  'PRE' AS "CAPA",
        COUNT(*)
FROM PRE.PFCT_FIN_GASTOSPRESUPUESTO
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL

UNION ALL

SELECT  'CON' AS "CAPA",
        COUNT(*)
FROM CON.FCT_FIN_GASTOSPRESUPUESTO
WHERE "ANIOMES" BETWEEN '202501' AND '202504'
--AND "CENTROCOSTO_ID" = 'A402041320'
GROUP BY ALL
;




-- VISTA FINAL

SELECT  SUM(IND_IMPORTE_GTOPRESUP_SOC),
        SUM(IND_IMPORTE_GTOREAL_SOC)
FROM CON.VW_FCT_FIN_GASTOS
WHERE CENTROCOSTO_ID = 'A002040091'
AND ANIOMES BETWEEN '202501' AND '202504';



--------------------------------------

SELECT *
FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9';

INSERT INTO RAW.PARAMETROS_EXTRACCION
        (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES  (3, 'SQ1_EXT_0CO_OM_CCA_9', 'GASTOS', 'FISCPER', '2025001', '2025005');


SELECT  SOCIEDAD_ID,
        SOCIEDADCO_ID,
        CENTROCOSTO_ID,
        CUENTA_ID,
        ANIOMES,
        COUNT(*)
FROM CON.FCT_FIN_GASTOSREAL
GROUP BY SOCIEDAD_ID, SOCIEDADCO_ID,CENTROCOSTO_ID, CUENTA_ID, ANIOMES
HAVING COUNT(*) > 1;



SELECT DISTINCT FIKRS AS FIKRS
FROM RAW.SQ1_EXT_0PU_IS_PS_31;




// Validacion de fechas fuera de rango y uso correcto de parametros de fechas

SELECT  'REAL' AS TIPO,
        MIN(FISCPER) AS MIN,
        MAX(FISCPER) AS MAX 
FROM RAW.SQ1_EXT_0CO_OM_CCA_9

UNION ALL

SELECT  'PRES' AS TIPO,
        MIN(FISCPER) AS MIN,
        MAX(FISCPER) AS MAX 
FROM RAW.SQ1_EXT_0CO_OM_CCA_1;

SELECT *
FROM RAW.PARAMETROS_EXTRACCION
WHERE ORDEN = '3'
AND EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9';

DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE ORDEN = '3'
AND EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';


ALTER TABLE PRE.PFCT_FIN_GASTOSREAL
ADD CONSTRAINT GASTOS_PK PRIMARY KEY (SOCIEDAD_ID,
        SOCIEDADCO_ID,
        CENTROCOSTO_ID,
        CUENTA_ID,
        ANIOMES);

SELECT *
FROM PRE.PFCT_FIN_GASTOSREAL;


SELECT DISTINCT TIPO
FROM CON.VW_FCT_FIN_GASTOS;


SELECT  CONSTRAINT_NAME,
        CONSTRAINT_TYPE,
        TABLE_NAME,
        COLUMN_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC

JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU

ON TC.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME

WHERE TC.TABLE_SCHEMA = 'PRE'
AND TC.TABLE_NAME = 'PFCT_FIN_GASTOSREAL'
AND TC.CONSTRAINT_TYPE = 'PRIMARY KEY';


SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE'; -- CREACIÓN DE ROLES 'GASTOS_ROLE' , 'DIMENSIONES', 'Valores' o también se puede 'ALL'.
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','DIRECCION_ID','20'),
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL')
;

DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE';


SELECT *
FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = 'JUAN_PEDREROS'; -- CREACIÓN DE USARIOS CON ROLES (SAP_ROLE tiene todo)
INSERT INTO SEGURIDAD.SEG_USUARIO_ROLE
(USER_NM,ROLE_NM) VALUES
('JUAN_PEDREROS','GASTOS_ROLE');
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = 'JUAN_PEDREROS';

SELECT *
FROM SEGURIDAD.SEG_USUARIO_DIMENSION;
INSERT INTO SEGURIDAD.SEG_USUARIO_DIMENSION
(USER_NM,DIM,VALOR) VALUES
('JUAN_PEDREROS','DIRECCION_ID','20');

DELETE FROM SEGURIDAD.SEG_USUARIO_DIMENSION
WHERE USER_NM = 'JUAN_PEDREROS';

SELECT *
FROM CON.DIM_FIN_CENTROCOSTO;

SELECT COUNT(CENTROCOSTO_ID) AS CENTROCOSTO
FROM(   
        SELECT	TIPO,
                DIRECCION_ID,
		ANIO, 
		MES, 
		ANIOMES, 
		FECHA_CONTABILIZACION,
		SOCIEDADCO_ID, 
		SOCIEDAD_ID, 
		CENTROCOSTO_ID, 
		CUENTA_ID, 
		CUENTAMAYOR_ID,
		GASTOER_ID, 
		CENTRO_ID, 
		ACREEDOR_ID, 
		SOCIEDADGLASOC_ID,
		VERSION_ID,

		IND_GASTOPRESUPUESTO_MXN,
		IND_GASTOPRESUPUESTO_SOC,
		IND_GASTOPRESUPUESTO_USD,

		IND_GASTOPRESUPUESTO_V0_SOC,
		IND_GASTOPRESUPUESTO_V1_SOC,
		IND_GASTOPRESUPUESTO_V2_SOC,
		IND_GASTOPRESUPUESTO_V3_SOC,
		IND_GASTOPRESUPUESTO_V0_MXN,
		IND_GASTOPRESUPUESTO_V1_MXN,
		IND_GASTOPRESUPUESTO_V2_MXN,
		IND_GASTOPRESUPUESTO_V3_MXN,
		IND_GASTOPRESUPUESTO_V0_USD,
		IND_GASTOPRESUPUESTO_V1_USD,
		IND_GASTOPRESUPUESTO_V2_USD,
		IND_GASTOPRESUPUESTO_V3_USD,

		IND_GASTOREAL_MXN,
		MON_MXN,
		IND_GASTOREAL_USD,
		MON_USD,
		IND_GASTOREAL_SOC,
		MON_SOC

        FROM CON.FCT_FIN_GASTOSPRESUPUESTO
        WHERE DIRECCION_ID = '20'

        UNION ALL

        SELECT          TIPO,
                        DIRECCION_ID,
                        ANIO, 
                        MES, 
                        ANIOMES, 
                        FECHA_CONTABILIZACION,
                        SOCIEDADCO_ID, 
                        SOCIEDAD_ID, 
                        CENTROCOSTO_ID, 
                        CUENTA_ID, 
                        CUENTAMAYOR_ID,
                        GASTOER_ID, 
                        CENTRO_ID, 
                        ACREEDOR_ID,
                        SOCIEDADGLASOC_ID,
                        VERSION_ID,

                        IND_GASTOPRESUPUESTO_MXN,
                        IND_GASTOPRESUPUESTO_SOC,
                        IND_GASTOPRESUPUESTO_USD,

                        IND_GASTOPRESUPUESTO_V0_SOC,
                        IND_GASTOPRESUPUESTO_V1_SOC,
                        IND_GASTOPRESUPUESTO_V2_SOC,
                        IND_GASTOPRESUPUESTO_V3_SOC,
                        IND_GASTOPRESUPUESTO_V0_MXN,
                        IND_GASTOPRESUPUESTO_V1_MXN,
                        IND_GASTOPRESUPUESTO_V2_MXN,
                        IND_GASTOPRESUPUESTO_V3_MXN,
                        IND_GASTOPRESUPUESTO_V0_USD,
                        IND_GASTOPRESUPUESTO_V1_USD,
                        IND_GASTOPRESUPUESTO_V2_USD,
                        IND_GASTOPRESUPUESTO_V3_USD,

                        IND_GASTOREAL_MXN,
                        MON_MXN,
                        IND_GASTOREAL_USD,
                        MON_USD,
                        IND_GASTOREAL_SOC,
                        MON_SOC
        FROM CON.FCT_FIN_GASTOSREAL
        WHERE DIRECCION_ID = '20'
)

UNION ALL

SELECT COUNT(CENTROCOSTO_ID) AS CENTROCOSTO
FROM CON.VW_FCT_FIN_GASTOS;


SELECT *
FROM CON.VW_FCT_FIN_GASTOS;




INSERT INTO RAW.PARAMETROS_EXTRACCION
        (ORDEN, EXTRACTOR, NEGOCIO, PARAMETRO, R_INICIO, R_FIN)
VALUES  (1, 'SQ1_EXT_0PU_IS_PS_31-43', 'CONTROL_PRESUPUESTAL', 'PERIODOS', '197001', '202612');