SELECT * FROM MIRRORING.DIM_FIN_ACREEDOR;
SELECT * FROM MIRRORING.DIM_FIN_CENTROCOSTO;
SELECT * FROM MIRRORING.DIM_FIN_SOCIEDADCO;
SELECT * FROM MIRRORING.DIM_FIN_CUENTA;
SELECT * FROM MIRRORING.DIM_FIN_VERSION;
SELECT * FROM MIRRORING.DIM_FIN_GASTOER;
SELECT * FROM MIRRORING.DIM_FIN_ACREEDOR;



SELECT COUNT(*) FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;


SELECT TIPO, COUNT(*)
FROM MIRRORING.FCT_FIN_GASTOS
GROUP BY TIPO;

SELECT COUNT(*)
FROM CON.FCT_FIN_GASTOSREAL;

SELECT COUNT(*)
FROM CON.FCT_FIN_GASTOSPRESUPUESTO;


SELECT DISTINCT ANIOMES
FROM MIRRORING.FCT_FIN_GASTOS;

SELECT DISTINCT ANIOMES
FROM MIRRORING.VW_FCT_FIN_GASTOS;

DESC TABLE MIRRORING.FCT_FIN_GASTOS;



SELECT R_INICIO, R_FIN
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';

SELECT *
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';

DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';

INSERT INTO RAW.PARAMETROS_EXTRACCION
VALUES
('1','SQ1_EXT_0CO_OM_CCA_9','GASTOS','FISCPER','2025001','2025008');



SELECT *
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;


SELECT R_INICIO, R_FIN
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0PU_IS_PS_31-43'
AND NEGOCIO = 'CONTROL_PRESUPUESTAL';


CALL PRE.SP_PRE_FCT_CONTROLPRESUPUESTAL('197001','202612');


SELECT R_INICIO, R_FIN
FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';



SELECT SUM(IND_GASTOREAL_SOC)
FROM MIRRORING.VW_FCT_FIN_GASTOS
WHERE ANIOMES = '202506';



SELECT SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL'
AND CURTYPE = '10'
AND KSTAR LIKE '%5';
--GROUP BY KSTAR ORDER BY KSTAR ASC;

SELECT  SUM(SWG) AS "IND_GASTOPRESUPUESTO_V0_SOC"
FROM RAW.SQ1_EXT_0CO_OM_CCA_1
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL'
AND VERSN = '000'
AND CURTYPE = '10';

SELECT SUM(IND_GASTOPRESUPUESTO_V0_SOC)
FROM PRE.PFCT_FIN_GASTOSPRESUPUESTO
WHERE ANIOMES = '202506';


SELECT DISTINCT FISCPER
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE CONCAT(SUBSTR(FISCPER, 0, 4), SUBSTR(FISCPER, 6, 2)) = '202506'
AND KOKRS = 'CAGL'
AND CURTYPE = '10';



SELECT DISTINCT KOSTL, SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL'
AND CURTYPE = '20'
AND KSTAR = '6201011001'
GROUP BY KOSTL ORDER BY KOSTL ASC;
-- AND KSTAR = '5220110001';


SELECT SUM(SWG)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL'
AND CURTYPE = '20';


SELECT DISTINCT COUNT(KSTAR)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL'
AND CURTYPE = '10';


SELECT COUNT(*)
FROM RAW.SQ1_EXT_0CO_OM_CCA_9
WHERE FISCPER = '2025006'
AND KOKRS = 'CAGL';



SELECT SUM(IND_PRESUPUESTO_ACTUAL)
FROM(
        SELECT  SUBSTR(ZHLDT,0,4) AS ANIO,
                IFF(SUBSTR(ZHLDT,6,2) = '00','01',
                        IFF(SUBSTR(ZHLDT,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(ZHLDT,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                '' AS TIPOVALORPRES_ID,
                '' AS VERSION_ID,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,
                
                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL

        FROM RAW.SQ1_EXT_0PU_IS_PS_31 AS EXT31

        LEFT JOIN PRE.PDIM_FIN_CUENTA AS CUENTA
		ON CONCAT(KOKRS,'_',LTRIM(EXT31.FIPEX, '0')) = CUENTA.CUENTA_ID

        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'

        UNION ALL

        SELECT  SUBSTR(ZHLDT,0,4) AS ANIO,
                IFF(SUBSTR(ZHLDT,6,2) = '00','01',
                        IFF(SUBSTR(ZHLDT,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(ZHLDT,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                '' AS TIPOVALORPRES_ID,
                '' AS VERSION_ID,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,
                
                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL

        FROM RAW.SQ1_EXT_0PU_IS_PS_32 AS EXT32
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'

        UNION ALL

        SELECT  SUBSTR(ZHLDT,0,4) AS ANIO,
                IFF(SUBSTR(ZHLDT,6,2) = '00','01',
                        IFF(SUBSTR(ZHLDT,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(ZHLDT,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                '' AS TIPOVALORPRES_ID,
                '' AS VERSION_ID,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,
                
                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL

        FROM RAW.SQ1_EXT_0PU_IS_PS_33 AS EXT33
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'

        UNION ALL

        SELECT  SUBSTR(FISCPER,0,4) AS ANIO,
                IFF(SUBSTR(FISCPER,6,2) = '00','01',
                        IFF(SUBSTR(FISCPER,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(FISCPER,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                VALTYPE_9 AS TIPOVALORPRES_ID,
                RVERS AS VERSION_ID,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,
                
                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL

        FROM RAW.SQ1_EXT_0PU_IS_PS_41 AS EXT41
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT41.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  SUBSTR(FISCPER,0,4) AS ANIO,
                IFF(SUBSTR(FISCPER,6,2) = '00','01',
                        IFF(SUBSTR(FISCPER,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(FISCPER,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                VALTYPE_9 AS TIPOVALORPRES_ID,
                RVERS AS VERSION_ID,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,
                
                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL
                
        FROM RAW.SQ1_EXT_0PU_IS_PS_42 AS EXT42
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT42.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (	(BUDAT = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (BUDAT != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR BUDAT BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )

        UNION ALL

        SELECT  SUBSTR(FISCPER,0,4) AS ANIO,
                IFF(SUBSTR(FISCPER,6,2) = '00','01',
                        IFF(SUBSTR(FISCPER,6,2) IN ('13','14','15','16'),'12',
                    SUBSTR(FISCPER,6,2))) AS MES,
                CONCAT(ANIO,MES) AS ANIOMES,
                FMTYPE	AS TIPOVALOR_ID,
                VALTYPE AS TIPOVALORPRES_ID,
                VERSION AS VERSION_ID,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '80' AND TIPOVALORPRES_ID = 'B1' AND VERSION_ID = '000',
                        IND_IMPORTE_ENTCP, 0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ACTUAL
                
                
        FROM RAW.SQ1_EXT_0PU_IS_PS_43 AS EXT43
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT43.FUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE FM_AREA BETWEEN 'FMAR' AND 'FMPE'
        AND (	(POSTDATE = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (POSTDATE != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR POSTDATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )

) WHERE ANIOMES BETWEEN '202501' AND '2025012';

SELECT SUM()
FROM PRE.PF