SELECT * FROM MIRRORING.DIM_FIN_ENTIDADCP;
SELECT * FROM MIRRORING.DIM_FIN_SOCIEDADCO;
SELECT * FROM MIRRORING.DIM_FIN_CENTROCOSTO;
SELECT * FROM MIRRORING.DIM_FIN_CENTROGESTOR;
SELECT * FROM MIRRORING.DIM_FIN_CUENTA;
SELECT * FROM MIRRORING.DIM_FIN_SOCIEDADGLASOC;
SELECT * FROM MIRRORING.DIM_FIN_VERSION;
SELECT * FROM MIRRORING.DIM_FIN_GASTOER;
SELECT * FROM MIRRORING.DIM_FIN_ACREEDOR;
SELECT * FROM MIRRORING.DIM_FIN_PROGRAMAPRES;
SELECT * FROM MIRRORING.DIM_FIN_DETALLECOMPREAL;
SELECT * FROM MIRRORING.DIM_FIN_POSICIONPRES;
SELECT * FROM MIRRORING.DIM_FIN_CATEGORIAPRES;
SELECT * FROM MIRRORING.DIM_CAL_GASTOSCONTROLPRES;


SELECT * FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES;
SELECT * FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
DESC TABLE MIRRORING.FCT_FIN_GASTOSCONTROLPRES;


SELECT COUNT(*) FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;



SELECT R_INICIO, R_FIN
FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0PU_IS_PS_31-43'
AND NEGOCIO = 'CONTROL_PRESUPUESTAL';

DELETE FROM RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0PU_IS_PS_31-43'
AND NEGOCIO = 'CONTROL_PRESUPUESTAL';

INSERT INTO RAW.PARAMETROS_EXTRACCION
(ORDEN,EXTRACTOR,NEGOCIO,PARAMETRO,R_INICIO,R_FIN) VALUES 
('1','SQ1_EXT_0PU_IS_PS_31-43','CONTROL_PRESUPUESTAL','PERIODO','202501','202501');


SELECT R_INICIO, R_FIN
FROM LAMOSALAKE_DEV.RAW.PARAMETROS_EXTRACCION
WHERE EXTRACTOR = 'SQ1_EXT_0CO_OM_CCA_9'
AND NEGOCIO = 'GASTOS';


CALL PRE.SP_PRE_FCT_CONTROLPRESUPUESTAL('197001','202612');

SELECT DISTINCT SOCIEDAD_ID
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL;

SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM CON.FCT_FIN_CONTROLPRESUPUESTAL
GROUP BY SOCIEDAD_ID;

SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES
GROUP BY SOCIEDAD_ID;

SELECT SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES;


SELECT SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES
GROUP BY SOCIEDAD_ID;
SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES
GROUP BY SOCIEDAD_ID;
SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES
GROUP BY SOCIEDAD_ID;



DELETE FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
DELETE FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;
DELETE FROM MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES;


SELECT COUNT(*)
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;

DELETE FROM CON.FCT_FIN_CONTROLPRESUPUESTAL;
DELETE FROM CON.FCT_FIN_GASTOSREAL;
DELETE FROM CON.FCT_FIN_GASTOSPRESUPUESTO;




SELECT DEUDOR_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM CON.FCT_FIN_CONTROLPRESUPUESTAL
GROUP BY DEUDOR_ID;






SELECT  SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM (
        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',FISTL) AS CENTROGESTOR_ID,
                FISTL AS CENTROGESTOR,
                STATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',FIPEX)	AS POSICIONPRES_ID,
                FIPEX	AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(FISTL, '0'))	AS CENTROCOSTO_ID,
                LTRIM(FISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_31 AS EXT31
        
        LEFT JOIN PRE.PDIM_FIN_CUENTA AS CUENTA
		ON CONCAT(KOKRS,'_',LTRIM(EXT31.FIPEX, '0')) = CUENTA.CUENTA_ID

        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT31.FISTL, '0')) = CECO.CENTROCOSTO_ID

        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',FISTL) AS CENTROGESTOR_ID,
                FISTL AS CENTROGESTOR,
                STATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',FIPEX)	AS POSICIONPRES_ID,
                FIPEX	AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(FISTL, '0'))	AS CENTROCOSTO_ID,
                LTRIM(FISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_32 AS EXT32
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT32.FISTL, '0')) = CECO.CENTROCOSTO_ID
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',RFISTL) AS CENTROGESTOR_ID,
                RFISTL AS CENTROGESTOR,
                RSTATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',RFIPEX) AS POSICIONPRES_ID,
                RFIPEX AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(RFISTL, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_33 AS EXT33
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT33.RFISTL, '0')) = CECO.CENTROCOSTO_ID
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(RFIKRS,'_',RFUNDSCTR) AS CENTROGESTOR_ID,
                RFUNDSCTR AS CENTROGESTOR,
                ''	AS INDICADOREST_ID, --STATS
                CONCAT(RFIKRS,'_',RCMMTITEM) AS POSICIONPRES_ID,
                RCMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(RFUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_41 AS EXT41
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT41.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(RFIKRS,'_',RFUNDSCTR) AS CENTROGESTOR_ID,
                RFUNDSCTR AS CENTROGESTOR,
                ''	AS INDICADOREST_ID, --STATS
                CONCAT(RFIKRS,'_',RCMMTITEM) AS POSICIONPRES_ID,
                RCMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(RFUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_42 AS EXT42
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT42.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (	(BUDAT = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (BUDAT != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR BUDAT BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'DUMMY') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FM_AREA,'_',FUNDSCTR) AS CENTROGESTOR_ID,
                FUNDSCTR AS CENTROGESTOR,
                '' AS INDICADOREST_ID, --STATS
                CONCAT(FM_AREA,'_',CMMTITEM) AS POSICIONPRES_ID,
                CMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(FUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(FUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_43 AS EXT43
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT43.FUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE FM_AREA BETWEEN 'FMAR' AND 'FMPE'
        AND (	(POSTDATE = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (POSTDATE != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR POSTDATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )
)
WHERE SOCIEDAD_ID = 'DUMMY'
GROUP BY SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID;






        select distinct CONCAT('CAGL','_',LTRIM(EXT31.FISTL, '0')) as CENTROCOSTO
        FROM RAW.SQ1_EXT_0PU_IS_PS_31 AS EXT31
        where CENTROCOSTO NOT IN (SELECT CENTROCOSTO_ID FROM PRE.PDIM_FIN_CENTROCOSTO);

SELECT  SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID, SUM(IND_IMPORTE_ENTCP), SUM(IND_PRESUPUESTO_ASIGNADO)
FROM (
        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',FISTL) AS CENTROGESTOR_ID,
                FISTL AS CENTROGESTOR,
                STATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',FIPEX)	AS POSICIONPRES_ID,
                FIPEX	AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(FISTL, '0'))	AS CENTROCOSTO_ID,
                LTRIM(FISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_31 AS EXT31
        
        LEFT JOIN PRE.PDIM_FIN_CUENTA AS CUENTA
		ON CONCAT(KOKRS,'_',LTRIM(EXT31.FIPEX, '0')) = CUENTA.CUENTA_ID

        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT31.FISTL, '0')) = CECO.CENTROCOSTO_ID

        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',FISTL) AS CENTROGESTOR_ID,
                FISTL AS CENTROGESTOR,
                STATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',FIPEX)	AS POSICIONPRES_ID,
                FIPEX	AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(FISTL, '0'))	AS CENTROCOSTO_ID,
                LTRIM(FISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_32 AS EXT32
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT32.FISTL, '0')) = CECO.CENTROCOSTO_ID
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',RFISTL) AS CENTROGESTOR_ID,
                RFISTL AS CENTROGESTOR,
                RSTATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',RFIPEX) AS POSICIONPRES_ID,
                RFIPEX AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(RFISTL, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_33 AS EXT33
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',LTRIM(EXT33.RFISTL, '0')) = CECO.CENTROCOSTO_ID
        WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(RFIKRS,'_',RFUNDSCTR) AS CENTROGESTOR_ID,
                RFUNDSCTR AS CENTROGESTOR,
                ''	AS INDICADOREST_ID, --STATS
                CONCAT(RFIKRS,'_',RCMMTITEM) AS POSICIONPRES_ID,
                RCMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(RFUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_41 AS EXT41
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT41.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (CECO.FECHA_DESDE IS NULL OR CECO.FECHA_HASTA IS NULL OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(RFIKRS,'_',RFUNDSCTR) AS CENTROGESTOR_ID,
                RFUNDSCTR AS CENTROGESTOR,
                ''	AS INDICADOREST_ID, --STATS
                CONCAT(RFIKRS,'_',RCMMTITEM) AS POSICIONPRES_ID,
                RCMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(RFUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(RFUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_42 AS EXT42
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT42.RFUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE RFIKRS BETWEEN 'FMAR' AND 'FMPE'
        AND (	(BUDAT = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (BUDAT != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR BUDAT BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )

        UNION ALL

        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FM_AREA,'_',FUNDSCTR) AS CENTROGESTOR_ID,
                FUNDSCTR AS CENTROGESTOR,
                '' AS INDICADOREST_ID, --STATS
                CONCAT(FM_AREA,'_',CMMTITEM) AS POSICIONPRES_ID,
                CMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(FUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(FUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_43 AS EXT43
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT43.FUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE FM_AREA BETWEEN 'FMAR' AND 'FMPE'
        AND (	(POSTDATE = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (POSTDATE != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR POSTDATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )
)
WHERE CENTROGESTOR = 'DUMMY' AND POSICIONPRES = '1109101018'
GROUP BY SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID;



        SELECT  BUKRS AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FIKRS,'_',FISTL) AS CENTROGESTOR_ID,
                FISTL AS CENTROGESTOR,
                STATS	AS INDICADOREST_ID,
                CONCAT(FIKRS,'_',FIPEX)	AS POSICIONPRES_ID,
                FIPEX	AS POSICIONPRES,
                CONCAT(KOKRS,'_',LTRIM(FISTL, '0'))	AS CENTROCOSTO_ID,
                LTRIM(FISTL, '0')	AS CENTROCOSTO,
                FKBTR AS IND_IMPORTE_ENTCP,
                WAERS AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_31 AS EXT31
        WHERE CENTROGESTOR = 'DUMMY'
        AND POSICIONPRES = '1109101018';


        SELECT  SUM(FKBTR)
        FROM RAW.SQ1_EXT_0PU_IS_PS_31
        WHERE FISTL = 'DUMMY'
        AND FIPEX = '1109101018';




SELECT  SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID, SUM(IND_IMPORTE_ENTCP), SUM(IND_PRESUPUESTO_ASIGNADO)
FROM (
        SELECT  COALESCE(CECO.SOCIEDAD_ID,'') AS SOCIEDAD_ID,
                FMTYPE	AS TIPOVALOR_ID,
                CONCAT(FM_AREA,'_',FUNDSCTR) AS CENTROGESTOR_ID,
                FUNDSCTR AS CENTROGESTOR,
                '' AS INDICADOREST_ID, --STATS
                CONCAT(FM_AREA,'_',CMMTITEM) AS POSICIONPRES_ID,
                CMMTITEM AS POSICIONPRES,
                CONCAT(SOCIEDADCO_ID,'_',LTRIM(FUNDSCTR, '0')) AS CENTROCOSTO_ID,
                LTRIM(FUNDSCTR, '0')	AS CENTROCOSTO,
                AMOUNT AS IND_IMPORTE_ENTCP,
                FMCUR AS MON_ENTCP,

                IFF(MON_ENTCP IN ('CLP','COP'),
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) * 100, -- Calculo de vista CON
                        (IFF(TIPOVALOR_ID = '70' AND INDICADOREST_ID <> 'X',
                        IND_IMPORTE_ENTCP,0)) -- Calculo de tabla CON
                    ) AS IND_PRESUPUESTO_ASIGNADO

        FROM RAW.SQ1_EXT_0PU_IS_PS_43 AS EXT43
        LEFT JOIN PRE.PDIM_FIN_CENTROCOSTO AS CECO
            ON CONCAT('CAGL','_',EXT43.FUNDSCTR) = CECO.CENTROCOSTO_ID
        WHERE FM_AREA BETWEEN 'FMAR' AND 'FMPE'
        AND (	(POSTDATE = '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL 
                            OR CECO.FECHA_HASTA IS NULL
                            OR CURRENT_DATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
                OR (POSTDATE != '1970-01-01'
                    AND (CECO.FECHA_DESDE IS NULL
                            OR CECO.FECHA_HASTA IS NULL
                            OR POSTDATE BETWEEN CECO.FECHA_DESDE AND CECO.FECHA_HASTA)
                )
        )
)
WHERE CENTROGESTOR = 'DUMMY' AND POSICIONPRES = '1109101018'
GROUP BY SOCIEDAD_ID, CENTROGESTOR_ID, POSICIONPRES_ID, CENTROCOSTO_ID;