SELECT  '31' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_31

UNION ALL

SELECT  '32' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_32

UNION ALL

SELECT  '33' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_33

UNION ALL

SELECT  '41' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_41

UNION ALL

SELECT  '42' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_42

UNION ALL

SELECT  '43' AS EXTRACTOR,
        COUNT(*)
FROM RAW.SQ1_EXT_0PU_IS_PS_43;


-------------------------------


SELECT  'PRE' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL

UNION ALL

SELECT  'CON' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM CON.FCT_FIN_CONTROLPRESUPUESTAL

UNION ALL

SELECT  'VISTA' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;

------------------------

SELECT  '31' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70' AND STATS <> 'X'
            THEN FKBTR ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_31
WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'

UNION ALL

SELECT  '32' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70' AND STATS <> 'X'
            THEN FKBTR ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_32_DELTA
WHERE FIKRS BETWEEN 'FMAR' AND 'FMPE'

UNION ALL

SELECT  '33' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70' AND RSTATS <> 'X'
            THEN FKBTR ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_33

UNION ALL

SELECT  '41' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70'
            THEN AMOUNT ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_41

UNION ALL

SELECT  '42' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70'
            THEN AMOUNT ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_42

UNION ALL

SELECT  '43' AS EXTRACTOR,
        SUM(CASE WHEN FMTYPE = '70'
            THEN AMOUNT ELSE 0 END) AS IND_PRESUPUESTO_ASIGNADO
FROM RAW.SQ1_EXT_0PU_IS_PS_43;



SELECT  'PRE' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL
WHERE CENTROCOSTO_ID = 'CAGL_A002040060'

UNION ALL

SELECT  'CON' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM CON.FCT_FIN_CONTROLPRESUPUESTAL
WHERE CENTROCOSTO_ID = 'CAGL_A002040060'

UNION ALL

SELECT  'VISTA' AS CAPA,
        SUM(IND_PRESUPUESTO_ASIGNABLE) AS IND_PRESUPUESTO_ASIGNABLE,
        SUM(IND_PRESUPUESTO_ASIGNADO) AS IND_PRESUPUESTO_ASIGNADO,
        SUM(IND_PRESUPUESTO_DISPONIBLE) AS IND_PRESUPUESTO_DISPONIBLE,
        SUM(IND_PRESUPUESTO_ACTUAL) AS IND_PRESUPUESTO_ACTUAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL
WHERE CENTROCOSTO_ID = 'CAGL_A002040060';


SELECT 916552618.92 + 4555219860.72;
SELECT 5415446670.61 - 5484745149.81;



SELECT  SOCIEDADCO_ID,
        ENTIDADCP_ID,
        CENTROCOSTO_ID,
        CUENTA_ID,
        FECHA_CONTABILIZACION,
        COUNT(*) AS COUNTER
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL
WHERE SOCIEDADCO_ID IS NULL OR SOCIEDADCO_ID = ''
OR ENTIDADCP_ID IS NULL OR ENTIDADCP_ID = ''
OR CENTROCOSTO_ID IS NULL OR CENTROCOSTO_ID = ''
OR CUENTA_ID IS NULL OR CUENTA_ID = ''
OR FECHA_CONTABILIZACION IS NULL
GROUP BY ALL;



SELECT *
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
