CALL CON.SP_CON_FCT_CONTROLPRESUPUESTAL('197001','202612');

delete from  MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
select distinct FECHA_CONTABILIZACION from  MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
select distinct FECHA_CONTABILIZACION from  MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;
select distinct FECHA_CONTABILIZACION from  MIRRORING.VW_FCT_FIN_GASTOSCONTROLPRES;


-- Quitar ceros de Acreedor y Deudor FACT Control y Gastos Real y Pres

SELECT DISTINCT ACREEDOR_ID
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT ACREEDOR_ID
FROM CON.FCT_FIN_GASTOSREAL;

SELECT DISTINCT ACREEDOR_ID
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
SELECT *
FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;
SELECT *
FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;

SELECT DISTINCT ACREEDOR_ID
FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;

DELETE FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;
DELETE FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES;


SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM CON.FCT_FIN_CONTROLPRESUPUESTAL
GROUP BY SOCIEDAD_ID;

SELECT SOCIEDAD_ID, SUM(IND_PRESUPUESTO_ASIGNADO)
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL
GROUP BY SOCIEDAD_ID;

SELECT *
FROM PRE.PFCT_FIN_CONTROLPRESUPUESTAL;

SELECT DISTINCT DEUDOR_ID
FROM(
        SELECT  ''	AS DEUDOR_ID, --KUNNR
        FROM RAW.SQ1_EXT_0PU_IS_PS_31

        UNION ALL

        SELECT  KUNNR AS DEUDOR_ID
        FROM RAW.SQ1_EXT_0PU_IS_PS_32 AS EXT32

        UNION ALL

        SELECT  ''	AS DEUDOR_ID, --KUNNR
        FROM RAW.SQ1_EXT_0PU_IS_PS_33

        UNION ALL

        SELECT  ''	AS DEUDOR_ID, --KUNNR
        FROM RAW.SQ1_EXT_0PU_IS_PS_41

        UNION ALL

        SELECT  ''	AS DEUDOR_ID, --KUNNR
        FROM RAW.SQ1_EXT_0PU_IS_PS_42

        UNION ALL

        SELECT  '' AS DEUDOR_ID, --KUNNR
        FROM RAW.SQ1_EXT_0PU_IS_PS_43
);