
--SEG_ROLE_DIMENSION
--SEG_USUARIO_ROLE
--SEG_USUARIO_DIMENSION

SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'SAP_ROLE'; -- CREACIÓN DE ROLES 'GASTOS_ROLE' , 'DIMENSIONES', 'Valores' o también se puede 'ALL'.
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','SOCIEDAD_ID','ALL'), --R201
('GASTOS_ROLE','DIRECCION_ID','20'), --20
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL')
;
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE';



SELECT *
FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = 'JUAN_PEDREROS'; -- CREACIÓN DE USARIOS CON ROLES (SAP_ROLE tiene todo)
INSERT INTO SEGURIDAD.SEG_USUARIO_ROLE
(USER_NM,ROLE_NM) VALUES
('JUAN_PEDREROS','GASTOS_ROLE');
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE --- USUARIO_ROLE
WHERE USER_NM = 'JUAN_PEDREROS';


SELECT *
FROM SEGURIDAD.SEG_USUARIO_DIMENSION; --- USUARIO_DIMENSION
INSERT INTO SEGURIDAD.SEG_USUARIO_DIMENSION
(USER_NM,DIM,VALOR) VALUES
('JUAN_PEDREROS','SOCIEDAD_ID','R201');
DELETE FROM SEGURIDAD.SEG_USUARIO_DIMENSION
WHERE USER_NM = 'JUAN_PEDREROS';



SELECT *
FROM CON.DIM_FIN_CENTROCOSTO;

SELECT *
FROM CON.VW_DIM_FIN_CENTROCOSTO;

SELECT *
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;

SELECT *
FROM CON.VW_FCT_FIN_GASTOS;


 
SELECT GASTO.CENTROCOSTO_ID, CENTRO.CENTROCOSTO_ID
FROM CON.FCT_FIN_GASTOSPRESUPUESTO AS GASTO

JOIN CON.DIM_FIN_CENTROCOSTO AS CENTRO

ON GASTO.CENTROCOSTO_ID = CENTRO.CENTROCOSTO_ID;







------------------------------------------------------------------
---------------------------------------------------------------

-- Validar acceso sin roles asignados

SELECT *
FROM SEGURIDAD.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_NM = 'JUAN_PEDREROS';
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE
WHERE USER_NM = 'JUAN_PEDREROS';        -- BORRAR ROLES ASIGNADOS A MI USUARIO

SELECT *                                -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT *                                -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;



------------------------------------------------------------------
---------------------------------------------------------------

-- Rol SAP_ROLE asignado

SELECT *
FROM SEGURIDAD.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_NM = 'JUAN_PEDREROS';
INSERT INTO SEGURIDAD.SEG_USUARIO_ROLE
(USER_NM,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('JUAN_PEDREROS','SAP_ROLE');
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE  -- ELIMINAR ROLES ASIGNADOS A MI USUARIO
WHERE USER_NM = 'JUAN_PEDREROS';


SELECT *                                -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT *                                -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;



------------------------------------------------------------------
---------------------------------------------------------------

-- Un rol asignado con la dimensión y un valor de dimensión


SELECT *
FROM SEGURIDAD.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_NM = 'JUAN_PEDREROS';
INSERT INTO SEGURIDAD.SEG_USUARIO_ROLE
(USER_NM,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('JUAN_PEDREROS','GASTOS_ROLE');
DELETE FROM SEGURIDAD.SEG_USUARIO_ROLE  -- ELIMINAR ROLES ASIGNADOS A MI USUARIO
WHERE USER_NM = 'JUAN_PEDREROS';


SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'GASTOS_ROLE';

INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','SOCIEDAD_ID','A101'),
('GASTOS_ROLE','DIRECCION_ID','20'),
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL');
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION        -- ELIMINAR DIMENSIONES ASIGNADAS A ROLE
WHERE ROLE_NM = 'GASTOS_ROLE';


SELECT DISTINCT SOCIEDAD_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT SOCIEDAD_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;

SELECT DISTINCT CENTROCOSTO_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT CENTROCOSTO_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;


SELECT CENTROCOSTO_ID, DIRECCION_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO             -- CENTROS DE COSTO DE CONTROL PRESUPUESTAL
WHERE CENTROCOSTO_ID IN ('CAGL_A402011140',
'CAGL_A404012140',
'CAGL_A403015140',
'CAGL_A402076600',
'CAGL_A406033260');


SELECT CENTROCOSTO_ID, DIRECCION_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO             -- CENTROS DE COSTO DE GASTOS
WHERE CENTROCOSTO_ID IN ('CAGL_A402086401',
'CAGL_A402086407',
'CAGL_A403015140',
'CAGL_A406053330',
'CAGL_A408034260');



------------------------------------------------------------------
---------------------------------------------------------------

-- Un rol asignado con la dimensión y diferentes valores de dimensión

SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'GASTOS_ROLE';
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION    -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','SOCIEDAD_ID','A101'),
('GASTOS_ROLE','SOCIEDAD_ID','A102'),
('GASTOS_ROLE','SOCIEDAD_ID','A103'),
('GASTOS_ROLE','DIRECCION_ID','20'),
('GASTOS_ROLE','DIRECCION_ID','C0'),
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL');
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE


SELECT DISTINCT SOCIEDAD_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT SOCIEDAD_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;

SELECT DISTINCT CENTROCOSTO_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT CENTROCOSTO_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;


SELECT CENTROCOSTO_ID, DIRECCION_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO             -- CENTROS DE COSTO DE CONTROL PRESUPUESTAL
WHERE CENTROCOSTO_ID IN (
'CAGL_A402011140',
'CAGL_A404012140',
'CAGL_A403015140',
'CAGL_A402076600',
'CAGL_A406033260',
'CAGL_A403025150',
'CAGL_A404062340',
'CAGL_A404022150',
'CAGL_A402061360',
'CAGL_A407053335',
'CAGL_A421037010',
'CAGL_A402086405',
'CAGL_A407086402',
'CAGL_A403045320',
'CAGL_A415087001',
'CAGL_A431037010',
'CAGL_A402021140',
'CAGL_A404062360',
'CAGL_A404042322',
'CAGL_A407043322',
'CAGL_A402086440',
'CAGL_A402036230',
'CAGL_A402086403',
'CAGL_A408014147',
'CAGL_A402086401',
'CAGL_A409042322',
'CAGL_A402086402',
'CAGL_A407023145',
'CAGL_A401041326');


SELECT CENTROCOSTO_ID, DIRECCION_ID
FROM CON.VW_DIM_FIN_CENTROCOSTO             -- CENTROS DE COSTO DE GASTOS
WHERE CENTROCOSTO_ID IN (
'CAGL_A402086407',
'CAGL_A402046470',
'CAGL_A406053330',
'CAGL_A403015140',
'CAGL_A403055330',
'CAGL_A407086400',
'CAGL_A402076600',
'CAGL_A402087010',
'CAGL_A406063360',
'CAGL_A406013140',
'CAGL_A402041320',
'CAGL_A407023145',
'CAGL_A402021903',
'CAGL_A403025140',
'CAGL_A408086402',
'CAGL_A402086402',
'CAGL_A402011140',
'CAGL_A409032265',
'CAGL_A404062360',
'CAGL_A406033260',
'CAGL_A417037010',
'CAGL_A436037010',
'CAGL_A402086420',
'CAGL_A404022151',
'CAGL_A401011146',
'CAGL_A406086401',
'CAGL_A407086402',
'CAGL_A415087010',
'CAGL_A402087001',
'CAGL_A407013145',
'CAGL_A408024140',
'CAGL_A402086406',
'CAGL_A404042322',
'CAGL_A402021140',
'CAGL_A402087016',
'CAGL_A407043325',
'CAGL_A402037022',
'CAGL_A408064340',
'CAGL_A402041322',
'CAGL_A402096540',
'CAGL_A403025150',
'CAGL_A408024150',
'CAGL_A403035260');



------------------------------------------------------------------
---------------------------------------------------------------

-- Un rol asignado con la dimensión y un valor inexistente

SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'GASTOS_ROLE';
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','SOCIEDAD_ID','R201'), --R201
('GASTOS_ROLE','DIRECCION_ID','20'),
('GASTOS_ROLE','DIRECCION_ID','C0'),
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL');
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE';


SELECT DISTINCT SOCIEDAD_ID, CENTROCOSTO_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT SOCIEDAD_ID, CENTROCOSTO_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;

SELECT DISTINCT CENTROCOSTO_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL;
SELECT DISTINCT CENTROCOSTO_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS;




------------------------------------------------------------------
---------------------------------------------------------------

-- Dimensión asignada a Role con valor ALL

SELECT *
FROM SEGURIDAD.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'GASTOS_ROLE';
INSERT INTO SEGURIDAD.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIM,VALOR) VALUES
('GASTOS_ROLE','SOCIEDAD_ID','ALL'),
('GASTOS_ROLE','DIRECCION_ID','ALL'),
('GASTOS_ROLE','SUCURSAL_ID','ALL'),
('GASTOS_ROLE','GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_CC_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_GERENCIA_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECCION_ID','ALL'),
('GASTOS_ROLE','ENCARGADO_DIRECAREA_ID','ALL');
DELETE FROM SEGURIDAD.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'GASTOS_ROLE';


SELECT DISTINCT SOCIEDAD_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL
ORDER BY SOCIEDAD_ID ASC;
SELECT DISTINCT SOCIEDAD_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS
ORDER BY SOCIEDAD_ID ASC;

SELECT DISTINCT CENTROCOSTO_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL
ORDER BY CENTROCOSTO_ID ASC;
SELECT DISTINCT CENTROCOSTO_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS
ORDER BY CENTROCOSTO_ID ASC;



------------------------------------------------------------------
---------------------------------------------------------------

-- Dimensión asignada a Usuario con valor

SELECT *
FROM SEGURIDAD.SEG_USUARIO_DIMENSION
WHERE USER_NM = 'JUAN_PEDREROS'; --- USUARIO_DIMENSION
INSERT INTO SEGURIDAD.SEG_USUARIO_DIMENSION
(USER_NM,DIM,VALOR) VALUES
('JUAN_PEDREROS','SOCIEDAD_ID','A101');
DELETE FROM SEGURIDAD.SEG_USUARIO_DIMENSION
WHERE USER_NM = 'JUAN_PEDREROS';


SELECT DISTINCT SOCIEDAD_ID             -- VISTA CONTROL PRESUPUESTAL
FROM CON.VW_FCT_FIN_CONTROLPRESUPUESTAL
ORDER BY SOCIEDAD_ID ASC;
SELECT DISTINCT SOCIEDAD_ID             -- VISTA GASTOS
FROM CON.VW_FCT_FIN_GASTOS
ORDER BY SOCIEDAD_ID ASC;