SELECT * FROM MIRRORING.SEG_USUARIO_ROLE;
SELECT * FROM MIRRORING.SEG_ROLE_DIMENSION;
SELECT * FROM MIRRORING.SEG_USUARIO_DIMENSION;



------------------------------------------------------------------
------------------------------------------------------------------

-- Validar acceso sin roles asignados

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
DELETE FROM MIRRORING.SEG_USUARIO_ROLE
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';        -- BORRAR ROLES ASIGNADOS A MI USUARIO

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'adolfo.castro@lamosa.com';

------------------------------------------------------------------
------------------------------------------------------------------

-- Rol SAP_ROLE asignado

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_ROLE
(USER_MAIL,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('test.pbi@grupolamosa.com','SAP_ROLE');
DELETE FROM MIRRORING.SEG_USUARIO_ROLE  -- ELIMINAR ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';



------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Un rol asignado con la dimensión y un valor de dimensión

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE


-- REV
-- Un rol asignado con la dimensión y un valor de dimensión

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AEX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE



------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Un rol asignado con la dimensión y diferentes valores de dimensión

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AGU1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','RPTA'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE



-- REV
-- Un rol asignado con la dimensión y diferentes valores de dimensión

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_REV_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AGU1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','RPTA'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE 



------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Un rol asignado con la dimensión y un valor inexistente

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A104'),    ----- <---- VALOR DE SOCIEDAD A104 INEXISTENTE
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AGU1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','RPTA'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE



-- REV
-- Un rol asignado con la dimensión y un valor inexistente

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_REV_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_REV_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_REV_ROLE','SOCIEDAD_ID','A104'),    ----- <---- VALOR DE SOCIEDAD A104 INEXISTENTE
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AGU1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','RPTA'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE



------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Dimensión asignada a Role con valor ALL

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_ROLE
(USER_MAIL,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('test.pbi@grupolamosa.com','CARTERA_ADH_ROLE');

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','ALL'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','ALL'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','ALL');

DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE


-- REV
-- Dimensión asignada a Role con valor ALL

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_ROLE
(USER_MAIL,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('test.pbi@grupolamosa.com','CARTERA_ADH_ROLE');

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','ALL'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','ALL'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','ALL');

DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE



------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Validar acceso con dimensión asignada a usario con valor 'ALL'

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE

SELECT *
FROM MIRRORING.SEG_USUARIO_DIMENSION       -- DIMENSIONES EXISTENTES DEL USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_DIMENSION
(USER_MAIL,DIM,VALOR) VALUES
('test.pbi@grupolamosa.com','SOCIEDAD_ID','ALL'),
('test.pbi@grupolamosa.com','CANALDISTRIBUCION_ID','ALL'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','ALL');
DELETE FROM MIRRORING.SEG_USUARIO_DIMENSION
WHERE USER_MAIL = 'test.pbi@grupolamosa.com'; 


------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Dimensión asignada a Role con valor ALL

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_ROLE
(USER_MAIL,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('test.pbi@grupolamosa.com','CARTERA_ADH_ROLE');

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','ALL'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','ALL'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','ALL');

DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE


-- REV
-- Dimensión asignada a Role con valor ALL

SELECT *
FROM MIRRORING.SEG_USUARIO_ROLE         -- ROLES ASIGNADOS A MI USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_ROLE
(USER_MAIL,ROLE_NM) VALUES                -- ASIGNACIÓN DE ROLE A MI USUARIO
('test.pbi@grupolamosa.com','CARTERA_ADH_ROLE');

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','ALL'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','ALL'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','ALL');

DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE





------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Validar acceso con dimensión asignada a usario con un valor

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE

SELECT *
FROM MIRRORING.SEG_USUARIO_DIMENSION       -- DIMENSIONES EXISTENTES DEL USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_DIMENSION
(USER_MAIL,DIM,VALOR) VALUES
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A101'),
('test.pbi@grupolamosa.com','CANALDISTRIBUCION_ID','EX'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AEX1');
DELETE FROM MIRRORING.SEG_USUARIO_DIMENSION
WHERE USER_MAIL = 'test.pbi@grupolamosa.com'; 



-- REV
-- Validar acceso con dimensión asignada a usario con un valor

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_REV_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_REV_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE

SELECT *
FROM MIRRORING.SEG_USUARIO_DIMENSION       -- DIMENSIONES EXISTENTES DEL USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_DIMENSION
(USER_MAIL,DIM,VALOR) VALUES
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A101'),
('test.pbi@grupolamosa.com','CANALDISTRIBUCION_ID','EX'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AEX1');
DELETE FROM MIRRORING.SEG_USUARIO_DIMENSION
WHERE USER_MAIL = 'test.pbi@grupolamosa.com'; 




------------------------------------------------------------------
------------------------------------------------------------------

-- ADH
-- Validar acceso con dimensión asignada a usario con varios valores

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_ADH_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_ADH_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_ADH_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_ADH_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE

SELECT *
FROM MIRRORING.SEG_USUARIO_DIMENSION       -- DIMENSIONES EXISTENTES DEL USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_DIMENSION
(USER_MAIL,DIM,VALOR) VALUES
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A101'),
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A102'),
('test.pbi@grupolamosa.com','CANALDISTRIBUCION_ID','EX'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AEX1'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AMR1');
DELETE FROM MIRRORING.SEG_USUARIO_DIMENSION
WHERE USER_MAIL = 'test.pbi@grupolamosa.com'; 



-- REV
-- Validar acceso con dimensión asignada a usario con varios valores

SELECT *
FROM MIRRORING.SEG_ROLE_DIMENSION       -- DIMENSIONES EXISTENTES DEL ROLE
WHERE ROLE_NM = 'CARTERA_REV_ROLE';
INSERT INTO MIRRORING.SEG_ROLE_DIMENSION        -- ASIGNAR DIMENSIONES Y VALORES A ROLE
(ROLE_NM,DIMENSION_NM,VALOR) VALUES
('CARTERA_REV_ROLE','SOCIEDAD_ID','A101'),
('CARTERA_REV_ROLE','SOCIEDAD_ID','A102'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','EX'),
('CARTERA_REV_ROLE','CANALDISTRIBUCION_ID','IN'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AEX1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMR1'),
('CARTERA_REV_ROLE','OFICINAVENTAS_ID','AMX1');
DELETE FROM MIRRORING.SEG_ROLE_DIMENSION
WHERE ROLE_NM = 'CARTERA_REV_ROLE';      -- ELIMINAR DIMENSIONES Y VALORES ASIGNADOS A ROLE

SELECT *
FROM MIRRORING.SEG_USUARIO_DIMENSION       -- DIMENSIONES EXISTENTES DEL USUARIO
WHERE USER_MAIL = 'test.pbi@grupolamosa.com';
INSERT INTO MIRRORING.SEG_USUARIO_DIMENSION
(USER_MAIL,DIM,VALOR) VALUES
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A101'),
('test.pbi@grupolamosa.com','SOCIEDAD_ID','A102'),
('test.pbi@grupolamosa.com','CANALDISTRIBUCION_ID','EX'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AEX1'),
('test.pbi@grupolamosa.com','OFICINAVENTAS_ID','AMR1');
DELETE FROM MIRRORING.SEG_USUARIO_DIMENSION
WHERE USER_MAIL = 'test.pbi@grupolamosa.com'; 