CREATE OR REPLACE TABLE MIRRORING.DIM_GEO_GEOGRAFIA AS
-- Ruta 1: País > Región
SELECT
    r.REGION_ID AS REGION_ID,
    r.REGION_TEXT AS REGION_TEXT,
    'REGIÓN' AS TIPO_NIVEL_GEOGRAFICO,
    p.PAIS_ID AS PAIS_ID,
    p.PAIS_TEXT AS PAIS_NOMBRE,
    r.SISORIGEN_ID AS SISTEMA_ORIGEN,
    r.MANDANTE AS MANDANTE,
    r.FECHA_CARGA AS FECHA_CARGA,
    r.ZONA_HORARIA AS ZONA_HORARIA
FROM CON.DIM_GEO_REGION r
JOIN CON.DIM_GEO_PAIS p ON r.PAIS_ID = p.PAIS_ID

UNION ALL

-- Ruta 2: País > Zona de Transporte
SELECT
    z.ZONATRANSPORTE_ID AS ZONATRANSPORTE_ID,
    z.ZONATRANSPORTE_TEXT AS ZONATRANSPORTE_TEXT,
    'ZONA DE TRANSPORTE' AS TIPO_NIVEL_GEOGRAFICO,
    p.PAIS_ID AS PAIS_ID,
    p.PAIS_TEXT AS PAIS_NOMBRE,
    z.SISORIGEN_ID AS SISTEMA_ORIGEN,
    z.MANDANTE AS MANDANTE,
    z.FECHA_CARGA AS FECHA_CARGA,
    z.ZONA_HORARIA AS ZONA_HORARIA
FROM CON.DIM_GEO_ZONATRANSPORTE z
JOIN CON.DIM_GEO_PAIS p ON z.PAIS_ID = p.PAIS_ID;


CREATE OR REPLACE STREAM mirroring.STREAM_DIM_GEO_GEOGRAFIA
ON TABLE mirroring.DIM_GEO_GEOGRAFIA;


SELECT
  z.zonatransporte_id,
  z.zonatransporte_text,
  r.region_id,
  r.region_text,
  p.pais_id,
  p.pais_text
FROM
  con.DIM_GEO_ZONATRANSPORTE z
JOIN
  con.DIM_GEO_REGION r ON z.region_id = r.region_id
JOIN
  con.DIM_GEO_PAIS p ON r.pais_id = p.pais_id