CREATE OR REPLACE TABLE MIRRORING.DIM_FIN_GASTOER(
	GASTOER_ID VARCHAR(10),
	GASTOER_TEXT VARCHAR(50),
    GASTOER_ID_TEXT VARCHAR(60)
);

CREATE OR REPLACE STREAM MIRRORING.STREAM_DIM_FIN_GASTOER
ON TABLE MIRRORING.DIM_FIN_GASTOER;