-- Este archivo pertenece a DIM_CLI_DESTINATARIO

CREATE OR REPLACE TABLE PRE.PDIM_CLI_DESTINATARIO (
    DESTINATARIO_ID VARCHAR(50),
    DESTINATARIO VARCHAR(10),
    ORGVENTAS_ID VARCHAR(4),
    CANALDISTRIB_ID VARCHAR(2),
    SECTOR_ID VARCHAR(2),
    COORDINADORDEST_ID VARCHAR(50),
    ASESORDEST_ID VARCHAR(50),
    DESTINATARIO_TEXT VARCHAR(50),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

