-- Este archivo pertenece a DIM_CLI_TIENDARECIBO

CREATE OR ALTER TABLE PRE.PDIM_CLI_TIENDARECIBO (
    TIENDARECIBO_ID VARCHAR,
    FUNCION_INTERLOCUTOR VARCHAR,
    TIENDARECIBO_TEXT VARCHAR,
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

