-- Este archivo pertenece a DIM_CLI_GRUPOCLIENTES2

CREATE OR ALTER TABLE PRE.PDIM_CLI_GRUPOCLIENTES2 (
    GRUPOCLIENTES2_ID VARCHAR(3),
    GRUPOCLIENTES2_TEXT VARCHAR(20),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

