-- Este archivo pertenece a DIM_CLI_EJECUTIVOCIS

CREATE OR REPLACE TABLE PRE.PDIM_CLI_EJECUTIVOCIS (
    EJECUTIVOCIS_ID VARCHAR,
    FUNCION_INTERLOCUTOR VARCHAR,
    EJECUTIVOCIS_TEXT VARCHAR,
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

