-- Este archivo pertenece a DIM_CLI_CLIENTE

CREATE OR REPLACE TABLE PRE.PDIM_CLI_CLIENTE (
    CLIENTE_ID VARCHAR(10),
    RAMO_ID VARCHAR(4),
    GRUPOSOLICITANTE_ID VARCHAR(10),
    PAIS_ID VARCHAR(3),
    REGION_ID VARCHAR(3),
    LOCALIDAD VARCHAR(35),
    RFC_ID VARCHAR(16),
    CLASIFICACIONCLIENTE_ID VARCHAR(2),
    CODIGOPOSTAL VARCHAR(10),
    CALLE VARCHAR(35),
    GRUPOCUENTAS_ID VARCHAR(35),
    CLIENTE_TEXT VARCHAR(35),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);

