CREATE OR REPLACE TABLE PRE.PDIM_FIN_DETALLECOMPREAL(
    DETALLECOMPREAL_ID,
    DETALLECOMPREAL_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  ACTDETL AS DETALLECOMPREAL_ID,
        TXTSH AS DETALLECOMPREAL_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0FM_ACTDETL_TEXT
WHERE LANGU = 'S';