CREATE OR REPLACE TABLE PRE.PDIM_FIN_CLASERIESGO(
    CLASERIESGO_ID,
    CLASERIESGO,
    CLASERIESGO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(KKBER,'_',CTLPC) AS CLASERIESGO_ID,
        CTLPC AS CLASERIESGO,
        RTEXT AS CLASERIESGO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0RISK_CATEG_TEXT
WHERE SPRAS = 'S';