CREATE OR REPLACE TABLE PRE.PDIM_FIN_GRUPOCREDCLIENTE(
    GRUPOCREDCLIENTE_ID,
    GRUPOCREDCLIENTE,
    GRUPOCREDCLIENTE_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(KKBER,'_',GRUPP) AS GRUPOCREDCLIENTE_ID,
        GRUPP AS GRUPOCREDCLIENTE,
        GTEXT AS GRUPOCREDCLIENTE_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0CRED_GROUP_TEXT
WHERE SPRAS = 'S';