CREATE OR ALTER TABLE PRE.PDIM_FIN_AREACTRLCDTO(
    AREACTRLCDTO_ID,
    AREACTRLCDTO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  KKBER AS AREACTRLCDTO_ID,
        KKBTX AS AREACTRLCDTO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0C_CTR_AREA_TEXT
WHERE SPRAS = 'S'
ORDER BY KKBER ASC;