CREATE OR ALTER TABLE PRE.PDIM_FIN_PROGRAMAPRES(
    PROGRAMAPRES_ID,
    PROGRAMAPRES,
    PROGRAMAPRES_TEXT,
    ENTIDADCP_ID,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(PROGRAMA.FMAREA,'_',PROGRAMA.MEASURE) AS PROGRAMAPRES_ID,
        PROGRAMA.MEASURE AS PROGRAMAPRES,
        TEXTO.DESCRIPTION AS PROGRAMAPRES_TEXT,
        PROGRAMA.FMAREA AS ENTIDADCP_ID,
        PROGRAMA.SISORIGEN_ID,
        PROGRAMA.MANDANTE,
        PROGRAMA.FECHA_CARGA,
        PROGRAMA.ZONA_HORARIA
FROM RAW.SQ1_EXT_0PU_MEASURE_ATTR AS PROGRAMA

LEFT JOIN RAW.SQ1_EXT_0PU_MEASURE_TEXT AS TEXTO

ON PROGRAMA.MEASURE = TEXTO.MEASURE

WHERE TEXTO.LANGUAGE = 'S';