CREATE OR ALTER TABLE PRE.PDIM_FIN_AREACTRLCDTO(
    AREACTRLCDTO_ID VARCHAR(4),
	AREACTRLCDTO_TEXT VARCHAR(35),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);