CREATE OR ALTER TABLE PRE.PDIM_FIN_EQUIPORESPCREDITO(
    EQUIPORESPCREDITO_ID,
    EQUIPORESPCREDITO,
    EQUIPORESPCREDITO_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(KKBER,'_',SBGRP) AS EQUIPORESPCREDITO_ID,
        SBGRP AS EQUIPORESPCREDITO,
        TXTMD AS EQUIPORESPCREDITO_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0REPR_GROUP_TEXT;