CREATE OR ALTER TABLE PRE.PDIM_FIN_CENTROGESTOR(
    CENTROGESTOR_ID VARCHAR(21),
	ENTIDADCP_ID VARCHAR(4),
	CENTROGESTOR VARCHAR(16),
	CENTROGESTOR_TEXT VARCHAR(40),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);