CREATE OR REPLACE TABLE PRE.PDIM_FIN_CUENTA(
    CUENTA_ID VARCHAR(15),
    SOCIEDADCO_ID VARCHAR(4),
    CUENTA VARCHAR(10),
    CUENTA_TEXT VARCHAR(40),
    SUBDIVISION_ID VARCHAR(132),
    SUBDIVISION_TEXT VARCHAR(40),
    SISORIGEN_ID VARCHAR(4),
    MANDANTE VARCHAR(4),
    FECHA_CARGA TIMESTAMP_TZ,
    ZONA_HORARIA VARCHAR(10)
);


SELECT * FROM PRE.PDIM_FIN_CUENTA;