CREATE OR REPLACE TABLE PRE.PDIM_FIN_POSICIONPRES(
    POSICIONPRES_ID,
    POSICIONPRES,
    POSICIONPRES_TEXT,
    ENTIDADCP_ID,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(POSICIONPRES.FIKRS,'_',POSICIONPRES.FIPEX) AS POSICIONPRES_ID,
        POSICIONPRES.FIPEX AS POSICIONPRES,
        TEXTO.TXTLG AS POSICIONPRES_TEXT,
        POSICIONPRES.FIKRS AS ENTIDADCP_ID,
        POSICIONPRES.SISORIGEN_ID,
        POSICIONPRES.MANDANTE,
        POSICIONPRES.FECHA_CARGA,
        POSICIONPRES.ZONA_HORARIA
FROM RAW.SQ1_EXT_0CMMT_ITEM_PU_ATTR AS POSICIONPRES

LEFT JOIN RAW.SQ1_EXT_0CMMT_ITEM_PU_TEXT AS TEXTO
ON POSICIONPRES.FIPEX = TEXTO.FIPEX
WHERE LANGU = 'S';

