CREATE OR REPLACE TABLE PRE.PDIM_FIN_PROGRAMAPRES(
    PROGRAMAPRES_ID,
    PROGRAMAPRES,
    PROGRAMAPRES_TEXT,
    ENTIDADCP_ID,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  PROGRAMAFILT.PROGRAMAPRES_ID,
        PROGRAMAFILT.PROGRAMAPRES,
        TEXTO.DESCRIPTION AS PROGRAMAPRES_TEXT,
        PROGRAMAFILT.ENTIDADCP_ID,
        PROGRAMAFILT.SISORIGEN_ID,
        PROGRAMAFILT.MANDANTE,
        PROGRAMAFILT.FECHA_CARGA,
        PROGRAMAFILT.ZONA_HORARIA
FROM (
        SELECT  CONCAT(PROGRAMA.FMAREA,'_',PROGRAMA.MEASURE) AS PROGRAMAPRES_ID,
                PROGRAMA.MEASURE AS PROGRAMAPRES,
                PROGRAMA.FMAREA AS ENTIDADCP_ID,
                PROGRAMA.SISORIGEN_ID,
                PROGRAMA.MANDANTE,
                PROGRAMA.FECHA_CARGA,
                PROGRAMA.ZONA_HORARIA
        FROM    (SELECT DISTINCT *
                FROM RAW.SQ1_EXT_0PU_MEASURE_ATTR) AS PROGRAMA
        WHERE ENTIDADCP_ID = 'FMGL'
) AS PROGRAMAFILT

LEFT JOIN RAW.SQ1_EXT_0PU_MEASURE_TEXT AS TEXTO
ON PROGRAMAFILT.PROGRAMAPRES_ID = CONCAT(TEXTO.FMAREA,'_',TEXTO.MEASURE)

WHERE TEXTO.LANGUAGE = 'S'