CREATE OR REPLACE TABLE PRE.PDIM_FIN_VERSION(
    VERSION_ID,
    VERSION_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  VERSI AS VERSION_ID,
        VTEXT AS VERSION_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0VERSION_TEXT
WHERE SPRAS = 'S';