CREATE OR REPLACE TABLE PRE.PDIM_FIN_CATEGORIAPRES(
    CATEGORIAPRES_ID,
    CATEGORIAPRES_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  KEY1 AS CATEGORIAPRES_ID,
        TXTLG AS CATEGORIAPRES_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0FM_BUCAT_TEXT
WHERE LANGU = 'S';