CREATE OR ALTER TABLE PRE.PDIM_FIN_ENTIDADCP(
    ENTIDADCP_ID,
    ENTIDADCP_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  ENTIDAD.FIKRS AS ENTIDADCP_ID,
        TEXTO.TXTMD AS ENTIDADCP_TEXT,
        ENTIDAD.SISORIGEN_ID,
        ENTIDAD.MANDANTE,
        ENTIDAD.FECHA_CARGA,
        ENTIDAD.ZONA_HORARIA
FROM RAW.SQ1_EXT_0FM_AREA_ATTR AS ENTIDAD

LEFT JOIN RAW.SQ1_EXT_0FM_AREA_TEXT AS TEXTO

ON ENTIDAD.FIKRS = TEXTO.FIKRS

WHERE LANGU = 'S';