CREATE OR ALTER TABLE PRE.PDIM_FIN_CENTROGESTOR(
    CENTROGESTOR_ID,
    ENTIDADCP_ID,
    CENTROGESTOR,
    CENTROGESTOR_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  CONCAT(CENTROGES.FIKRS,'_',CENTROGES.FICTR) AS CENTROGESTOR_ID,
        CENTROGES.FIKRS AS ENTIDADCP_ID,
        CENTROGES.FICTR AS CENTROGESTOR,
        TEXTO.TXTMD AS CENTROGESTOR_TEXT,
        CENTROGES.SISORIGEN_ID,
        CENTROGES.MANDANTE,
        CENTROGES.FECHA_CARGA,
        CENTROGES.ZONA_HORARIA
FROM RAW.SQ1_EXT_0FUNDS_CTR_ATTR AS CENTROGES

LEFT JOIN RAW.SQ1_EXT_0FUNDS_CTR_TEXT AS TEXTO

ON CENTROGES.FICTR = TEXTO.FICTR

WHERE LANGU = 'S';