CREATE OR REPLACE TABLE PRE.PDIM_DOC_CLASEDOCFI(
    CLASEDOCFI_ID,
    CLASEDOCFI_TEXT,
    SISORIGEN_ID,
    MANDANTE,
    FECHA_CARGA,
    ZONA_HORARIA
) AS

SELECT  BLART AS CLASEDOCFI_ID,
        LTEXT AS CLASEDOCFI_TEXT,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
FROM RAW.SQ1_EXT_0AC_DOC_TYP_TEXT
WHERE SPRAS = 'S';