create or replace TABLE RAW.FILE_XLS_LOG_ADH_ABASTECIMIENTOS_PCP (
    ANIOMES VARCHAR(6),
    SOCIEDAD_ID VARCHAR(4),
    CENTRO_ID VARCHAR(4),
    MATERIAL_ID VARCHAR(30),
    IND_PRECIOCOMPRA_PCP_LOC VARCHAR(20),
    MON_LOC VARCHAR(4)
);