CREATE OR ALTER TABLE PRE.PDIM_TRA_CLASETRANSPORTE (
CLASETRANSPORTE_ID	VARCHAR(4) PRIMARY KEY,
CLASETRANSPORTE_TEXT 	VARCHAR(20),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);


CREATE OR ALTER TABLE CON.DIM_TRA_CLASETRANSPORTE (
CLASETRANSPORTE_ID	VARCHAR(4) PRIMARY KEY,
CLASETRANSPORTE_TEXT	VARCHAR(20),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);
