CREATE OR ALTER TABLE PRE.PDIM_TRA_TRANSPORTISTA (
TRANSPORTISTA_ID	VARCHAR(10) PRIMARY KEY,
/* SE ELIMINAN LOS SIGIUENTES CAMPOS SOLICITUD DE DANIEL GORDILLO 23/06/2025 
CLIENTE_ID	VARCHAR(10),
REGION_ID	VARCHAR(3),
REGION_TEXT	VARCHAR(3),
CENTRO_ID	VARCHAR(4), */
TRANSPORTISTA_TEXT	VARCHAR(35),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);

CREATE OR ALTER TABLE CON.DIM_TRA_TRANSPORTISTA (
TRANSPORTISTA_ID	VARCHAR(10) PRIMARY KEY,
/* SE ELIMINAN LOS SIGIUENTES CAMPOS SOLICITUD DE DANIEL GORDILLO 23/06/2025 
CLIENTE_ID	VARCHAR(10),
REGION_ID	VARCHAR(3),
REGION_TEXT	VARCHAR(3),
CENTRO_ID	VARCHAR(4),  */
TRANSPORTISTA_TEXT	VARCHAR(35),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);