create or replace TABLE PRE.PDIM_TRA_CLASEEXPEDICION (
CLASEEXPEDICION_ID	VARCHAR(3) PRIMARY KEY,
CLASEEXPEDICION_TEXT	VARCHAR(40),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);

create or replace TABLE CON.DIM_TRA_CLASEEXPEDICION (
CLASEEXPEDICION_ID	VARCHAR(3) PRIMARY KEY,
CLASEEXPEDICION_TEXT	VARCHAR(40),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);