CREATE OR ALTER TABLE PRE.PDIM_TRA_RUTA (
RUTA_ID	VARCHAR(6) PRIMARY KEY,
RUTA_TEXT	VARCHAR(40),
SISORIGEN_ID	VARCHAR(4),
MANDANTE	VARCHAR(3),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);

CREATE OR ALTER TABLE CON.DIM_TRA_RUTA (
RUTA_ID	VARCHAR(6) PRIMARY KEY,
RUTA_TEXT	VARCHAR(40),
SISORIGEN_ID	VARCHAR(4),
MANDANTE	VARCHAR(3),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);