CREATE OR ALTER TABLE PRE.PDIM_TRA_TIPOTRANSPORTE (
TIPOTRANSPORTE_ID	VARCHAR(10) PRIMARY KEY,
TIPOTRANSPORTE_TEXT	VARCHAR(60),
SISORIGEN_ID	VARCHAR(3),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);

CREATE OR ALTER TABLE CON.DIM_TRA_TIPOTRANSPORTE (
TIPOTRANSPORTE_ID	VARCHAR(10) PRIMARY KEY,
TIPOTRANSPORTE_TEXT	VARCHAR(60),
SISORIGEN_ID	VARCHAR(5),
MANDANTE	VARCHAR(4),
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR(12)
);


--SELECT * FROM PRE.PDIM_TRA_TIPOTRANSPORTE;


INSERT INTO CON.DIM_TRA_TIPOTRANSPORTE
VALUES 
('1','TERRESTRE','FILE','',CURRENT_TIMESTAMP,RIGHT(CURRENT_TIMESTAMP,5)),
('2','MARITIMO','FILE','',CURRENT_TIMESTAMP,RIGHT(CURRENT_TIMESTAMP,5));

SELECT * FROM CON.DIM_TRA_TIPOTRANSPORTE;

DELETE FROM MIRRORING.DIM_TRA_TIPOTRANSPORTE;
INSERT INTO MIRRORING.DIM_TRA_TIPOTRANSPORTE
VALUES 
('1','TERRESTRE', '1 - TERRESTRE','FILE','',CURRENT_TIMESTAMP,RIGHT(CURRENT_TIMESTAMP,5)),
('2','MARITIMO','2 - MARITIMO','FILE','',CURRENT_TIMESTAMP,RIGHT(CURRENT_TIMESTAMP,5));
SELECT * FROM MIRRORING.DIM_TRA_TIPOTRANSPORTE;