CREATE OR REPLACE PROCEDURE CON.SP_CON_FCT_LOG_REV_ABASTECIMIENTOS_DELTA()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
/*
---------------------------------------------------------------------------------
 Versión:            2.0
 Fecha de creación:  2025-04-25
 Creador:            Juan Esteban Méndez N
 Descripción:        SP DELTA que transforma datos desde la capa PRE a CON para ABASTECIMIENTOS REV
---------------------------------------------------------------------------------
*/

DECLARE
    -- VARIABLES DE CONTROL
    F_INICIO        TIMESTAMP_NTZ(9);
    F_FIN           TIMESTAMP_NTZ(9);
    T_EJECUCION     NUMBER(38,0);
    ROWS_INSERTED   NUMBER(38,0);
    TEXTO           VARCHAR(200);
    FECHA_INICIO    VARCHAR(100);
    FECHA_FIN       VARCHAR(100);

BEGIN

    ---------------------------------------------------------------------------------
    -- STEP 1: LIMPIEZA DE DATOS EN LA TABLA CON
    ---------------------------------------------------------------------------------
    BEGIN

        SELECT CURRENT_TIMESTAMP() INTO :F_INICIO;

        DELETE FROM CON.FCT_LOG_REV_ABASTECIMIENTOS
        WHERE DOCCOMPRAS IN (SELECT DISTINCT EBELN FROM RAW.SQ1_EXT_2LIS_02_SCL
            WHERE FECHA_CARGA = (SELECT MAX(FECHA_CARGA) ------------ULTIMOS REGISTROS--------
                                FROM RAW.SQ1_EXT_2LIS_02_SCL)
                    AND TIPO = 'DELTA')
        ;

        SELECT CURRENT_TIMESTAMP() INTO :F_FIN;
        SELECT DATEDIFF(millisecond, :F_INICIO, :F_FIN) INTO :T_EJECUCION;
    EXCEPTION
        WHEN statement_error THEN
            SELECT ('Error en DELETE: ' || :sqlerrm) INTO :TEXTO;
    END;

    ---------------------------------------------------------------------------------
    -- STEP 2: INSERCIÓN DE DATOS DESDE PRE HACIA CON
    ---------------------------------------------------------------------------------
    BEGIN
        SELECT CURRENT_TIMESTAMP() INTO :F_INICIO;

        INSERT INTO CON.FCT_LOG_REV_ABASTECIMIENTOS(
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,

        IND_CANTIDAD_TOTAL,
        UM_PEDIDO,

        IND_IMPTE_COMPRA_PED,
        IND_IMPTE_FLETE_PED,
        IND_IMPTE_COMPRA_SIN_FLETE_PED,
        MON_PED,

        IND_IMPTE_COMPRA_LOC,
        IND_IMPTE_FLETE_LOC,
        IND_IMPTE_COMPRA_SIN_FLETE_LOC ,
        MON_LOC,

        IND_IMPTE_COMPRA_USD,
        IND_IMPTE_FLETE_USD,
        IND_IMPTE_COMPRA_SIN_FLETE_USD,
        MON_USD,

        IND_IMPTE_COMPRA_EUR,
        IND_IMPTE_FLETE_EUR,
        IND_IMPTE_COMPRA_SIN_FLETE_EUR,
        MON_EUR,

        TIPOCAMBIO_USD,
        TIPOCAMBIO_EUR,

        IND_CANT_DIAS_COLOCACION,
        IND_CANT_POSICIONES_PEDIDO,

        IND_CANT_EM_PEDIDO_ENTIEMPO, 
        IND_CANT_EM_COMPLETAS_ENTIEMPO, 
        IND_CANT_POS_COMPLETAS_ENTIEMPO,
        IND_CANT_POS_NOCOMPLETAS_ENTIEMPO,

        IND_CANT_EM_TOTAL_VENCIDAS,
        IND_CANT_DIASPONDERADOS,
        IND_CANT_DIASPODERADOS_ANT,
        IND_CANT_POS_TOTAL,

        CLAVEMP_LOC,
        CLAVEMP_USD,
        CLAVEMP_EUR,

        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
        )
        --------------------------------------------NIVEL DE SERVICIOS--------------------------------------------------

        ------------------------------------------- Fecha Entrega --------------------------------------------
        SELECT
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,

        0 AS IND_CANTIDAD_TOTAL,
        UM_PEDIDO,

        0 AS IND_IMPTE_COMPRA_PED,
        0 AS IND_IMPTE_FLETE_PED,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_PED,
        MON_PED,

        0 AS IND_IMPTE_COMPRA_LOC,
        0 AS IND_IMPTE_FLETE_LOC,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_LOC ,
        MON_LOC,

        0 AS IND_IMPTE_COMPRA_USD,
        0 AS IND_IMPTE_FLETE_USD,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_USD,
        MON_USD,

        0 AS IND_IMPTE_COMPRA_EUR,
        0 AS IND_IMPTE_FLETE_EUR,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_EUR,
        MON_EUR,

        0 AS TIPOCAMBIO_USD,
        0 AS TIPOCAMBIO_EUR,

        0 AS IND_CANT_DIAS_COLOCACION ,
        0 AS IND_CANT_POSICIONES_PEDIDO,

        SUM(IND_CANT_EM_PEDIDO_ENTIEMPO) AS IND_CANT_EM_PEDIDO_ENTIEMPO, 
        SUM(IND_CANT_EM_COMPLETAS_ENTIEMPO) AS IND_CANT_EM_COMPLETAS_ENTIEMPO, 
        CASE 
            WHEN GRUPOARTICULOS_ID IN ('000','001','102','104','107') 
            THEN IFF((SUM(IND_CANT_EM_COMPLETAS_ENTIEMPO)*100/SUM(IND_CANT_EM_PEDIDO_ENTIEMPO))>=70,1,0) 
            ELSE IFF((SUM(IND_CANT_EM_COMPLETAS_ENTIEMPO)*100/SUM(IND_CANT_EM_PEDIDO_ENTIEMPO))>=90,1,0) 
        END AS IND_CANT_POS_COMPLETAS_ENTIEMPO,
        CASE 
            WHEN GRUPOARTICULOS_ID IN ('000','001','102','104','107') 
            THEN IFF((SUM(IND_CANT_EM_COMPLETAS_ENTIEMPO)*100/SUM(IND_CANT_EM_PEDIDO_ENTIEMPO))>=70,0,1) 
            ELSE IFF((SUM(IND_CANT_EM_COMPLETAS_ENTIEMPO)*100/SUM(IND_CANT_EM_PEDIDO_ENTIEMPO))>=90,0,1) 
        END AS IND_CANT_POS_NOCOMPLETAS_ENTIEMPO,

        0 AS IND_CANT_EM_TOTAL_VENCIDAS,
        0 AS IND_CANT_DIASPONDERADOS,
        0 AS IND_CANT_DIASPODERADOS_ANT,
        IND_CANT_POS_COMPLETAS_ENTIEMPO + IND_CANT_POS_NOCOMPLETAS_ENTIEMPO AS IND_CANT_POS_TOTAL,

        CONCAT(MON_PED,'_',MON_LOC) AS CLAVEMP_LOC,
        CONCAT(MON_PED,'_USD') AS CLAVEMP_USD,
        CONCAT(MON_PED,'_EUR') AS CLAVEMP_EUR,

        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA

        FROM(

        SELECT
        SUBSTR(FECHA_ENTREGAPLANIFICADA, 0, 4) AS anio,
        SUBSTR(FECHA_ENTREGAPLANIFICADA, 6, 2) AS mes,
        CONCAT(SUBSTR(FECHA_ENTREGAPLANIFICADA, 0, 4), SUBSTR(FECHA_ENTREGAPLANIFICADA, 6, 2)) AS aniomes,
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        UM_PEDIDO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,
        MON_LOC,
        MON_PED,
        MON_USD,
        MON_EUR,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA,

        IND_CANTIDAD_TOTAL AS IND_CANT_EM_PEDIDO_ENTIEMPO, -- 0CPQUAOU --> ZCTD_PED
        0 AS IND_CANT_EM_COMPLETAS_ENTIEMPO -- 0CPDEOGQUOU --> ZCTD_ENT

        FROM PRE.PFCT_LOG_ABASTECIMIENTOS
        WHERE --DOCCOMPRAS_CLASE IN ('LP','NB','ZDNP','ZFIN','ZINV','ZIPT','ZNB','ZNBS','ZURG')
        CLAVEOPERACION IN ('001','011','021', '004','014','024', '005','015','025', '041','051','061')
        --AND SUBSTRING(ALMACENCENTRO_ID, 1, POSITION('_' IN ALMACENCENTRO_ID) - 1) IN ('', 'ME01', 'MP01', 'MP02', 'RF01', 'RF02')

        UNION ALL
            
        SELECT
        SUBSTR(FECHA_ENTREGAPLANIFICADA, 0, 4) AS anio,
        SUBSTR(FECHA_ENTREGAPLANIFICADA, 6, 2) AS mes,
        CONCAT(SUBSTR(FECHA_ENTREGAPLANIFICADA, 0, 4), SUBSTR(FECHA_ENTREGAPLANIFICADA, 6, 2)) AS aniomes,
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        UM_PEDIDO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,
        MON_LOC,
        MON_PED,
        MON_USD,
        MON_EUR,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA,

        0 AS IND_CANT_EM_PEDIDO_ENTIEMPO,
        IFF((DATEDIFF(DAY, FECHA_CONTABILIZACION, FECHA_ENTREGAOBJETIVO) >= 0), IND_CANTIDAD_TOTAL, 0) AS IND_CANT_EM_COMPLETAS_ENTIEMPO
        FROM PRE.PFCT_LOG_ABASTECIMIENTOS
        WHERE 
            --DOCCOMPRAS_CLASE IN ('LP','NB','ZDNP','ZFIN','ZINV','ZIPT','ZNB','ZNBS','ZURG')
            CLAVEOPERACION IN ('002','012','022','006','016','026')
            --AND SUBSTRING(ALMACENCENTRO_ID, 1, POSITION('_' IN ALMACENCENTRO_ID) - 1) IN ('',' ','ME01','MP01','MP02','RF01','RF02')
            AND IND_CANTIDAD_TOTAL <> 0)

        JOIN RAW.PARAMETROS_EXTRACCION
        ON EXTRACTOR = '2LIS_02_SCL'
        AND NEGOCIO = 'REVMEXICO'
        AND PARAMETRO = 'ORGCOMPRAS_ID'
        AND ORGCOMPRAS_ID BETWEEN R_INICIO AND R_FIN

        WHERE DOCCOMPRAS IN (SELECT DISTINCT EBELN FROM RAW.SQ1_EXT_2LIS_02_SCL
            WHERE FECHA_CARGA = (SELECT MAX(FECHA_CARGA) ------------ULTIMOS REGISTROS--------
                                FROM RAW.SQ1_EXT_2LIS_02_SCL)
                    AND TIPO = 'DELTA')

        GROUP BY 
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,
        UM_PEDIDO,
        MON_PED,
        MON_LOC,
        MON_USD,
        MON_EUR,
        CLAVEMP_LOC,
        CLAVEMP_USD,
        CLAVEMP_EUR,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA

        HAVING SUM(IND_CANT_EM_PEDIDO_ENTIEMPO) <> 0

        ----------------------------------------Fin Fecha Entrega --------------------------------------------
        UNION ALL
        ---------------------------------------- Fecha Contable --------------------------------------------

        SELECT
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,

        0 AS IND_CANTIDAD_TOTAL,
        UM_PEDIDO,

        0 AS IND_IMPTE_COMPRA_PED,
        0 AS IND_IMPTE_FLETE_PED,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_PED,
        MON_PED,

        0 AS IND_IMPTE_COMPRA_LOC,
        0 AS IND_IMPTE_FLETE_LOC,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_LOC ,
        MON_LOC,

        0 AS IND_IMPTE_COMPRA_USD,
        0 AS IND_IMPTE_FLETE_USD,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_USD,
        MON_USD,

        0 AS IND_IMPTE_COMPRA_EUR,
        0 AS IND_IMPTE_FLETE_EUR,
        0 AS IND_IMPTE_COMPRA_SIN_FLETE_EUR,
        MON_EUR,

        0 AS TIPOCAMBIO_USD,
        0 AS TIPOCAMBIO_EUR,

        0 AS IND_CANT_DIAS_COLOCACION ,
        0 AS IND_CANT_POSICIONES_PEDIDO,

        0 AS IND_CANT_EM_PEDIDO_ENTIEMPO, 
        0 AS IND_CANT_EM_COMPLETAS_ENTIEMPO, 
        0 AS IND_CANT_POS_COMPLETAS_ENTIEMPO,
        0 AS IND_CANT_POS_NOCOMPLETAS_ENTIEMPO,

        SUM(IFF((DATEDIFF(day, fecha_contabilizacion, FECHA_ENTREGAOBJETIVO) < 0), IND_CANTIDAD_TOTAL, 0)) AS IND_CANT_EM_TOTAL_VENCIDAS,
        SUM(DATEDIFF(day, fecha_reparto, fecha_contabilizacion) * IND_CANTIDAD_TOTAL) AS IND_CANT_DIASPONDERADOS,
        SUM(IFF((DATEDIFF(day, fecha_contabilizacion, FECHA_ENTREGAOBJETIVO) < 0),
            IFF(DATEDIFF(day, FECHA_ENTREGAOBJETIVO, fecha_contabilizacion) = 0,
                DATEDIFF(day, FECHA_ENTREGAOBJETIVO, fecha_contabilizacion),
                (DATEDIFF(day, FECHA_ENTREGAOBJETIVO, fecha_contabilizacion) * IND_CANTIDAD_TOTAL)
            ), 0
        )) AS IND_CANT_DIASPODERADOS_ANT,
            --COUNT(DISTINCT CONCAT(DOCCOMPRAS, '_', DOCCOMPRAS_POS, '_', DOCCOMPRAS_REPARTO)) AS IND_CANT_POS_TOTAL,
            0 AS IND_CANT_POS_TOTAL,

        CONCAT(MON_PED,'_',MON_LOC) AS CLAVEMP_LOC,
        CONCAT(MON_PED,'_USD') AS CLAVEMP_USD,
        CONCAT(MON_PED,'_EUR') AS CLAVEMP_EUR,

        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA

        FROM PRE.PFCT_LOG_ABASTECIMIENTOS

        JOIN RAW.PARAMETROS_EXTRACCION
        ON EXTRACTOR = '2LIS_02_SCL'
        AND NEGOCIO = 'REVMEXICO'
        AND PARAMETRO = 'ORGCOMPRAS_ID'
        AND ORGCOMPRAS_ID BETWEEN R_INICIO AND R_FIN

        WHERE --DOCCOMPRAS_CLASE IN ('LP', 'NB', 'ZDNP', 'ZFIN', 'ZINV', 'ZIPT', 'ZNB', 'ZNBS', 'ZURG')
        CLAVEOPERACION IN ('002','012','022','006','016','026')
        --AND SUBSTRING(ALMACENCENTRO_ID, 1, POSITION('_' IN ALMACENCENTRO_ID) - 1) IN ('ME01', 'MP01', 'MP02', 'RF01', 'RF02')

        AND DOCCOMPRAS IN (SELECT DISTINCT EBELN FROM RAW.SQ1_EXT_2LIS_02_SCL
            WHERE FECHA_CARGA = (SELECT MAX(FECHA_CARGA) ------------ULTIMOS REGISTROS--------
                                FROM RAW.SQ1_EXT_2LIS_02_SCL)
                    AND TIPO = 'DELTA')

        GROUP BY  
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,
        UM_PEDIDO,
        MON_PED,
        MON_LOC,
        MON_USD,
        MON_EUR,
        CLAVEMP_LOC,
        CLAVEMP_USD,
        CLAVEMP_EUR,
        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA
        ----------------------------------------Fin Fecha Contable --------------------------------------------
        ---------------------------------------- FIN NIVEL DE SERVICIOS--------------------------------------------------

        UNION ALL

        -----------------------------------BASE Y DIAS ------------------------------------------
        SELECT
        CENTRO_ID,
        ALMACENCENTRO_ID,
        ORGCOMPRAS_ID,
        GRUPOCOMPRAS_ID,
        MATERIAL_ID,
        MATERIALCENTRO_ID,
        GRUPOARTICULOS_ID,
        PROVEEDOR_ID,
        DOCCOMPRAS_CLASE,
        DOCCOMPRAS_TIPO,
        DOCCOMPRAS,
        DOCCOMPRAS_POS,
        DOCCOMPRAS_REPARTO,
        FECHA_LIBERACION,
        FECHA_DOCCOMPRAS,
        FECHA_ENTREGAPLANIFICADA,
        FECHA_ENTREGAOBJETIVO,
        FECHA_CONTABILIZACION,
        CLAVEOPERACION,
        SOLPED,
        SOLPED_POS,

        IND_CANTIDAD_TOTAL,
        UM_PEDIDO,

        IND_IMPTE_COMPRA_PED,
        IND_IMPTE_FLETE_PED,
        IND_IMPTE_COMPRA_SIN_FLETE_PED,
        MON_PED,

        IND_IMPTE_COMPRA_LOC,
        IND_IMPTE_FLETE_LOC,
        IND_IMPTE_COMPRA_SIN_FLETE_LOC ,
        MON_LOC,

        IND_IMPTE_COMPRA_USD,
        IND_IMPTE_FLETE_USD,
        IND_IMPTE_COMPRA_SIN_FLETE_USD,
        MON_USD,

        IND_IMPTE_COMPRA_EUR,
        IND_IMPTE_FLETE_EUR,
        IND_IMPTE_COMPRA_SIN_FLETE_EUR,
        MON_EUR,

        TIPOCAMBIO_USD,
        TIPOCAMBIO_EUR,

        IND_CANT_DIAS_COLOCACION,
        IND_CANT_POSICIONES_PEDIDO,

        0 AS IND_CANT_EM_PEDIDO_ENTIEMPO, 
        0 AS IND_CANT_EM_COMPLETAS_ENTIEMPO, 
        0 AS IND_CANT_POS_COMPLETAS_ENTIEMPO,
        0 AS IND_CANT_POS_NOCOMPLETAS_ENTIEMPO,

        0 AS IND_CANT_EM_TOTAL_VENCIDAS,
        0 AS IND_CANT_DIASPONDERADOS,
        0 AS IND_CANT_DIASPODERADOS_ANT,
        0 AS IND_CANT_POS_TOTAL,

        CLAVEMP_LOC,
        CLAVEMP_USD,
        CLAVEMP_EUR,

        SISORIGEN_ID,
        MANDANTE,
        FECHA_CARGA,
        ZONA_HORARIA

        FROM PRE.PFCT_LOG_ABASTECIMIENTOS

        JOIN RAW.PARAMETROS_EXTRACCION
        ON EXTRACTOR = '2LIS_02_SCL'
        AND NEGOCIO = 'REVMEXICO'
        AND PARAMETRO = 'ORGCOMPRAS_ID'
        AND ORGCOMPRAS_ID BETWEEN R_INICIO AND R_FIN

        WHERE DOCCOMPRAS IN (SELECT DISTINCT EBELN FROM RAW.SQ1_EXT_2LIS_02_SCL
            WHERE FECHA_CARGA = (SELECT MAX(FECHA_CARGA) ------------ULTIMOS REGISTROS--------
                                FROM RAW.SQ1_EXT_2LIS_02_SCL)
                    AND TIPO = 'DELTA')

----------------------------------FIN BASE Y DIAS ------------------------------------------
;

        -- Conteo de filas insertadas
        SELECT COUNT(*) INTO :ROWS_INSERTED FROM CON.FCT_LOG_REV_ABASTECIMIENTOS;

        SELECT CURRENT_TIMESTAMP() INTO :F_FIN;
        SELECT DATEDIFF(millisecond, :F_INICIO, :F_FIN) INTO :T_EJECUCION;
    EXCEPTION
        WHEN statement_error THEN
            SELECT ('Error en DELETE: ' || :sqlerrm) INTO :TEXTO;
            RETURN :TEXTO;
    END;

    ---------------------------------------------------------------------------------
    -- STEP 3: LOG
    ---------------------------------------------------------------------------------
    SELECT COALESCE(:TEXTO, 'EJECUCION CORRECTA') INTO :TEXTO;

    INSERT INTO LOGS.HISTORIAL_EJECUCIONES
    VALUES ('SP_CON_FCT_LOG_REV_ABASTECIMIENTOS_DELTA','CON.FCT_LOG_REV_ABASTECIMIENTOS', :F_INICIO, :F_FIN, :T_EJECUCION, :ROWS_INSERTED, :TEXTO );

    ---------------------------------------------------------------------------------
    -- STEP 4: FINALIZACIÓN
    ---------------------------------------------------------------------------------
    RETURN CONCAT('Complete - Filas insertadas: ', ROWS_INSERTED);

END;
$$;
 
 