create or replace TABLE CON.DIM_ABA_TASACAMBIO_ANT (
	CLAVEMONEDA VARCHAR(16777216),
	FECHA_TIPOCAMBIO DATE,
	MON_DES VARCHAR(5),
	MON_ORG VARCHAR(5),
	TASACAMBIO_ANT NUMBER(25,12),
	TIPO_TASACAMBIO_ANT VARCHAR(4),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);