create or replace TABLE CON.DIM_ABA_GRUPOCUENTASPROV (
	GRUPOCUENTASPROV_ID VARCHAR(4),
	GRUPOCUENTASPROV_TEXT VARCHAR(30),
	SISORIGEN_ID VARCHAR(3),
	MANDANTE VARCHAR(50),
	FECHA_CARGA VARCHAR(20),
	ZONA_HORARIA VARCHAR(10)
);