CREATE OR REPLACE TASK MIRRORING.TASK_FCT_FIN_ADH_VENTAS
	WAREHOUSE=LAMOSALAKE_DEV_WH
	WHEN SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_FIN_ADH_VENTAS_2')
	AS BEGIN

    -- RECREAR STREAM para eliminar basura
    -- create or replace stream MIRRORING.STREAM_FCT_FIN_ADH_CARTERA_2 on table MIRRORING.FCT_FIN_ADH_CARTERA_2;
    
    -- 1. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_FIN_ADH_CARTERA
    WHERE MODELO = 'VENTAS'
    AND SISORIGEN_ID <> 'BW4'; --Ventana de Tiempo
          

    -- 2. INSERTAR registros
    -- Insertar Todas la Ventas BW4
    INSERT INTO MIRRORING.FCT_FIN_ADH_CARTERA
    SELECT *
    FROM MIRRORING.VW_FCT_FIN_ADH_VENTAS_2 src
    WHERE src.MODELO = 'VENTAS'
    AND src.SISORIGEN_ID = 'BW4'
    AND NOT EXISTS (
            SELECT 1
            FROM MIRRORING.FCT_FIN_ADH_CARTERA tgt
            WHERE tgt.SISORIGEN_ID = src.SISORIGEN_ID
    );
    
    -- Insertar Todas la Ventas distintas BW4
    INSERT INTO MIRRORING.FCT_FIN_ADH_CARTERA
    SELECT *
    FROM MIRRORING.VW_FCT_FIN_ADH_VENTAS_2 src
    WHERE src.MODELO = 'VENTAS'
    AND src.SISORIGEN_ID <> 'BW4';

END;

ALTER TASK MIRRORING.TASK_FCT_FIN_ADH_VENTAS RESUME;


SELECT DISTINCT FECHACLAVE,ANIO_MES, SOCIEDAD_ID, SUM(VTA_IND_VENTA_REAL_MXN) AS VENTAS_MXN
FROM MIRRORING.FCT_FIN_ADH_CARTERA
WHERE MODELO = 'VENTAS'
GROUP BY FECHACLAVE,ANIO_MES,SOCIEDAD_ID
ORDER BY ANIO_MES DESC;

SELECT FECHACLAVE,ANIO_MES,SUM(IND_IMP_CARTERA_TOTAL_MDOC) AS CARTERA, SUM(VTA_IND_VENTA_REAL_MXN) AS VENTA
FROM MIRRORING.FCT_FIN_ADH_CARTERA
WHERE ANIO = '2025'
GROUP BY FECHACLAVE,ANIO_MES
ORDER BY ANIO_MES ASC;


DELETE FROM MIRRORING.FCT_FIN_ADH_CARTERA
WHERE MODELO = 'VENTAS'
AND SISORIGEN_ID = 'BW4';

SELECT  ANIOMES AS ANIO_MES,
        TO_DATE(CONCAT(ANIO_MES,'01'),'YYYYMMDD') AS FECHACLAVE
FROM MIRRORING.FCT_COM_ADH_COMERCIAL --CONFIRMACIÓN SI SE USARÁ HISTÓRICOS
WHERE SOCIEDAD_ID LIKE 'A%'
AND MODELO = 'VENTAS'
ORDER BY ANIO_MES DESC;

