CREATE OR REPLACE TASK MIRRORING.TASK_FCT_FIN_CONTROLPRESUPUESTAL
    warehouse=LAMOSALAKE_DEV_WH
	WHEN SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_FIN_CONTROLPRESUPUESTAL')
	AS BEGIN

    -- 1. TRUNCAR tabla temporal
    TRUNCATE TABLE MIRRORING.TR_FCT_FIN_CONTROLPRESUPUESTAL;

    -- 2. INSERTAR datos desde el stream a la temporal
    INSERT INTO MIRRORING.TR_FCT_FIN_CONTROLPRESUPUESTAL
    SELECT * FROM MIRRORING.STREAM_VW_FCT_FIN_CONTROLPRESUPUESTAL;

    -- 3. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_FIN_CONTROLPRESUPUESTAL AS FACTCONTROLPRESUPUESTAL
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_CONTROLPRESUPUESTAL
            WHERE METADATA$ACTION = 'DELETE'
    ) AS TR
    WHERE FACTCONTROLPRESUPUESTAL.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTCONTROLPRESUPUESTAL.ENTIDADCP_ID = TR.ENTIDADCP_ID
    AND FACTCONTROLPRESUPUESTAL.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTCONTROLPRESUPUESTAL.CUENTA_ID = TR.CUENTA_ID
    AND FACTCONTROLPRESUPUESTAL.FECHA_CONTABILIZACION = TR.FECHA_CONTABILIZACION;

    -- 4. INSERTAR o ACTUALIZAR registros nuevos o modificados
    MERGE INTO MIRRORING.FCT_FIN_CONTROLPRESUPUESTAL AS FACTCONTROLPRESUPUESTAL
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_CONTROLPRESUPUESTAL
            WHERE METADATA$ACTION = 'INSERT'
    ) AS TR
    
    ON FACTCONTROLPRESUPUESTAL.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTCONTROLPRESUPUESTAL.ENTIDADCP_ID = TR.ENTIDADCP_ID
    AND FACTCONTROLPRESUPUESTAL.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTCONTROLPRESUPUESTAL.CUENTA_ID = TR.CUENTA_ID
    AND FACTCONTROLPRESUPUESTAL.FECHA_CONTABILIZACION = TR.FECHA_CONTABILIZACION
    
    WHEN NOT MATCHED THEN INSERT (
        ANIO,
        MES,
        ANIOMES,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        ENTIDADCP_ID,
        CATEGORIAPRES_ID,
        TIPOVALOR_ID,
        FONDO_ID,
        CENTROGESTOR_ID,
        CENTROGESTOR,
        DETALLECOMPREAL_ID,
        INDICADOREST_ID,
        PROGRAMAPRES_ID,
        PROGRAMAPRES,
        POSICIONPRES_ID,
        POSICIONPRES,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        ACREEDOR_ID,
        DEUDOR_ID,
        GASTOER_ID,
        FECHA_CONTABILIZACION,
        TEXTO_TEXT,
        IND_PRESUPUESTO_ASIGNABLE,
        IND_PRESUPUESTO_ASIGNADO,
        IND_PRESUPUESTO_GASTOREAL,
        IND_PRESUPUESTO_GASTOCOMP,
        IND_PRESUPUESTO_DISPONIBLE,
        IND_PRESUPUESTO_ACTUAL,
        IND_PRESUPUESTO_COMPREAL,
        IND_PRESUPUESTO_VALORREAL,
        MON_ENTCP,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    ) VALUES (
        ANIO,
        MES,
        ANIOMES,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        ENTIDADCP_ID,
        CATEGORIAPRES_ID,
        TIPOVALOR_ID,
        FONDO_ID,
        CENTROGESTOR_ID,
        CENTROGESTOR,
        DETALLECOMPREAL_ID,
        INDICADOREST_ID,
        PROGRAMAPRES_ID,
        PROGRAMAPRES,
        POSICIONPRES_ID,
        POSICIONPRES,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        ACREEDOR_ID,
        DEUDOR_ID,
        GASTOER_ID,
        FECHA_CONTABILIZACION,
        TEXTO_TEXT,
        IND_PRESUPUESTO_ASIGNABLE,
        IND_PRESUPUESTO_ASIGNADO,
        IND_PRESUPUESTO_GASTOREAL,
        IND_PRESUPUESTO_GASTOCOMP,
        IND_PRESUPUESTO_DISPONIBLE,
        IND_PRESUPUESTO_ACTUAL,
        IND_PRESUPUESTO_COMPREAL,
        IND_PRESUPUESTO_VALORREAL,
        MON_ENTCP,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    );
END;