CREATE OR REPLACE TASK MIRRORING.TASK_FCT_FIN_GASTOSCONTROLPRES
    warehouse=LAMOSALAKE_DEV_WH
	WHEN SYSTEM$STREAM_HAS_DATA('STREAM_VW_FCT_FIN_GASTOSCONTROLPRES')
	AS BEGIN

    -- 1. TRUNCAR tabla temporal
    TRUNCATE TABLE MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES;

    -- 2. INSERTAR datos desde el stream a la temporal
    INSERT INTO MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES
    SELECT * FROM MIRRORING.STREAM_VW_FCT_FIN_GASTOSCONTROLPRES;

    -- 3. BORRAR registros eliminados
    DELETE FROM MIRRORING.FCT_FIN_GASTOSCONTROLPRES AS FACTGASTOSCONTROLPRES
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES
            WHERE METADATA$ACTION = 'DELETE'
    ) AS TR
    WHERE FACTGASTOSCONTROLPRES.SOCIEDAD_ID = TR.SOCIEDAD_ID
    AND FACTGASTOSCONTROLPRES.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTGASTOSCONTROLPRES.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTGASTOSCONTROLPRES.CUENTA_ID = TR.CUENTA_ID
    AND FACTGASTOSCONTROLPRES.ANIOMES = TR.ANIOMES
    AND FACTGASTOSCONTROLPRES.ENTIDADCP_ID = TR.ENTIDADCP_ID
    AND FACTGASTOSCONTROLPRES.FECHA_CONTABILIZACION = TR.FECHA_CONTABILIZACION;
    -- AND FACTGASTOSCONTROLPRES.CENTROGESTOR_ID = TR.CENTROGESTOR_ID
    -- AND FACTGASTOSCONTROLPRES.CUENTAMAYOR_ID = TR.CUENTAMAYOR_ID
    -- AND FACTGASTOSCONTROLPRES.CENTRO_ID = TR.CENTRO_ID
    -- AND FACTGASTOSCONTROLPRES.ACREEDOR_ID = TR.ACREEDOR_ID
    -- AND FACTGASTOSCONTROLPRES.CATEGORIAPRES_ID = TR.CATEGORIAPRES_ID
    -- AND FACTGASTOSCONTROLPRES.DEUDOR_ID = TR.DEUDOR_ID;

    -- 4. INSERTAR o ACTUALIZAR registros nuevos o modificados
    MERGE INTO MIRRORING.FCT_FIN_GASTOSCONTROLPRES AS FACTGASTOSCONTROLPRES
    USING (
            SELECT * FROM MIRRORING.TR_FCT_FIN_GASTOSCONTROLPRES
            WHERE METADATA$ACTION = 'INSERT'
    ) AS TR
    
    ON FACTGASTOSCONTROLPRES.SOCIEDAD_ID = TR.SOCIEDAD_ID
    AND FACTGASTOSCONTROLPRES.SOCIEDADCO_ID = TR.SOCIEDADCO_ID
    AND FACTGASTOSCONTROLPRES.CENTROCOSTO_ID = TR.CENTROCOSTO_ID
    AND FACTGASTOSCONTROLPRES.CUENTA_ID = TR.CUENTA_ID
    AND FACTGASTOSCONTROLPRES.ANIOMES = TR.ANIOMES
    AND FACTGASTOSCONTROLPRES.ENTIDADCP_ID = TR.ENTIDADCP_ID
    AND FACTGASTOSCONTROLPRES.FECHA_CONTABILIZACION = TR.FECHA_CONTABILIZACION
    AND FACTGASTOSCONTROLPRES.CENTROGESTOR_ID = TR.CENTROGESTOR_ID
    AND FACTGASTOSCONTROLPRES.CUENTAMAYOR_ID = TR.CUENTAMAYOR_ID
    AND FACTGASTOSCONTROLPRES.CENTRO_ID = TR.CENTRO_ID
    AND FACTGASTOSCONTROLPRES.ACREEDOR_ID = TR.ACREEDOR_ID
    AND FACTGASTOSCONTROLPRES.CATEGORIAPRES_ID = TR.CATEGORIAPRES_ID
    AND FACTGASTOSCONTROLPRES.DEUDOR_ID = TR.DEUDOR_ID
    
    WHEN NOT MATCHED THEN INSERT (
        MODELO,
        TIPO,
        ANIO,
        MES,
        ANIOMES,
        FECHA_CONTABILIZACION,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        CUENTAMAYOR_ID,
        GASTOER_ID,
        CENTRO_ID,
        ACREEDOR_ID,
        SOCIEDADGLASOC_ID,
        VERSION_ID,
        ENTIDADCP_ID,
        CATEGORIAPRES_ID,
        TIPOVALOR_ID,
        FONDO_ID,
        CENTROGESTOR_ID,
        CENTROGESTOR,
        DETALLECOMPREAL_ID,
        INDICADOREST_ID,
        PROGRAMAPRES_ID,
        PROGRAMAPRES,
        POSICIONPRES_ID,
        POSICIONPRES,
        DEUDOR_ID,
        TEXTO_TEXT,
        IND_GASTOPRESUPUESTO_MXN,
        IND_GASTOPRESUPUESTO_SOC,
        IND_GASTOPRESUPUESTO_USD,
        IND_GASTOPRESUPUESTO_V0_SOC,
        IND_GASTOPRESUPUESTO_V1_SOC,
        IND_GASTOPRESUPUESTO_V2_SOC,
        IND_GASTOPRESUPUESTO_V3_SOC,
        IND_GASTOPRESUPUESTO_V0_MXN,
        IND_GASTOPRESUPUESTO_V1_MXN,
        IND_GASTOPRESUPUESTO_V2_MXN,
        IND_GASTOPRESUPUESTO_V3_MXN,
        IND_GASTOPRESUPUESTO_V0_USD,
        IND_GASTOPRESUPUESTO_V1_USD,
        IND_GASTOPRESUPUESTO_V2_USD,
        IND_GASTOPRESUPUESTO_V3_USD,
        IND_GASTOREAL_MXN,
        MON_MXN,
        IND_GASTOREAL_USD,
        MON_USD,
        IND_GASTOREAL_SOC,
        MON_SOC,
        IND_PRESUPUESTO_ASIGNABLE,
        IND_PRESUPUESTO_ASIGNADO,
        IND_PRESUPUESTO_GASTOREAL,
        IND_PRESUPUESTO_GASTOCOMP,
        IND_PRESUPUESTO_DISPONIBLE,
        IND_PRESUPUESTO_ACTUAL,
        IND_PRESUPUESTO_COMPREAL,
        IND_PRESUPUESTO_VALORREAL,
        MON_ENTCP,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    ) VALUES (
        MODELO,
        TIPO,
        ANIO,
        MES,
        ANIOMES,
        FECHA_CONTABILIZACION,
        SOCIEDADCO_ID,
        SOCIEDAD_ID,
        CENTROCOSTO_ID,
        CENTROCOSTO,
        CUENTA_ID,
        CUENTA,
        CUENTAMAYOR_ID,
        GASTOER_ID,
        CENTRO_ID,
        ACREEDOR_ID,
        SOCIEDADGLASOC_ID,
        VERSION_ID,
        ENTIDADCP_ID,
        CATEGORIAPRES_ID,
        TIPOVALOR_ID,
        FONDO_ID,
        CENTROGESTOR_ID,
        CENTROGESTOR,
        DETALLECOMPREAL_ID,
        INDICADOREST_ID,
        PROGRAMAPRES_ID,
        PROGRAMAPRES,
        POSICIONPRES_ID,
        POSICIONPRES,
        DEUDOR_ID,
        TEXTO_TEXT,
        IND_GASTOPRESUPUESTO_MXN,
        IND_GASTOPRESUPUESTO_SOC,
        IND_GASTOPRESUPUESTO_USD,
        IND_GASTOPRESUPUESTO_V0_SOC,
        IND_GASTOPRESUPUESTO_V1_SOC,
        IND_GASTOPRESUPUESTO_V2_SOC,
        IND_GASTOPRESUPUESTO_V3_SOC,
        IND_GASTOPRESUPUESTO_V0_MXN,
        IND_GASTOPRESUPUESTO_V1_MXN,
        IND_GASTOPRESUPUESTO_V2_MXN,
        IND_GASTOPRESUPUESTO_V3_MXN,
        IND_GASTOPRESUPUESTO_V0_USD,
        IND_GASTOPRESUPUESTO_V1_USD,
        IND_GASTOPRESUPUESTO_V2_USD,
        IND_GASTOPRESUPUESTO_V3_USD,
        IND_GASTOREAL_MXN,
        MON_MXN,
        IND_GASTOREAL_USD,
        MON_USD,
        IND_GASTOREAL_SOC,
        MON_SOC,
        IND_PRESUPUESTO_ASIGNABLE,
        IND_PRESUPUESTO_ASIGNADO,
        IND_PRESUPUESTO_GASTOREAL,
        IND_PRESUPUESTO_GASTOCOMP,
        IND_PRESUPUESTO_DISPONIBLE,
        IND_PRESUPUESTO_ACTUAL,
        IND_PRESUPUESTO_COMPREAL,
        IND_PRESUPUESTO_VALORREAL,
        MON_ENTCP,
        MANDANTE,
        SISORIGEN_ID,
        FECHA_CARGA,
        ZONA_HORARIA
    );
END;