CREATE OR ALTER TABLE PRE.PDIM_DOC_BLOQUEOENTREGA_POS (
BLOQUEOENTREGA_POS_ID	VARCHAR PRIMARY KEY,
BLOQUEOENTREGA_POS_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

CREATE OR ALTER TABLE CON.DIM_DOC_BLOQUEOENTREGA_POS (
BLOQUEOENTREGA_POS_ID	VARCHAR PRIMARY KEY,
BLOQUEOENTREGA_POS_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);