CREATE OR ALTER TABLE PRE.PDIM_DOC_PERFILCF_CENTRO (
PERFILCFCENTRO_ID	VARCHAR PRIMARY KEY,
PERFILCFCENTRO	VARCHAR,
CENTRO_ID	VARCHAR,
PERFILCFCENTRO_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

CREATE OR ALTER TABLE CON.DIM_DOC_PERFILCF_CENTRO (
PERFILCFCENTRO_ID	VARCHAR PRIMARY KEY,
PERFILCFCENTRO	VARCHAR,
CENTRO_ID	VARCHAR,
PERFILCFCENTRO_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);