CREATE OR ALTER TABLE PRE.PDIM_DOC_CLASEENTREGA (
CLASEENTREGA_ID	VARCHAR PRIMARY KEY,
CLASEENTREGA_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

CREATE OR ALTER TABLE CON.DIM_DOC_CLASEENTREGA (
CLASEENTREGA_ID	VARCHAR PRIMARY KEY,
CLASEENTREGA_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);