create or replace TABLE PRE.PDIM_DOC_STATUSCREDITO (
STATUSCREDITO_ID	VARCHAR PRIMARY KEY,
STATUSCREDITO_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);

INSERT INTO PRE.PDIM_DOC_STATUSCREDITO 
VALUES
('A', 'Operación OK', 'SQ1', '500', CURRENT_TIMESTAMP, RIGHT(CURRENT_TIMESTAMP,5)),
('B', 'Operación no OK', 'SQ1', '500', CURRENT_TIMESTAMP, RIGHT(CURRENT_TIMESTAMP,5)),
('D', 'Operación liberada', 'SQ1', '500', CURRENT_TIMESTAMP, RIGHT(CURRENT_TIMESTAMP,5)),
('', 'No ejecutado', 'SQ1', '500', CURRENT_TIMESTAMP, RIGHT(CURRENT_TIMESTAMP,5))
('', 'No ejecutado', 'SQ1', '500', CURRENT_TIMESTAMP, RIGHT(CURRENT_TIMESTAMP,5))
;

create or replace TABLE CON.DIM_DOC_STATUSCREDITO (
STATUSCREDITO_ID	VARCHAR PRIMARY KEY,
STATUSCREDITO_TEXT	VARCHAR,
SISORIGEN_ID	VARCHAR,
MANDANTE	VARCHAR,
FECHA_CARGA	TIMESTAMP_TZ,
ZONA_HORARIA	VARCHAR
);


CALL CON.SP_CON_DIM_DOC_STATUSCREDITO();
