CREATE OR REPLACE view SEGURIDAD.VW_SEG_VISTA_GRAL
AS
WITH DIM_ROL AS (
    SELECT DISTINCT
        UR.USER_NM AS USUARIO,
        RD.ROLE_NM AS ROLE_USUARIO,
        RD.DIM AS DIM_ROL,
        RD.VALOR AS VALOR_ROL
    FROM 
        SEGURIDAD.SEG_USUARIO_ROLE UR
    INNER JOIN 
        SEGURIDAD.SEG_ROLE_DIMENSION RD
    ON 
        UR.ROLE_NM = RD.ROLE_NM
), FINAL AS (
    SELECT 
        USER_NM AS USUARIO, '' AS ROLE_USUARIO, DIM AS DIM_ROL, VALOR AS VALOR_ROL 
        FROM SEGURIDAD.SEG_USUARIO_DIMENSION
        UNION
    SELECT * FROM DIM_ROL
)

SELECT * FROM FINAL ORDER BY DIM_ROL;
;



